### ISSUE TITLE
allow installation on PHP 7.2

### ISSUE THREAD

**Issue by arosenhagen** [netz98/n98-magerun#1001]
with the official PHP 7.2 patches there's no need for the check of mcrypt in required php-extensions

**Comment by cmuench** [comment]
Is ext-mcrypt completely dropped in Magento 1?

**Comment by arosenhagen** [comment]
there is no need for mcrypt anymore with these patches - at least that should be the idea since there are no packages for php-mcrypt in version 7.2.
Hence installation fails while n98-magerun requires to install php-mcrypt.

**Comment by cmuench** [comment]
ok. Good to know.
We only have to remove one line of config to remove the check.

https://github.com/netz98/n98-magerun/blob/master/config.yaml#L551

**Comment by cmuench** [comment]
@arosenhagen I released V1.102.0 with a modified config.
