### ISSUE TITLE
Mage_Core_Model_Store_Exception

### ISSUE THREAD

**Issue by cesaroito** [netz98/n98-magerun#1006]
Hello,

I have a fresh Magento 1.9.3.9 and run n98-magerun version 1.102.0 .
Every time a try to run any command, show me this message (img attached).
<img width="1191" alt="screen shot 2018-10-09 at 16 28 32" src="https://user-images.githubusercontent.com/7848165/46693530-6d336e00-cbe0-11e8-97e6-796584700000.png">
Is there a way to solve this?
Thanks

**Comment by cmuench** [comment]
@cesaroito I checked your issue and installed a Magento CE 1.9.3.9 on my local machine. "Works on my machine".
Can you verify if the shop was installed correctly?
You can use the "sys:check" and "sys:info" commands.

**Comment by cesaroito** [comment]
@cmuench, thank you for your reply.
I try with this two commands. I use -vv to verbose and show me this two images with Exception.
<img width="1440" alt="screen shot 2018-10-10 at 05 44 15" src="https://user-images.githubusercontent.com/7848165/46724154-d43c3b80-cc4f-11e8-8580-93dc84afc03d.png">
<img width="1440" alt="screen shot 2018-10-10 at 05 44 54" src="https://user-images.githubusercontent.com/7848165/46724156-d43c3b80-cc4f-11e8-8215-05ab95b5b41a.png">

Best,

**Comment by pocallaghan** [comment]
This sounds like the issues people started reporting when SUPEE-10415 first came out. Validation was added for log file extension name, which means triggering a call to log tries to get a value from the config. This in turn  can cause issues if the log call is too early in the boot process. If you set `dev/log/active` to 0 directly in the DB does the problem disappear?

**Comment by cesaroito** [comment]
Hello @pocallaghan,
I make modifications that that you wrote to me, but the issue still the same. I use MAMP, MySQL 5.6.32 with OPcache.
Any ideas of possible solution for this issue?
Best

**Comment by cmuench** [comment]
@cesaroito Is your shop frontend working?

**Comment by cesaroito** [comment]
@cmuench  My frontend works fine. I can run all features off Backend and Frontend.
Just n98-magerun not work properly.

**Comment by cmuench** [comment]
@cesaroito Can you verify that the old version of n98-magerun is working? https://files.magerun.net/n98-magerun-1.101.1.phar

**Comment by cmuench** [comment]
@omerzs Does it work with the previous version of n98-magerun? ? https://files.magerun.net/n98-magerun-1.101.1.phar

**Comment by omerzs** [comment]
yes did try it , but its deff an environment issue nothing to do with magerun

**Comment by tylerssn** [comment]
@cesaroito did you get to the bottom of this?

**Comment by tylerssn** [comment]
I see this issue as having been explained here: https://maxchadwick.xyz/blog/supee-10415-causing-every-page-to-404. It seems that Magerun may be calling the logger before the store has been initialized.

**Comment by cmuench** [comment]
@tylerssn Do you mean that we can fix that in n98-magerun?

**Comment by tylerssn** [comment]
If I remember the point that I was trying to make (I really don't) I think the suggestion is to have magerun "tell" Magento that this would be tied to admin it some other scope.

Sorry 🤷‍♂️ best I have. It's been a year.
