### ISSUE TITLE
Uncaught Error: Call to a member function get() on null MagentoHelper.php:397

### ISSUE THREAD

**Issue by stefankb** [netz98/n98-magerun#1008]
Hi there,

We've just updated to 98-magerun2 version 3.0.0 and tried the following command (on a sever with PHP 7.0.30):

`$ n98-magerun2.phar --root-dir="/var/www/mydir" --compression=gzip --strip="@trade" db:dump /var/www/mydir/test_temp.sql.gz`

Unfortunately we are getting the following output:

`PHP Fatal error:  Uncaught Error: Call to a member function get() on null in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Util/Console/Helper/MagentoHelper.php:397
Stack trace:
#0 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Util/Console/Helper/MagentoHelper.php(379): N98\Util\Console\Helper\MagentoHelper->initBaseConfig()
#1 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Util/Console/Helper/DatabaseHelper.php(71): N98\Util\Console\Helper\MagentoHelper->getBaseConfig()
#2 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/Database/AbstractDatabaseCommand.php(59): N98\Util\Console\Helper\DatabaseHelper->detectDbSettings(Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/Database/DumpCommand.php(239): N98\Magento\Command\Database\AbstractDatabaseCommand->detectDbSettings(Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Command/Command.php(245): N98\Magento\Command\Da in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Util/Console/Helper/MagentoHelper.php on line 397`

This was working on the previous version. Any assistance would be greatly appreciated.

Cheers,

Stefan

**Comment by cmuench** [comment]
@stefankb Thanks for reporting. Please open the issue in the right project.

https://github.com/netz98/n98-magerun2/issues
