### ISSUE TITLE
install via homebrew failing

### ISSUE THREAD

**Issue by Julime** [netz98/n98-magerun#1010]
```
$ brew install n98-magerun
Error: No available formula with the name "n98-magerun"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```
Am i required to use the unshallow version?

Also, you recommend installing homebrew-php tap, which is deprecated

**Comment by cmuench** [comment]
@Julime The homebrew version was managed by an extern contributor in the "homebrew-php" tap which was removed.
At the moment I do not know a homebrew based installation.

Officially w offer phar downloads here: https://files.magerun.net/

**Comment by yclaes** [comment]
Any fix for this issue?

**Comment by cmuench** [comment]
We are not able to provide Homebrew support.
This is an alternative:
https://magerun.net/phive-support-for-n98-magerun/
