### ISSUE TITLE
Access Denied if password has special chars (or umlauts?)

### ISSUE THREAD

**Issue by hausfux** [netz98/n98-magerun#1011]
I can't dump my database I always get access denied. I used the command `./n98-magerun.phar db:dump --strip="@development"`.

I get:

 `mysqldump: Got error: 1045: "Access denied for user 'X'@'Y' (using password: YES)" when trying to connect`

I believe it is because the password is too complex and contains special chars like !%$§

**Update 1:**

I tested it again by using the `--password` option and received the error `-bash: !3: event not found`. My password does contain `!3` so it must be because of the `!`

**Update 2:**
I noticed that putty changed the output to this

![image](https://user-images.githubusercontent.com/47148259/53478082-52ba3e00-3a76-11e9-9531-6ac4152d4e8d.png)

This is a very small part of my password, the part where you can see the weird "symbol" is a  `ä` char, so I thought this is a putty problem.

So I checked my `locale` and figured out that LANG is empty, so I exported the german UTF-8 into lang `export LANG=de_DE.UTF-8` but it still fails with  `-bash: !3: event not found`

**Update 3**

It must be because of the `!` I removed them and now I get another error: ` [Symfony\Component\Console\Exception\RuntimeException]
  The "--password" option does not exist.`

**Comment by hausfux** [comment]
I was able to solve it by adding the option `--ansi`:

Full command:

`./n98-magerun.phar db:dump --strip="@development"`

**Comment by hausfux** [comment]
I have to reopen the issue ... I just tried it again today and I get `Access denied` even with the `--ansi` option.

**Comment by ktomk** [comment]
Tthe `bash: !3: event not found` message shows that what was entered is not what was thought would input  verbatim into the computer. This is a larger topic, one place to start is perhaps the section called [*QUOTING*  in the bash manpage](http://man7.org/linux/man-pages/man1/bash.1.html#QUOTING) for referencing.

If that message is from within what Magerun invokes (and this is how I understand your report), this means that the encoding of the password value is not properly handled within the utility code. The [`escapeshellarg`](http://php.net/manual/en/function.escapeshellarg.php) function is used to encode the password value (read from the XML configuration file; [reference](https://github.com/netz98/n98-magerun/blob/44b34c268e3352d5d7a4ef2cf9fe71581f71b893/src/N98/Magento/DbSettings.php#L214)) and checking for character encoding related issue w/ that function turns up quickly [the most voted comment in the manual](http://php.net/manual/de/function.escapeshellarg.php#99213):

> **phil at philfreo dot com / Aug 2010**
> When escapeshellarg() was stripping my non-ASCII characters from a UTF-8 string, adding the following fixed the problem:
>
>     <?php
>     setlocale(LC_CTYPE, "en_US.UTF-8");
>     ?>

Not saying that solves your issue, not at all. I don't know. You most likely can't even do that.You're not *Phil* is what I know. But maybe this rings a bell.

Also what I know is that the password within the XML file is UTF-8 encoded, and if it works with the PDO adapter, this is most likely then safe to transfer as UTF-8 byte sequence. So it must not get mangled. If *Phil's* comment is correct, it would get mangled if the locale is *not* UTF-8 for LC_CTYPE.

*Felipe* on the Bug #44945 report suggests this in my eyes much better looking code:

>     if (false == setlocale(LC_CTYPE, "UTF8", "en_US.UTF-8")) {
>     	die("skip setlocale() failed\n");
>     }

As you perhaps don't start hacking the Magerung core it's perhaps worth to try setting and exporting the LC_CTYPE environemtn variable in the shell you want to invoke the command:

~~~
$ LC_CTYPE="de_DE.UTF-8"; export LC_CTYPE
$ ./n98-magerun.phar db:dump --strip="@development"
~~~

Hope this helps to mitigate the problem.

## References

* [Bug #44945 escapeshellarg removes UTF-8 multi-byte characters (May 2008)](https://bugs.php.net/bug.php?id=44945)
* [Environment Variables - The Single UNIX ® Specification, Version 2 Copyright © 1997 The Open Group](http://pubs.opengroup.org/onlinepubs/7908799/xbd/envvar.html)
* [setlocale - set program locale - The Single UNIX ® Specification, Version 2 Copyright © 1997 The Open Group](http://pubs.opengroup.org/onlinepubs/7908799/xsh/setlocale.html)
* [Security Advisory: PHP's escapeshellcmd and escapeshellarg are insecure (Paul Buonopane; Feb 2017)](https://gist.github.com/Zenexer/40d02da5e07f151adeaeeaa11af9ab36)

**Comment by hausfux** [comment]
@ktomk It works if I call `LC_CTYPE="de_DE.UTF-8"; export LC_CTYPE` before the magerun command, that solved my issue, thx!

**Comment by ktomk** [comment]
Why you always close the issue that fast? Now again! First of all thanks for your feedback... .

Please test with LC_CTYPE only furthermost. The LANG setting should not play a role, if it does (isolated) please note it for the record (but only if isolated).

Your reporting means that magerun is affected by that PHP bug (which technically is no wonder b/c magerun runs on PHP), but your report also makes this report prominent.

So thanks for reporting. If you think setting and exporting LC_CTYPE is sufficient to make use of magerun for your case, you can keep the issue closed. With a bit ping and pong it could be argued, we've solved the issue together (knowing about the inner workuing).

However  if you say that setting up LC_CTYPE is too burdensome, please feel free to re-open as we need to find something to address it more within the core of magerun (if or how ever possible). So thanks a lot for your feedback.

P.S. some of the environments allow to export and set the variable in one command (e.g. my bash/zsh shell does): `$ LC_TYPE="de_DE.UTF-8" ./n98-magerun.phar db:dump [...]` so this might be more handy in your case, or  `$ export LC_TYPE="de_DE.UTF-8"; ./n98-magerun.phar db:dump [...]`. Please try what suits yourself best and tailor your shell environment to your needs.

**Comment by hausfux** [comment]
@ktomk Is it possible that you misspelled LC_TYPE? It should be LC_CTYPE? Isn't it?

**Comment by ktomk** [comment]
@hausfux yes, I misspelled in the two examples at the very end. So if you try then please with the 'C': LC_CTYPE.
