### ISSUE TITLE
Magento developer mode

### ISSUE THREAD

**Issue by seansan** [netz98/n98-magerun#1015]
(using last version as of today)

We are running `'MAGE_MODE' => 'developer',`

When we execute a command, even listing available commands it takes ~10-20 seconds before it responds ... is there some magic setting to switch? or does it have to do with `'MAGE_MODE' => 'developer',`

thanks!

**Comment by cmuench** [comment]
Is it also slow if you run `bin/magento`?
Theoretically the cache could be cold and/or the "generated" directory must be filled with auto generated code.

**Comment by cmuench** [comment]
Btw... This issue must be opened in the "netz98/n98-magerun2" repository.

**Comment by cmuench** [comment]
@seansan Can you re-create that issue in the "netz98/n98-magerun2" project?
