### ISSUE TITLE
Plugins directory configuration

### ISSUE THREAD

**Issue by dvershinin** [netz98/n98-magerun#1016]
## Intro

I've been packaging n98-magerun and Hypernode plugins for it [here](https://extras.getpagespeed.com/redhat/7/noarch/repoview/n98-magerun-module-hypernode.html). It works, but it doesn't follow system conventions, because I have to install plugins to `/usr/local/share/n98-magerun/modules` and packages should not tinker with `/usr/local`.

## What I'm trying to achieve now

I want n98-magerun to *also* check /usr/share/n98-magerun/modules in addition to /usr/local/share/n98-magerun/modules for loading addons. (and install the plugins to proper locations in `/usr/share/n98-magerun/modules`. In this way, system admins can do the `yum install` for packaged plugins and whatever wasn't packaged or requires local changes, properly goes to `/usr/local`.

## How it fails

By default, n98-magerun uses plugin -> folders configuration in [`config.yaml`](https://github.com/netz98/n98-magerun/blob/master/config.yaml#L10) to define directory(ies) that will be used for loading plugins

I thought I could ship package with `/etc/n98-magerun.yaml` and define plugin->folders according to system packaging conventions:

```
plugin:
  folders:
    - /usr/share/n98-magerun/modules
```

But n98-magerun does not make use of plugin -> folders configuration. Even putting the same to `/.n98-magerun.yaml` makes no effect. In a nutshell, problem is that plugin -> folders cannot be configured anywhere. I know that custom config files are loaded, as I confirmed it with strace / some other configuration parameters are being applied as expected.

I could have built my own `n98-magerun.phar`, I guess with the changes required, but that might be an overkill for the simple change.

Help? :)

**Comment by ktomk** [comment]
From what I remember this is a configuration merge in effect and it *should* merge arrays, so plugin folders *could* be added if this is in effect properly. From what you request it sounds like a sane operation, maybe @cmuench might comment on this one.

Building the phar also should not be too burdensome, the build script is within the repository. However what you ask for sounds like a good addition to have upstream.

**Comment by cmuench** [comment]
@dvershinin I previously respected only the "/usr/local/share" directory with the idea that someone will manually install the magerun modules.
For the case that a package is installed by a linux package manager, the "/usr/share" is the right location.

**Comment by cmuench** [comment]
Solution is already deployed.
