### ISSUE TITLE
Respect Default Website During customer:create

### ISSUE THREAD

**Issue by sprankhub** [netz98/n98-magerun#1021]
When using `customer:create` without explicitly mentioning the website, the default website should be taken. Currently, it seems that the website with the highest ID is used.

**Comment by Ig0r-M** [comment]
@cmuench any advice on how to debug with xdebug magerun on a blank magento project without db connection ?

**Comment by cmuench** [comment]
@Ig0r-M Without DB connection it's difficult.
I use a seperated installed Magento installation.

In my ZSH I had an alias to run the development version of n98-magerun.

`n98-magerun-dev='php <path-to-magerun-source>/bin/n98-magerun'`

In the meantime I use a docker setup based on the ddev tool where I mount the source code.

**Comment by IgorM-sudo** [comment]
@cmuench could you share repo to have sample data magento on local via docker ?

**Comment by cmuench** [comment]
@Ig0r-M I can share that. But today I am really busy. Maybe at the weekend.

**Comment by IgorM-sudo** [comment]
No rush.

**Comment by cmuench** [comment]
@Ig0r-M https://github.com/netz98/n98-magerun-magento1-ddev

**Comment by IgorM-sudo** [comment]
Thanks @cmuench while waiting for feedback starting preparing https://hub.docker.com/r/alexcheng/magento/ to have php7 and latest magento version(with aim later to have OpenMage one if there is not a docker image already).

Then planning to add n98-magerun as a submodule and setup debugger.

**Comment by IgorM-sudo** [comment]
@cmuench tring to setup debugging via CLI for n98-magerun using PHPStorm as IDE through ddev.

Current issue that i am experimenting is following:

```bash
Cannot find file '/opt/n98-magerun/bin/n98-magerun' locally. To fix it set server name by environment variable PHP_IDE_CONFIG and restart debug session.
```

**Comment by cmuench** [comment]
@Ig0r-Maybe a path mapping in debug server settings?

**Comment by IgorM92** [comment]
@sprankhub working through this bug dicovered that actually a question to select the website was intended to appear as done in done past.

@cmuench a couple of things:
1. Managed to setup debugging of magerun, thanks for your contribution.
2. This bug appearead in a01062eb739c7fcfafe67728d47967c5b4a80daf
3. PR to fix it -> https://github.com/netz98/n98-magerun/pull/1054


**How it was intented to work**
![image](https://user-images.githubusercontent.com/7593380/80863868-04ef2600-8c77-11ea-93af-06f4bd650f4c.png)
