### ISSUE TITLE
update twig/twig to version later than 1.37.1

### ISSUE THREAD

**Issue by wb-lime** [netz98/n98-magerun#1024]
Current version of twig in the composer lock (v1.31.0) is reported as a vulnerable package when using sensio security checker.

See: https://symfony.com/blog/twig-sandbox-information-disclosure

Sensio security checker: https://github.com/sensiolabs/security-checker

**Comment by cmuench** [comment]
@wb-lime I had to drop support for PHP 5.3. I think that's fair five years after official support stop ;-)
Fix is already in develop branch.
