### ISSUE TITLE
Problem with PhpParser (Owebia) and n98-magerun

### ISSUE THREAD

**Issue by PauGNU** [netz98/n98-magerun#1027]
Hi,

Since I installed the last magento Owebia Advanced Shipping module, when I try to execute operations with n98magerun I get always the error:

`$ n98-magerun.phar cache:clean ## or cache:flush
PHP Fatal error: Cannot declare class PhpParser\Autoloader, because the name is already in use in /var/www/brildor.lxc/src/lib/PhpParser/Autoloader.php on line 8`

Any idea why this conflict is happening? Does n98magerun use phpparser as well and this could be creating the issue?

* n98magerun is updated to the last version
* owebia is the release 2.6.8
* Magento is 1.9.4.1

Thanks

**Comment by ktomk** [comment]
I don''t think that magerun ships with PhpParser, the first Idea I got is that the module itself is loaded twice. Must not be by the module on it's ow but could and. From the path and the class name looks like there is a try to initialize an autoloader.

**Comment by PauGNU** [comment]
Hi @ktomk ,

I reported this issue on owebia side as well:
https://github.com/owebia/magento1-module-advanced-shipping/issues/13

It seems that nikic\php-parser is actually included in n98-magerun.

**Comment by cmuench** [comment]
@PauGNU Yes, the PHPParser is used. If I understand, the next version of the owebia module will solve the problem. So we can ignore that problem here.

**Comment by cmuench** [comment]
Close. Won't fix.
