### ISSUE TITLE
Magerun fails with a memory error when running a large magerun-scripts

### ISSUE THREAD

**Issue by kolaente** [netz98/n98-magerun#1045]
I was importing a lot of config values with a magerun-script I had exported previously.

It failed after a while with a memory exception: ![image](https://user-images.githubusercontent.com/13721712/72134792-2903c000-3385-11ea-86ba-3545e8dfa356.png)

It executes ~130 items each time I run it.

The php cli does not have a memory limit (set to `-1`).

The system has a total of 16GB ram available, when I started the magerun command, it had > 11 GB available
To me, this looks like a bug either in magerun or magento, since the system has at least 10GB of memory available, which should be more than enough.

**Comment by cmuench** [comment]
That's a common problem of running commands in commands.
Currently we do not have a solution.

See also: https://github.com/netz98/n98-magerun2/issues/447

**Comment by cmuench** [comment]
Close as duplicate of #447
