### ISSUE TITLE
Magento 1 app/etc/local.xml is also cached, cache:clean wont work if database user is wrong

### ISSUE THREAD

**Issue by imakin** [netz98/n98-magerun#1046]
n98-magerun version 1.103.1 by netz98 GmbH

if somehow the local.xml has wrong database username and it be cached, the next time you want to run `cache:clean` would output like this

`[Zend_Db_Adapter_Exception]
SQLSTATE[HY000] [1044] Access denied for user 'someuser'@'localhost' to database 'somedatabase'`

at this rate, the cache is stuck. we can't clean it.

to reproduce:

1. have app/etc/local.xml correct database username
2. cache clean it
3. open the webpage so that cache generated
4. change app/etc/local.xml database username to a wrong value
5. cache clean it
6. open the webpage so that cache generated
7. now correct the database username on app/etc/local.xml 
8. cache clean it (now it stucks)

 thanks for creating n98-magerun

**Comment by cmuench** [comment]
@imakin Can you please verify if you issue is fixed in develop version?

You can update to the dev-version with this command: `n98-magerun.phar self-update --unstable`

**Comment by imakin** [comment]
now it won't allow me to pass the 5th steps, **which is good**. so people should put correct database username before cleaning cache.
is this the expected behavior?

**Comment by cmuench** [comment]
@imakin Yes, i think so. We will not be responsible for wrong db credentials if anyone change it.

**Comment by cmuench** [comment]
I released that fix with 1.103.2.
