### ISSUE TITLE
Conflict with composer-installer

### ISSUE THREAD

**Issue by dvdsndr** [netz98/n98-magerun#1049]
Many Magento 1.9.X sites use composer and n98-magerun to manage their installations.

There is some conflict with the symfony framework using the latest php7.3 compatible magerun.

We get the following from n98-magerun:

PHP Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Command\HelpCommand::isHidden() in /var/www/magento/vendor/symfony/console/Descriptor/ApplicationDescription.php:108
Stack trace:

If rename the symfony folder loaded by compose-installer then the problem goes away. I can only assume that both composer-installer and magerun are using incompatible versions and the compose-installer Symfony version is already loaded thus magerun gets the wrong version.

**Comment by cmuench** [comment]
@dvdsndr the preferred installation method is to use the phar version of n98-magerun.
For n98-magerun2 we have a composer dist package which installs the phar via composer with zero dependencies.
We plan to provide also a dist package for n98-magerun1.

**Comment by cmuench** [comment]
@dvdsndr We published a new composer package which installs the phar file as composer dependency.

`composer require n98/magerun1-dist`

**Comment by dvdsndr** [comment]
Great. thanks
