### ISSUE TITLE
empty https://files.magerun.net/n98-magerun.phar

### ISSUE THREAD

**Issue by tmotyl** [netz98/n98-magerun#1050]
the url https://files.magerun.net/n98-magerun.phar
only show 
```
#!/usr/bin/env php
```
and nothing else

**Comment by robolmos** [comment]
Temporary workaround: https://files.magerun.net/n98-magerun-latest.phar

**Comment by cmuench** [comment]
@tmotyl We have moved the complete infrastructure. Problem should be solved.
Sorry if you had trouble during our site transfer.

New structure is described here: https://magerun.net/from-source-code-to-public-availability/
