### ISSUE TITLE
Uncaught Error: Class 'Mage_Enterprise_Index_Helper_Data'

### ISSUE THREAD

**Issue by Ig0r-M** [netz98/n98-magerun#1051]
**Magento CE** is not compatible with commands extending https://github.com/netz98/n98-magerun/blob/develop/src/N98/Magento/Command/Indexer/AbstractMviewIndexerCommand.php
And throwing error shown in title

Stack trace:
```bash
PHP Fatal error:  Uncaught Error: Class 'Mage_Enterprise_Index_Helper_Data' not found in /var/www/magento-project/magento/app/Mage.php:550
Stack trace:
#0 phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(393): Mage::helper('enterprise_inde...')
#1 phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/Indexer/AbstractMviewIndexerCommand.php(24): N98\Magento\Command\AbstractMagentoCommand->_getHelper('enterprise_inde...')
#2 phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/Indexer/ReindexMviewCommand.php(40): N98\Magento\Command\Indexer\AbstractMviewIndexerCommand->getIndexers()
#3 phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Command/Command.php(264): N98\Magento\Command\Indexer\ReindexMviewCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(473): Symfony\Component\Console\Command\ in /var/www/magento-project/magento/app/Mage.php on line 550
```

xDebug Frames:
![image](https://user-images.githubusercontent.com/22006850/78159885-199f8a80-743b-11ea-8401-281b41645f6b.png)

**Possible Solution** determine if magento is CE or EE and display warning message based of that by checking if Mage_Enterprise_Index_Helper_Data exists or adding following statement `if (Mage::helper('core')->isModuleEnabled('Enterprise_Index'))`

**Comment by Ig0r-M** [comment]
wanted to hear ideas about approach to fix.

**Comment by cmuench** [comment]
@Ig0r-M both sounds good.
The `class_exists` looks like the simpler solution. We have to test both variants. 
But we have also a Enterprise Edition Check in n98-magerun.
I will check that.

**Comment by cmuench** [comment]
@Ig0r-M fix is in develop build and will be publish as 1.103.3.

**Comment by Ig0r-M** [comment]
I am afraid that either it was not updated to 1.103.3 properly or updated and that still did not fix the issue.

**Magento version** 1.9.4.4
![Screenshot from 2020-04-03 09-50-40](https://user-images.githubusercontent.com/22006850/78342414-27672400-7591-11ea-861d-efe09d13654c.png)


![image](https://user-images.githubusercontent.com/22006850/78342433-2e8e3200-7591-11ea-9ec9-207160e107af.png)

**Comment by Ig0r-M** [comment]
@cmuench thoughts ?

**Comment by cmuench** [comment]
@Ig0r-M You are right. I will check that.

**Comment by cmuench** [comment]
@Ig0r-M was a server issue. Thanks for testing. Should update now.

**Comment by Ig0r-M** [comment]
Confirmed that they do not list in `magerun` commands
