### ISSUE TITLE
Error: Call to undefined method Mage_Core_Model_Resource_Setup::getAttributeSetId

### ISSUE THREAD

**Issue by hubertinio** [netz98/n98-magerun#1053]
After run sys:setup:run with that:
`$attribute_set_id = $this->getAttributeSetId('catalog_product', $attribute_set_name);`

**Comment by cmuench** [comment]
@hans2103 Can you provide additional information?
I need a stack trace. This can also be a issue of Magento and a installed 3rd party module.

**Comment by hans2103** [comment]
@cmuench euh... I think you want some additional information from @hubertinio instead.

**Comment by cmuench** [comment]
> @cmuench euh... I think you want some additional information from @hubertinio instead.

Yes, sorry.

**Comment by hubertinio** [comment]
@cmuench It is caused by command 
`bin/magento dev:module:create Adrem Test --add-all`

Result in etc/config.xml:
`<config>
        <global>
        <resources>
            <adrem_test_setup>
                <setup>
                    <module>Adrem_Test</module>
                </setup>
            </adrem_test_setup>
        </resources>
    </global>
</config>`

Expected:
`<config>
        <global>
       <resources>
            <adrem_test_setup>
                <setup>
                    <module>Adrem_Test</module>
                    <class>Adrem_Test_Model_Resource_Setup</class>
                </setup>
            </adrem_test_setup>
        </resources>
    </global>
</config>`

And related class created:
app/code/local/Adrem/Test/Model/Resource/Setup.php
`
<?php
class Adrem_Test_Model_Resource_Setup extends Mage_Eav_Model_Entity_Setup
{

}
`

I can fix it if you show me where :)

**Comment by cmuench** [comment]
@hubertinio you mean this line? https://github.com/netz98/n98-magerun/blob/develop/res/twig/dev/module/create/app/etc/modules/config.twig#L34

**Comment by hubertinio** [comment]
@cmuench yes, it is, give me an example how to create that class

**Comment by cmuench** [comment]
@hubertinio I checked the issue on my maschine. For me it's not a bug. If no class is specified, the default setup class is `Mage_Core_Model_Resource_Setup`. If the default setup class is used, then there is no need to create an own class which extends `Mage_Core_Model_Resource_Setup`.
An example is e.g. the `Mage_Directory` core module.

If your data is EAV related like in your case, a different setup class (or an own) can be defined. But that's part of the custom implementation and not of the code generator. Please note that you can also re-use existing EAV setup classes.

There are a lot of different Setup classes in Magento 1.

e,g.

- Mage_Sales_Model_Entity_Setup
- Mage_Tax_Model_Resource_Setup
- Mage_Index_Model_Resource_Setup
...

For me there is no need to change the current behavior.

**Comment by hubertinio** [comment]
You, right. EAV is used in almost all modules, maybe there should be an option for it?

**Comment by cmuench** [comment]
@hubertinio Feel free to contribute :-)
Main focus is Magento 2 for me.
