### ISSUE TITLE
Missing Delta Recorda

### ISSUE THREAD

**Issue by drinkingsouls** [netz98/n98-magerun#1055]
Hi,
This is just a question about the functionality of Magerun.
I have a Magento 2.3.4 install that I've been delta migrating from Magento 1.9.0.1. It was working fine but I recently had a corruption in the database and had to refer to a backup from about 5 days ago. I had also not done a delta for about 7 days prior to that.
I now cannot delta the changes from Magento 1 because it's already emptied the m2_cl tables so I have a gap of data between my restored database and now.
Can Magerun fill in the missing products and data so I can jump back in with Delta for changes going forward?
Thank you.

**Comment by cmuench** [comment]
@drinkingsouls No. n98-magerun is only utilizing mysql tools like mysqldump.

**Comment by drinkingsouls** [comment]
@cmuench I was refered to Magerun from [this Github Data Migration thread](https://github.com/magento/data-migration-tool/issues/316#issuecomment-366233807) where it was mentioned that it could be helpful with this? 
Is it not able to populate the m2_cl tables for missing delta data?
Thank you.

**Comment by cmuench** [comment]
@drinkingsouls that's a 3rd party plugin. I have not tried it before.
What are you missing in the core tool?

**Comment by cmuench** [comment]
@drinkingsouls that's a 3rd party plugin. I have not tried it before.
What are you missing in the core tool?
