### ISSUE TITLE
Is it possible to return support for php 5.5?

### ISSUE THREAD

**Issue by vitaliyreznikov** [netz98/n98-magerun#1093]
I've noticed that last version of n98-magerun doesn't support PHP 5.5.
Is it possible to return support for 5.5? It's really important for using the tool in CI process when we need to test something in different environments.

**Comment by cmuench** [comment]
@vitaliyreznikov we dropped officially support for this old PHP versions. Maybe it works but we do not test it anymore.
For older version we provide the old phar fles as well.
Have a look here: https://files.magerun.net/old_versions.php
