### ISSUE TITLE
MySQL 8 Compatibility

### ISSUE THREAD

**Issue by nniecws** [netz98/n98-magerun#1115]
There is an issue if you are running magerun on **MySQL 8.0.21**:

If you are trying to run a cron by **sys:cron:run** you get this error:

SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: '', query was: SELECT `main_table`.* FROM `cron_schedule` AS `main_table` WHERE (`status` = 'pending') AND (`job_code` = 'sitemap_generate') AND (`scheduled_at` =   
  '')
General error: 1525 Incorrect TIMESTAMP value: ''

On MySQL 8.0.21 empty string comparisons like **`scheduled_at` =   ''** are not allowed and throw an exception.

**Comment by cmuench** [comment]
@nniecws Officially Magento 1 is not compatible with MySQL 8. Which exact version of Magento are you using?

**Comment by nniecws** [comment]
Magento Version is 1.9.2.4

**Comment by cmuench** [comment]
@nniecws Thanks for the info. As this version is not supported by any Magento 1 release I need to figure out what steps are needed to make the tool MySQL 8 compatible. Last known supported MySQL version of Magento 1 is MySQL 5.7.
I wil change the ticket into a feature request.

**Comment by cmuench** [comment]
@nniecws I have contacted the OpenMage team which is the fork we support after the official Magento 1 EOL.
There is already support for MySQL 8.

See also https://github.com/OpenMage/magento-lts/pull/1011

I will check your issue in the latest OpenMage release with MySQL 8 in the next days (maybe next week).

**Comment by cmuench** [comment]
@nniecws Did some tests and cannot find a relation to our code. We delegate everything to the Mage_Cron module.
Maybe a stacktrace can clearify the issue.
Can you provide me a stacktrace by running n98-magerun.phar with "-vvv" option?

**Comment by nniecws** [comment]
@cmuench Here is a stacktrace. Hope it will help you.

[Stacktrace.txt](https://github.com/netz98/n98-magerun/files/5377247/Stacktrace.txt)

**Comment by cmuench** [comment]
@nniecws ok. That helps. The problem is part of the Aoe_Scheduler module. I can reprodce it on my machine.

Here:
https://github.com/AOEpeople/Aoe_Scheduler/blob/master/app/code/community/Aoe/Scheduler/Model/Schedule.php#L564

It does not re-use the already existing schedule object. The code there looks a bit weird.
I am not sure if I can fix it in n98-magerun but I will try it.

**Comment by cmuench** [comment]
@nniecws good news. Found a solution to fix it.
