### ISSUE TITLE
Custom config model

### ISSUE THREAD

**Issue by Sekiphp** [netz98/n98-magerun#1137]
Is it possible to change config model class during magerun command is runned? Because if someone have extended `Mage_Core_Model_Config` it is necessary to add this class as third argument to `Mage::run()`.

```
Mage::run(
    $mageRunCode,
    $mageRunType,
    ['config_model' => Namespace_Module_Model_Core_Config::class]
);
```

**Comment by midlan** [comment]
solution that seems working for me:

create file `app/etc/n98-magerun.yaml`

with content:
```
init:
  options:
    config_model: Namespace_Module_Model_Core_Config
```

**Comment by cmuench** [comment]
@Sekiphp The solution mentioned by @midlan should work.
It's a undocumented feature.
You can see the base config here: https://github.com/netz98/n98-magerun/blob/master/config.yaml#L24
