### ISSUE TITLE
Unshare Shared

### ISSUE THREAD

**Issue by ktomk** [netz98/n98-magerun#1149]
Looks to me the days of shared are over hence I propose to unshare the files in `shared` for Magerun.

I'm willing to do this, but would be good to know if you see anything against it @cmuench 

Follow-Ups:
- [x] Confirmation from Christans drone server for project phar builds
- [x] Check PSR-4 for project autoloading (filed per #1151)
- [x] Care-taking for magerun 2 to streamline unsharing + findings (filed in https://github.com/netz98/n98-magerun2/issues/693)
- [x] Check Required minimum PHP Version (testing w/ project PHPUnit requires PHP 7.1 something [via composer system-reqs checks])

**Comment by cmuench** [comment]
@ktomk I already removed the shared directory in n98-magerun2.
I think it's ok to unshare also for n98-magerun1. It's not providing too much synergies anymore.

**Comment by ktomk** [comment]
Those were the days ... ACK its more old cruft, lets clean things up here.

**Comment by cmuench** [comment]
Build and deploy of the phar to files.magerun.net was successful. No problem at all.

**Comment by ktomk** [comment]
Declare victory.

**Comment by cmuench** [comment]
@ktomk Thanks for sharing the info about the unshare shared victory.  😅
