### ISSUE TITLE
Bump composer/composer from 1.10.22 to ~2

### ISSUE THREAD

**Issue by boesbo** [netz98/n98-magerun#1189]
Are you planning to upgrade to composer 2?

## Problem and motivation
It would allow to work with Openmage-lts with Composer 2, since its dependent libraries have all been updated.

**Comment by cmuench** [comment]
@boesbo yes, we plan to upgrade. 
If you are using the lhar version then it should be already compatible.
The installation of n98-magerun via composer is not recommend.
If you really need it then we offer a special dist package which can install the phar as composer dependency.
See: https://packagist.org/packages/n98/magerun1-dist
