### ISSUE TITLE
Empty CronExpression leads to Exception in sys:cron:run

### ISSUE THREAD

**Issue by riconeitzel** [netz98/n98-magerun#1190]
The Database contains empty cron expressions:

```
448	default	0	crontab/default/jobs/catalog_product_alert/schedule/cron_expr	0 0 * * *	2020-01-15 12:29:31
449	default	0	crontab/default/jobs/catalog_product_alert/run/model		2021-03-31 12:04:24
780	default	0	crontab/default/jobs/currency_rates_update/schedule/cron_expr	0 0 * * *	2020-01-15 12:29:31
1546	default	0	crontab/default/jobs/magento_scheduled_import_export_log_clean/schedule/cron_expr	0 0 * * *	2020-01-15 12:29:31
1816	default	0	crontab/default/jobs/send_notification/schedule/cron_expr		2021-03-31 12:04:24
1817	default	0	crontab/default/jobs/send_notification/run/model		2021-03-31 12:04:24
2719	default	0	crontab/default/jobs/sitemap_generate/schedule/cron_expr	10 4 * * *	2020-01-15 12:29:31
2720	default	0	crontab/default/jobs/sitemap_generate/run/model		2021-03-31 12:04:24
12266	default	0	crontab/default/jobs/analytics_collect_data/schedule/cron_expr	00 02 * * *	2020-08-26 12:54:00
```

In Magento this is not a problem at all due to

\Magento\Cron\Observer\ProcessCronQueueObserver::_generateJobs

```php
    protected function _generateJobs($jobs, $exists, $groupId)
    {
        foreach ($jobs as $jobCode => $jobConfig) {
            $cronExpression = $this->getCronExpression($jobConfig);
            if (!$cronExpression) {
                continue;
            }

            $timeInterval = $this->getScheduleTimeInterval($groupId);
            $this->saveSchedule($jobCode, $cronExpression, $timeInterval, $exists);
        }
    }
```

Which filters these empty cron expressions before they get scheduled.

magerun however tries to create the schedule based on the expressions directly w/o filtering empty ones:

```
Exception trace:
  at ./vendor/magento/module-cron/Model/Schedule.php:112
 Magento\Cron\Model\Schedule->setCronExpr() at ./generated/code/Magento/Cron/Model/Schedule/Interceptor.php:37
 Magento\Cron\Model\Schedule\Interceptor->setCronExpr() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php:152
 N98\Magento\Command\System\Cron\AbstractCronCommand->getSchedule() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php:106
 N98\Magento\Command\System\Cron\AbstractCronCommand->getJobs() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php:239
 N98\Magento\Command\System\Cron\AbstractCronCommand->getJobForExecuteMethod() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/System/Cron/RunCommand.php:51
 N98\Magento\Command\System\Cron\RunCommand->execute() at ./vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:363
 N98\Magento\Command\AbstractMagentoCommand->run() at phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:1023
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:271
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php:226
 N98\Magento\Application->doRun() at phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/console/Application.php:147
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Application.php:329
 N98\Magento\Application->run() at /usr/local/bin/n98-magerun2.phar:8
```

I'd recommend to skip empty cron expressions and only fail on broken ones.

```php
if($cronExpression === '') { continue; }
```

**Comment by ktomk** [comment]
Skipping sounds right to me as well.

With which command were you able to provoke the exception?

And would you say some reporting (e.g. a warning) is useful?

**Comment by riconeitzel** [comment]
> With which command were you able to provoke the exception?

`sys:cron:run`

> And would you say some reporting (e.g. a warning) is useful?

nope … just skip it. If Magento doesn't log anything, we don't have to talk about it either 😄

**Comment by ktomk** [comment]
@riconeitzel Thx. Which Magento/Fork version are you reporting against?

**Comment by riconeitzel** [comment]
I this case it was multiple M2.3 instances but this code is present in all current Magento 2 versions: 

https://github.com/magento/magento2/blob/f121ac8359768b5ebcc7462574e58c36f34c52df/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L517-L528

**Comment by ktomk** [comment]
Okay, then this might be the wrong Github project, you may want to report that against https://github.com/netz98/n98-magerun2/issues/

It *could* be this is also an issue in n98-magerun (which is for Magento 1), so you can leave this issue open @riconeitzel , I'll check it later.

**Comment by riconeitzel** [comment]
aaah shoot … @cmuench you should change the github link on the magerun.net website then 😄

**Comment by ktomk** [comment]
@riconeitzel No problem, it could have been a regression in magerun 1, too (but it's not, just checked). And yes https://magerun.net/support/ looks like it could benefit from a little touch-up @cmuench .

**Comment by cmuench** [comment]
> @riconeitzel No problem, it could have been a regression in magerun 1, too (but it's not, just checked). And yes https://magerun.net/support/ looks like it could benefit from a little touch-up @cmuench .

:heavy_check_mark:  magerun.net support page updated

**Comment by ktomk** [comment]
Now that's a support portal compared to earlier ;) @cmuench
