### ISSUE TITLE
how to configure store view with a locale 

### ISSUE THREAD

**Issue by f1-outsourcing** [netz98/n98-magerun#1227]
Hi Christian,

I was wondering how I should configure the store view with a specific locale? I assume this goes via 

`n98-magerun.phar config:set`

But how do I know the path?

**Comment by cmuench** [comment]
@f1-outsourcing You can see the path in your core_config_data table.
It's always the Magento "section" + "group" + "field". So the path contains three parts, delimitted by a slash.

To see all stored configs you can run:

```
n98-magerun.phar config:get "*"
```

**Comment by f1-outsourcing** [comment]
Ok thanks, I will make a note of this! I found the configpath general/locale/code and my store is called 'Spanish' currently the locale is correctly set to es_ES

```
 bash-4.2$ php ../n98-magerun.phar config:get general/locale/code
+---------------------+----------+----------+-------+
| Path                | Scope    | Scope-ID | Value |
+---------------------+----------+----------+-------+
| general/locale/code | default  | 0        | en_GB |
| general/locale/code | websites | 2        | en_GB |
| general/locale/code | stores   | 2        | en_GB |
| general/locale/code | stores   | 3        | pl_PL |
| general/locale/code | stores   | 4        | nl_NL |
| general/locale/code | stores   | 6        | de_DE |
| general/locale/code | stores   | 7        | en_US |
| general/locale/code | stores   | 8        | fr_FR |
| general/locale/code | stores   | 9        | es_ES |
+---------------------+----------+----------+-------+
```

Say I want to change this back to english, Should the command not look more like this, same as when using the web interface? What is the logics behind having to look up the id first (and be forced to have to use some sort of command substitution and pipelines to create a one liner)? 

Magento 2
```
php -d disable_functions=none bin/magento config:set --scope=website --scope-code=testshop trans_email/ident_general/name 'adfasdf'
```

**Comment by cmuench** [comment]
Yes, you can define the scope of the setting. It depends on your config setting.
In Magento we have "global", "website" and "store view" (only called store) level.
The command does the same as the Adminhtml UI. It's designed for scripting.
In general you can also write setup scripts in your modules to set config values. The "config:get" command has also options to print the result in different formats like setup scripts.

**Comment by f1-outsourcing** [comment]
so maybe it is good to add a feature request `--scope-code` argument ?

**Comment by cmuench** [comment]
> so maybe it is good to add a feature request `--scope-code` argument ?

https://github.com/netz98/n98-magerun/blob/fbf15de6db1829596e9977927c34661ddb6e673a/src/N98/Magento/Command/Config/AbstractConfigCommand.php#L84

It is already possible to use the codes.

**Comment by f1-outsourcing** [comment]
Oh yes nice! I did not get that at all.
```
php -d disable_functions=none ../n98-magerun.phar config:set tax/defaults/country 'ES' --scope stores --scope-id 'es_es'
```
