### ISSUE TITLE
Php7/8: different output for dev:ide:phpstorm:meta

### ISSUE THREAD

**Issue by sreichel** [netz98/n98-magerun#1265]
## Describe the bug

`dev:ide:phpstorm:meta` has different output for php7 and 8.

## Expected behaviour

Same output for php7/8

## Steps to reproduce the issue

Run command with OpenMage ... 

- with php8 nothing should change
- with php7.3 (lowest supported version) sort order in generated files is slightly different

## Additional context

Low priority :heart:

**Comment by ktomk** [comment]
> with php7.3 (lowest supported version) sort order in generated files is slightly different

Does this change when you run it in a different locale? E.g.  could you try if it looks correct in the C locale (`LC_ALL=C`)?

**Comment by cmuench** [comment]
Reference #1256  PHP 8 implementation

**Comment by sreichel** [comment]
Low priority => no priority.

Think its not worth to dig deeper here.
