### ISSUE TITLE
released n98magerun for m1 demo data urls are wrong 

### ISSUE THREAD

**Issue by speedupmate** [netz98/n98-magerun#1266]
in currently released n98-magerun.phar for m1 demo data urls are wrong cause repo removed.

**Comment by sreichel** [comment]
After merging #1262 i deleted my repo. Fortunately, we are in the 90-day period, so i was able to restore the repo.

Please try again. :)

**Comment by sreichel** [comment]
Vote to close. (i'll keep that repo for thte next time)
