### ISSUE TITLE
Integration in Nix - upload build asset (phar) to Github release?

### ISSUE THREAD

**Issue by drupol** [netz98/n98-magerun#1276]
Hello,

I'm Pol, a PHP maintainer in the NixOS community.

Today @fballiano has open a [PR](https://github.com/NixOS/nixpkgs/pull/212249) to include Magerun 1 and 2 in Nix.

Since I do not know anything about Magento and its tooling, I was wondering if it would be possible to download the phar directly from the Github release, just like `php-cs-fixer` and many other tools are doing (https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases)

Attaching the phar could be automatic through a simple Github action upon tag. I see that it would not require a lot of work since [you already have a workflow](https://github.com/netz98/n98-magerun2/blob/develop/.github/workflows/phar_build_and_update.yml) building and testing the phar.

Having a clear and open process on how the phar is built on Github would clear out any security concerns and also would be automatically updated in Nix by an internal automated process. 

Let me know what you think about this.

Thanks.

**Comment by ktomk** [comment]
@cmuench I'd like to bring this forward as I think releasing nix packages is useful. one consequence would be to have the phar build artifact under releases on Github and running the build within the projects' Github actions.

Technically this can be additionally to the build pipeline that, IIRC, you run on your build box, but for sure opens an additional "release channel" on Github without any further changes on the release pipeline.

I'd take this in here on Magerun 1 to try it out, and it would be great if you can share your thoughts. I think it's useful to have the phar artifact build on Github anyway, as it is a source archive like the zip and tar.gz that is available already. Please let me know your thoughts.

**Comment by cmuench** [comment]
@ktomk i do not want to have the phar builds on Github.
We have a Cloudflare CDN in front of files.magerun.net which is super caching all the traffic.

@drupol We publish all phar files at https://files.magerun.net/

**Comment by drupol** [comment]
Thanks for the explanation, closing the issue.

The idea here was more about transparency and security concerns.

Having builds made by Github, on Github clear out those concerns.

On top of that, Github is already providing the CDN for you, so, this is something to not worry about.

**Comment by cmuench** [comment]
@drupol Maybe useful... We also provide a Composer  package which delivers the phar file, too.
https://packagist.org/packages/n98/magerun1-dist
https://packagist.org/packages/n98/magerun2-dist

**Comment by drupol** [comment]
> @drupol Maybe useful... We also provide a Composer package which delivers the phar file, too. https://packagist.org/packages/n98/magerun1-dist https://packagist.org/packages/n98/magerun2-dist

That might be useful for auto-updating in Nix, thanks.

However, one could argue that security wise, we don't really know what's in those phar. Hence, my will to have an open process on Github.

**Comment by fballiano** [comment]
> i do not want to have the phar builds on Github. We have a Cloudflare CDN in front of files.magerun.net which is super caching all the traffic.

@cmuench why not though? The Nix package manager can't download stuff the network at build time (for security reasons) and they'd like to have the phar on github also for security reason (it ties the source with the phar and avoid security concerns about the hosting of the phar files). It could simplify your build pipeline too.

**Comment by cmuench** [comment]
It do not want to have all the dependencies on Github. Currently I build the phar files on my own machine. The phar is also signed.
We provide a ./build.sh file in the repo for people who want to build the package. The n98-magerun2 repo contains also a phar build for PRs which are then attached to the PR.
What we are currenlty not doing is to release the phar als Github release. There is currently no plan to do that. Also the phar contains a self-update command which looks on files.magerun.net.

**Comment by fballiano** [comment]
dependencies wouldn't be on github tho, as you can see from https://github.com/netz98/n98-magerun/releases/tag/2.3.1-alpha1 the build worked without any change to the repo.

**Comment by cmuench** [comment]
@fballiano That's maybe possible but it's not what I want to have. Official phar files will be at files.magerun.net.

**Comment by cmuench** [comment]
@ktomk I reverted everything back. The new process forced several automatic environments to update to a alpha version. We have several thousand downloads everyday!
I had to rollback data on the files.magerun.net server.

**Comment by ktomk** [comment]
Ouch, I'm truly sorry. @cmuench

**Comment by cmuench** [comment]
@ktomk no worry. Next time let's talk. ;-)
