### ISSUE TITLE
where is build instruction (for el7/el9)

### ISSUE THREAD

**Issue by f1-outsourcing** [netz98/n98-magerun#1278]
```
[@test2 magento-n98-magerun]$ scl enable php74 bash
[@test2 magento-n98-magerun]$ ./build.sh
Building n98-magerun.phar...
./build.sh executed in /home/software/magento-n98-magerun
with: PHP 7.4.33 (cli) (built: Feb 14 2023 08:49:52) ( NTS )
./build.sh: line 87: /home/software/magento-n98-magerun/vendor/bin/composer: No such file or directory
with:
./build.sh: line 88: /home/software/magento-n98-magerun/vendor/bin/phing: No such file or directory
with:
building in /home/software/magento-n98-magerun/build/output
build version: 5d5a860 Bump symfony/process from 4.4.41 to 4.4.44
provision: ulimits (soft) set from 1024 to 4096 (hard) for faster phar builds...
build timestamp: 1679350567
Could not open input file: /home/software/magento-n98-magerun/vendor/bin/phing
trap: removing 'build/output'..
exit (1).
[@test2 magento-n98-magerun]$

```

**Comment by cmuench** [comment]
@f1-outsourcing The build.sh script is used internally from the n98-magerun team to provide new phar releases.
Theoretically it can be run.
In your case it seems that the build environment is not ready. There is currently no manual for that.
To get it up and running you need to install the dependencies first.

Try this:

- Install Composer 1 first. See: https://getcomposer.org/doc/00-intro.md
- Install project dependencies via composer `composer install` (this should install sphinx)
- Run the `./build.sh` script again

---

If you only want to run the tool, then you can download pre-build phar files here:
https://files.magerun.net/

If you prefer to install it as Magento 1 dependency then we offer the **n98/magerun1-dist** composer package.
Please also note that this is the Magento 1 version of the tool.
For Magento 2 we have a different repo here: http://github.com/netz98/n98-magerun2

**Comment by f1-outsourcing** [comment]
```
    121 magento-n98-magerun
    122 ===================
    123 yum install -y php74-php-cli php74-php-xml
    124 scl enable php74 bash
    125 cd magento-n98-magerun
    126
    127 install composer
    128 https://getcomposer.org/download/
    129 mkdir -p vendor/bin/
    130 mv composer.phar vendor/bin/composer
    131
    132 wget 'https://www.phing.info/get/phing-2.17.4.phar'
    133 mv vendor/bin/phing-2.17.4.phar vendor/bin/phing
    134
    135
    136 ./build.sh --changes
    137 you have to create code changes in build/output
```

Yes this is what I have documented now, maybe this should be done in the build script or so. What also is annoying is that the changes are not build it is copying stuff without the changes. Now I copying files back from build/output to the trunk to commit????

If you want others to commit this should be easy and straight forward.

**Comment by cmuench** [comment]
@f1-outsourcing Maybe you can describe what your purpose is.
We already offer ready-to-use phar files of the tool.
Building your own phar file is possible but not necessary to run the tool. 

If you need to build the phar we offer a setup based on [ddev](https://ddev.com/).

If ddev is installed your system then you can easily run this:

```sh
ddev start
ddev exec ./build.sh
```

Just tested with current develop branch:

![image](https://github.com/netz98/n98-magerun/assets/211294/0ea27f92-a624-48bb-bc15-6c0b11424fe9)

Please use latest develop branch. I did some smaller changes in the ddev setup.
