### ISSUE TITLE
TypeError when running sys:cron:list on PHP 8

### ISSUE THREAD

**Issue by azambon** [netz98/n98-magerun#1280]
## Describe the bug

With PHP 8.0 (and, I suspect, all later versions), the `sys:cron:list` command throws
```Uncaught TypeError: array_slice(): Argument #1 ($array) must be of type array, null given in phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php:103```

## Expected behaviour

Launching `sys:cron:list` I expect to see a list of all available crons.

## Steps to reproduce the issue

Install OpenMage 19.4.19 on PHP 8.0 (or later PHP versions)
Launch n98 sys:cron:list

## Technical details

- Host Machine OS: Linux
- PHP version: 8.0
- Magento version: OpenMage 19.4.19

## Possible Fix

There are two issues here.
The first is that the [check for the "always" cron expr](https://github.com/netz98/n98-magerun/blob/develop/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php#L88) is done incorrectly. It assumes that the provided cron expr is a string and, as such, uses the === operator for the comparison. In reality the expression is an instance of `Mage_Core_Model_Config_Element`, so the strict comparison always fails.
When this happens, the $array variable on line 101 is set to `null`, which leads to the second issue.
Up to PHP 7.4 the `array_slice` function had no argument type specified. It accepted `null` as the first argument and carried on, merely emitting a warning. Starting with PHP 8 the type of the first argument is specified as `array`, hence the error when the function is called with `null`.

I made a PR to fix the "always" expression check. This should fix the issue and prevent `null` values from being supplied to the `array_slice` function.

**Comment by azambon** [comment]
As far as I can see there has been no new version released since this bug was closed. The latest stable version is 2.3.0 from  May 23 **2022**.
So, as a matter of fact, the bug is still there. Any idea if/when this could make its way into a stable release?

**Comment by cmuench** [comment]
@azambon We have a merged a very big Changeset to the develop branch. This contains a lot of PHP 8 related changed to get the tool ready to run with the latests OpenMage versions and PHP 8.2.
At netz98 we do not work anymore on OpenMage or Magento 1 projects. So I do not have a good way to QA this.
The last changes were done by @sreichel.
We can only release a new Magerun version if it's tested by anyone.
Nevertheless it should be possible to update to the develop version which contain all the changes.

**Comment by cmuench** [comment]
btw... all the Infrastructure had to be replaced. All old Magento 1 servers are shutdown by Adobe.

**Comment by sreichel** [comment]
Will work,on this .... may take some days.
