### ISSUE TITLE
Remove DEFINER statements from db dumps

### ISSUE THREAD

**Issue by fbrnc** [netz98/n98-magerun#130]
Magento EE 1.13 (and 1.8) are using mysql triggers. When creating database dumps MySQLwill include a "DEFINER" statement with the current username and hosts. Importing this on another server won't work. 

I'm not sure if there is a cleaner way to do this, but removing the DEFINER statement works fine for me. 

cat dump.sql | sed -e 's/\/*[^_]_DEFINER=[^_]_*\///'

If this is the way to go the db:dump command could take care of doing this.

**Comment by convenient** [comment]
Just putting this here, I received the following error:

```
sed: RE error: illegal byte sequence
mysqldump: Got errno 32 on write
```

I had to run the following before triggering the `mysqldump` to get this to work correctly.

```
export LANG=C
```

A very useful feature, thanks

**Comment by tkn98** [comment]
hmm, sed is getting picky, nice. @convenient: Can you create a new ticket for this? Just reference to here so that it's clear when it was introduced.

**Comment by convenient** [comment]
@tkn98 Now that I look at it with fresh eyes it's clearly OSX being weird.

Original definition of `$LANG` is as follows
```
echo $LANG
en_GB.UTF-8
```

**Comment by tkn98** [comment]
@convenient: well, depends. if sed internally changes from default C locale for string operations to the one in the environment variable, then this is the issue. It's possible to have C strings but they are not valid UTF-8, e.g. other 8 bit ISO encodings in a dump file. I think your suggestion to export LANG=C  is reasonable for the intended operation.

**Comment by convenient** [comment]
Fair enough i'll open up another issue shortly. :+1:
