### ISSUE TITLE
Database dumps with @sales stripped group may result in inconsistent increment_id

### ISSUE THREAD

**Issue by jonpday** [netz98/n98-magerun#140]
The `increment_last_id` in `eav_entity_store` is checked by Magento when reserving new order increments. A database import that affects the sales tables should either warn the user, or (better) explicitly update the field per store so that it matches the new increment ID values. A failure here can lead to orders not being accepted by Magento due to duplicate key errors.

**Comment by tkn98** [comment]
Closing as no traction.

It should always be possible to insert a dump into an empty database. Just empty the database beforehand. We can't take care of issues that *might* appear if that is not the case as the existing data is undefined.

The exception that was reported looks more like a feature in Magento than a bug as the data was inconsistent and Magento realizes that the database-schema has not enough constraints to error at the db-import already.

Just saying, I'm open for good fixing suggestions, but in lack therefore will close.
