### ISSUE TITLE
Update Blog-Post?

### ISSUE THREAD

**Issue by sreichel** [netz98/n98-magerun#1448]
## Your Question

https://magerun.net/introducting-the-new-n98-magerun-module-system/

Is it possible to update that post?

I'd like to add some commands to a custom module, but from reading it is not clear where the files have to be placed.

@cmuench  Can you please provide a sample module (w/o any functionallty) to see the file structure?

**Comment by sreichel** [comment]
Forget about it ... without deploying the files, it cant work ...

**Comment by cmuench** [comment]
@sreichel nevertheless, there are some external modules documented here: https://github.com/netz98/n98-magerun/wiki/3rd-party-magerun-projects
