### ISSUE TITLE
APC settings

### ISSUE THREAD

**Issue by fbrnc** [netz98/n98-magerun#153]
It's a known issue that executing phars doesn't work well with apc enabled (this is still the case or is this resolved now?) Anyways this was driving me crazy today and I got all kinds of strange errors (Cannot redeclare class, class not found,...) 

Maybe it would be nice to check the apc ini settings while bootstrapping n98-magerun and printing a warning is problems have been detected similar to the checks done in the composer installer:
http://getcomposer.org/installer

This works for me as a workaround to make sure apc is disabled on a server where I'm not allowed to touch php.ini:

   php -d apc.enable_cli=0 n98-magerun.phar

**Comment by tkn98** [comment]
Cross-Reference: #314
