### ISSUE TITLE
Global Configuration Placeholders, i.e. for config:set

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#208]
Use case:

All developers use the same set of magerun scripts (they are checked into the VCS), but want to use some local variables, for example for the base URL after importing a test database.

In the global magerun config I set

foo_webroot = http://myhost/foobar

And then I can call

n98-magerun.phar config:set web/unsecure/base_url "$foo_webroot"

or (and this would be the more likely usecase) I can call this in a script.

Is this maybe already possible?

If not I would just implement this in the AbstractConfigCommand - or does this even make sense on a more general level?

**Comment by cmuench** [comment]
@amenk 
In the meantime the command was renamed to `config:store:set` and Adobe released the core `config:set` command and a way to define config's via env variables.
IMHO this is not up-to-date anymore.
Feel free to reopen the issue if I am wrong.
