### ISSUE TITLE
dev:console does not work when Magento is in a subfolder

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#209]
<pre>
me@here:~/local-workspace/example-shop$ n98-magerun.phar dev:con
Interactive shell

FATAL: Magento could not be initialized.
php > 
me@here:~/local-workspace/example-shop$ cd public/
me@here:~/local-workspace/example-shop/public$ n98-magerun.phar dev:con
Interactive shell

===========================
MAGENTO INTERACTIVE CONSOLE
===========================

Initialized Magento (1.13.0.2)

php > 
</pre>

**Comment by cmuench** [comment]
dev:console was replaced in 1.95.0.
