### ISSUE TITLE
system:run-setup-scripts: set version in core_resource table

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#22]
Implement an option --set modulecode=versionnumber to force a version number to be set before executiong applyAllUpdates. This can be helpfull to re-run setup scripts for debugging.

**Comment by pocallaghan** [comment]
The command `sys:setup:change-version` now exists does that fulfil the requirements of this ticket, or are we interested in adding a flag to `sys:setup:run` to trigger a version change before running the update? Might save people a few keystrokes?

**Comment by cmuench** [comment]
@pocallaghan You are right. We have this already with `sys:setup:change-version`.
