### ISSUE TITLE
Error ConsoleTerminateEvent on magerun commands

### ISSUE THREAD

**Issue by arosenhagen** [netz98/n98-magerun#221]
On current version 1.78.2 we get the following error on e.g. `n98-magerun.phar cache:clean`
Known stable version is 1.76.0 although we haven't tested the interim versions.

```
PHP Fatal error:  Class 'Symfony\Component\Console\Event\ConsoleTerminateEvent' not found in phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php on line 915
```

We call n98-magerun from within a chef run, which fails due to this error (exit code).

**Comment by alfechner** [comment]
Thanks so much @arosenhagen 

Had the same problem and resolved it by disabling `Aitoc` modules.

**Comment by jeroenvermeulen** [comment]
Thanks so much @arosenhagen
Had the same problem and resolved it by disabling Aitoc modules.
