### ISSUE TITLE
Problem with shebang?

### ISSUE THREAD

**Issue by joshribakoff** [netz98/n98-magerun#224]
I get a segfault unless I explicitly prefix the command with `php`

```
# n98-magerun.phar 
PHP Fatal error:  include(): Cannot redeclare class symfony\component\eventdispatcher\eventdispatcherinterface in phar:///usr/bin/n98-magerun.phar/vendor/composer/ClassLoader.php on line 185

Fatal error: include(): Cannot redeclare class symfony\component\eventdispatcher\eventdispatcherinterface in phar:///usr/bin/n98-magerun.phar/vendor/composer/ClassLoader.php on line 185
Segmentation fault
```

```
# php n98-magerun.phar 

     ___ ___
 _ _/ _ ( _ )___ _ __  __ _ __ _ ___ _ _ _  _ _ _
| ' \_, / _ \___| '  \/ _` / _` / -_) '_| || | ' \
|_||_/_/\___/   |_|_|_\__,_\__, \___|_|  \_,_|_||_|
                           |___/
n98-magerun version 1.78.3 by netz98 new media GmbH


```

**Comment by jay-saint** [comment]
I had this same problem on my shared hosting account with Nexcess.net.  To get most command line php to work I had to create an alias in my .bashrc file to set *apc.enable_cli* to off and to turn on *allow_url_open* php flags. extending this I created a new n98 alias that fixed this and saves me a few key strokes.

Example from my .bashrc file:
```
# User specific aliases and functions
alias php="php -d allow_url_fopen=On -d apc.enable_cli=Off"
alias n98="php /home/jibcrane/bin/n98-magerun.phar"
```

Then run the following command to reload .bashrc:
```
source ~/.bashrc
```

**Comment by ktomk** [comment]
@jay-saint: Thanks for sharing. Next to .bashrc adding an additional php.ini or replacing it altogether can help, too under certain (shared) environments: https://secure.php.net/manual/en/configuration.php#63096 - the PHPRC environment variable is often easy to configure for a generic set-up across multiple PHP based command-line tools.

**Comment by davidalger** [comment]
Our typical solution we came up with over here is to add the following to a file at `~/bin/mr`

    #!/usr/bin/env bash
    /usr/bin/env php -d apc.enable_cli=0 -d detect_unicode=Off -d disable_functions= ~/bin/n98-magerun.phar "$@"

Where the env doesn't require this, we install n98-magerun at `~/bin/mr` directly (our name of choice for the tool).

**Comment by davidalger** [comment]
I've wanted to try what was done to solve the APC issue on the composer project with this tool and see if it would ~~solve~~ workaround that "gotcha" for good: https://github.com/composer/composer/pull/3502 just haven't had the time yet :)

**Comment by tkn98** [comment]
@jay-saint: Can you still reproduce / provoke this and give the error message(s)? I'm asking because I'd like to find out if the issue is with a recent magerun version. If so the reference given by @davidalger  might be very useful. And if we patch it we knew who we could ask for a test ;)

**Comment by jay-saint** [comment]
@tkn98 yes I can still reproduce this problem.  I just need to to invoke n98-magerun.phar directly instead of through my alias.

I only recently began using n98.  I was actually able to run n98 without the work around when I had it initially installed directly in my magento directory.
I then moved it to my */home/user/bin* folder and created a *./n98-magerun* folder in order to install Fabrizio's https://github.com/AOEpeople/mpmd 
I then began experiencing the problem.  Perhaps this only encounters a problem with re-declaring the class when using an external module.

**Comment by tkn98** [comment]
@jay-saint If you still have the problem and can reproduce, I think we should introduce the changes @davidalger suggested into the development version and then you can give it a test and try. If you want to provide a PR for that fine, otherwise I can do it as well. Just let me know.
