### ISSUE TITLE
Check if developer IP restriction is set / allow reset of the option

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#23]
When enabling template hints or inline translation, the setting might not take effect because a developer IP restriction is set

* show warning
* add an option to reset the IP

**Comment by robbieaverill** [comment]
It's a shame that the `AbstractMagentoStoreConfigCommand` doesn't pass the input and output interfaces to the `_beforeSave()` and `_afterSave()` methods - if it did, implementing a warning and/or option to reset the IP would be added to the shell `TemplateHintsBlocksCommand` with relative ease.

**Comment by ktomk** [comment]
@robbieaverill: You can use the IO helper for that:

    $output = $this->getHelper('io')->getOutput();

**Comment by robbieaverill** [comment]
Great!

On Friday, 15 April 2016, Tom Klingenberg <notifications@github.com> wrote:

> @robbieaverill <https://github.com/robbieaverill>: You can use the IO
> helper for that:
>
> $output = $this->getHelper('io')->getOutput();
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/netz98/n98-magerun/issues/23#issuecomment-210293391>
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by ktomk** [comment]
Thanks to @robbieaverill this has been implemented.
