### ISSUE TITLE
Removing warning - Folder /tmp/magento/var found, but not used in n98-magerun

### ISSUE THREAD

**Issue by seansan** [netz98/n98-magerun#245]
Hi, we use several magerun commands in a shell script and see these warning for every command. Can we quiet that? (but do see other more specific warnings related to the command)

It's not recommended to run n98-magerun as root user

Folder /tmp/magento/var found, but not used in n98-magerun

This might cause serious problems. n98-magerun is using the configured var-folder /home/dev/domains/qdays.nl/public_html/var
Please refer to https://github.com/netz98/n98-magerun/wiki/File-system-permissions for more information.

**Comment by henkvalk** [comment]
I had it also. I run n98 as root. He's running n98-magerun as root. So the var directory is changing owner of var dir to root. Reset ownership.

chown -R user:group var

change above user and group at your own (dev:dev??)

**Comment by seansan** [comment]
We allow access for all users to magerun, so is there any chown command
other then "Access for all" that would make the warning go away?

So root uses it; user1, user2, all with their own (directadmin) environment

**Comment by cmuench** [comment]
Btw.... it's not a Magento specific problem. It occures on every environment where a cli script runs with a different user as (web) PHP.

See i.e. Symfony2 documentation about that:

http://symfony.com/doc/current/book/installation.html  -> Setting up Permissions

**Comment by henkvalk** [comment]
Use root user only for emergency issues, like updating your webserver for example.
When you use root as a normal user, you get problems like this. It´s also unsafe.
So use the userlogin login you setup for that specific website. 
before you using the good logins, you must reset ownership. That´s not possible in DirectAdmin anymore, because it is set to root. so only root can reset ownership.

cd /home
for i in `ls`; do { chown -R $i:$i $i; }; done;

**Comment by steverobbins** [comment]
> Btw.... it's not a Magento specific problem.

@cmuench If it's not a Magento/N98 specific problem then I don't think it's magerun's job to warn about it.

**Comment by cmuench** [comment]
@steverobbins I don't understand your point of view. It's possible to disable the warning by config. I think n98-magerun should warn a user for possible issues related to the Magento environment.
Files in /tmp folder can cause serious issues in a multi-system environment or cause side effects.

**Comment by tkn98** [comment]
> If it's not a Magento/N98 specific problem then I don't think it's magerun's job to warn about it.

Fair argument, however I think you stretch it a bit. How I understood @cmuench he just wanted to point out that it's not possible for Magerun to deal with root access properly. The warning given is a reminder on the [Principle of least privilege](http://en.wikipedia.org/wiki/Principle_of_least_privilege).

**Comment by danshumaker** [comment]
I agree with @tkn98 and @cmuench ,  please leave the warning in there.  As a newer magento user, I'm getting better and better at recognizing common problems, and while the /tmp/magento issue is usually issue #3 out of 2,000,000 that we have with magento, i definitely appreciate the reminder that things are not right.  Most of the time we are in such a hurry that without that warning we would accelerate right on past that initial setup step of fixing the logs and permissions.  And as an advanced magento user you should either have your system setup correctly or learn how to disable it.
