### ISSUE TITLE
mysql/mysqldump cli command charset

### ISSUE THREAD

**Issue by mklooss** [netz98/n98-magerun#258]
this method miss utf8 as default charset

```
--default-character-set=utf8
```

a workaround is to add .my.cnf to user dir

**Comment by bambamboole** [comment]
I have this problem right now on a df.eu managed server too. @mklooss do you have a solution for this?

**Comment by mklooss** [comment]
Just take a look at the documention of mysql/mariadb:
https://mariadb.com/kb/en/library/configuring-mariadb-with-mycnf/

you should set the default charset in the ~/.my.cnf file

**Comment by cmuench** [comment]
With MySQL 8 the people also want to have `utf8mb4`. We do not want to change the behavious in Magerun. This should be managed in the MySQL config for client. In the background we are using mysqldump which can be configured with defaults as well.
