### ISSUE TITLE
cache:clean specific multiple caches and error handling

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#28]
Implement

n98-magerun.phar cache:clean full_page,block_html

to clear multiple caches.

Currently I think also no error message is shown if invalid cache codes are supplied

Could apply to other commands to run them on multiple targets

**Comment by pocallaghan** [comment]
The `cache:clean` method seems to implement `InputArgument::IS_ARRAY` allowing for multiple arguments to be passed. I think this is therefore resolved.

**Comment by cmuench** [comment]
@pocallaghan Thanks for reporting. I close the ticket.
