### ISSUE TITLE
magento2 support 2.0.0.0-dev63

### ISSUE THREAD

**Issue by rlieser** [netz98/n98-magerun#298]
Magerun crashes when used in a fresh magento2 (dev63) installation:

ralf@ralf-vm:~/Workspace/magento2$ n98-magerun.phar --version
n98-magerun version 1.85.0 by netz98 new media GmbH
ralf@ralf-vm:~/Workspace/magento2$ n98-magerun.phar sys:check
PHP Fatal error:  Class 'Mage' not found in phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Application.php on line 634
PHP Stack trace:
PHP   1. {main}() /usr/bin/n98-magerun.phar:0
PHP   2. N98\Magento\Application->run() /usr/bin/n98-magerun.phar:8
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Application.php:533
PHP   4. N98\Magento\Application->doRun() phar:///usr/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:121
PHP   5. Symfony\Component\Console\Application->doRun() phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Application.php:487
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///usr/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:191
PHP   7. N98\Magento\Command\AbstractMagentoCommand->run() phar:///usr/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:888
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:371
PHP   9. N98\Magento\Command\System\CheckCommand->execute() phar:///usr/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
PHP  10. N98\Magento\Command\AbstractMagentoCommand->initMagento() phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Command/System/CheckCommand.php:52
PHP  11. N98\Magento\Application->initMagento() phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:168
PHP  12. N98\Magento\Application->_initMagento2() phar:///usr/bin/n98-magerun.phar/src/N98/Magento/Application.php:377

**Comment by caneraydinbey** [comment]
Anyslutions?

**Comment by tkn98** [comment]
@caneraydinbey: The solution I'd say is to use Magerun2 :) - But I was not aware that this still is an issue for someone. Can you share some more details what your issue is?

This issue was reported (Feb 2014) before branching out the Magerun 2 version (Nov 2014).
