### ISSUE TITLE
sys:setup:run on enterprise requires admin session. Possible?

### ISSUE THREAD

**Issue by ProxiBlue** [netz98/n98-magerun#315]
Using the sys:setup:run to upgrade from EE 1.11 to EE 1.12 (and later to EE 1.13)

During upgrade (1.11 to 1.12) I get this exception : 

PHP Fatal error:  Call to a member function getId() on a non-object in /home/lucas/workspace/sites/site-name-removed/app/code/core/Enterprise/Cms/Model/Observer.php on line 228
PHP Stack trace:
PHP   1. {main}() /home/lucas/workspace/n98-magerun/n98-magerun.phar:0
PHP   2. N98\Magento\Application->run() /home/lucas/workspace/n98-magerun/n98-magerun.phar:8
PHP   3. Symfony\Component\Console\Application->run() phar:///home/lucas/workspace/n98-magerun/n98-magerun.phar/src/N98/Magento/Application.php:513
PHP   4. N98\Magento\Application->doRun() phar:///home/lucas/workspace/n98-magerun/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:121
PHP   5. Symfony\Component\Console\Application->doRun() phar:///home/lucas/workspace/n98-magerun/n98-magerun.phar/src/N98/Magento/Application.php:467
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///home/lucas/workspace/n98-magerun/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:191
PHP   7. N98\Magento\Command\AbstractMagentoCommand->run() phar:///home/lucas/workspace/n98-magerun/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:904
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///home/lucas/workspace/n98-magerun/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:353
PHP   9. N98\Magento\Command\System\Setup\RunCommand->execute() phar:///home/lucas/workspace/n98-magerun/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:244
PHP  10. Mage_Core_Model_Resource_Setup::applyAllDataUpdates() phar:///home/lucas/workspace/n98-magerun/n98-magerun.phar/src/N98/Magento/Command/System/Setup/RunCommand.php:45
PHP  11. Mage_Core_Model_Resource_Setup->applyDataUpdates() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Core/Model/Resource/Setup.php:269
PHP  12. Mage_Core_Model_Resource_Setup->_upgradeData() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Core/Model/Resource/Setup.php:286
PHP  13. Mage_Core_Model_Resource_Setup->_modifyResourceDb() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Core/Model/Resource/Setup.php:407
PHP  14. include() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Core/Model/Resource/Setup.php:624
PHP  15. Mage_Core_Model_Abstract->save() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Cms/data/cms_setup/data-upgrade-1.6.0.0.0-1.6.0.0.1.php:258
PHP  16. Mage_Core_Model_Abstract->_afterSave() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Core/Model/Abstract.php:319
PHP  17. Mage::dispatchEvent() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Core/Model/Abstract.php:466
PHP  18. Mage_Core_Model_App->dispatchEvent() /home/lucas/workspace/sites/site-name-removed/app/Mage.php:447
PHP  19. Mage_Core_Model_App->_callObserverMethod() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Core/Model/App.php:1317
PHP  20. Enterprise_Cms_Model_Observer->cmsPageSaveAfter() /home/lucas/workspace/sites/site-name-removed/app/code/core/Mage/Core/Model/App.php:1338

Looking at the code where the exception is thrown:

Enterprise_Cms_Model_Observer::cmsPageSaveAfter

$version->setLabel($page->getTitle())
                ->setAccessLevel(Enterprise_Cms_Model_Page_Version::ACCESS_LEVEL_PUBLIC)
                ->setPageId($page->getId())
                ->setUserId(Mage::getSingleton('admin/session')->getUser()->getId())
                ->setInitialRevisionData($revisionInitialData)
                ->save();

thus the issue here is the call to Mage::getSingleton('admin/session')->getUser()->getId() 

Any way to fake the session?

**Comment by cmuench** [comment]
Should be fixed. Feel free to reopen the issue if you have this problem already in the latest release.
