### ISSUE TITLE
composer vendor autoloads

### ISSUE THREAD

**Issue by magicaner** [netz98/n98-magerun#340]
in case if there is vendors extensions under magento root it will be good to have them inlcuded to autolad process. 
can you add automatic include for {magento_root}/vendor/autoload.php please

**Comment by cmuench** [comment]
In the meantime we have support for this use-case.
There is a `\N98\Magento\Application\AutoloaderDecorator` in the Magerun core which tries to load a class from Magerun vendor folder. If that class is not loadable it tries as fallback to load with the Magento autoloader.

I close this issue. If this is still not helping in your case, please re-open the issue.
