### ISSUE TITLE
Run update scripts with cache clearing

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#35]
https://gist.github.com/2715268

**Comment by pocallaghan** [comment]
The `sys:setup:run` appears to call `cache:flush`, I'm assuming this ticket can be closed?

**Comment by kalenjordan** [comment]
Ah cool.  Ya I'm guessing it can probably be closed.

**Comment by redshark1802** [comment]
thanks for noticing

I'm closing this issue
