### ISSUE TITLE
db:dump --strip not seeing table prefixes

### ISSUE THREAD

**Issue by brentwpeterson** [netz98/n98-magerun#395]
-data export for: dataflow_batch_export dataflow_batch_import log_url log_url_info log_visitor log_visitor_info log_visitor_online report_compared_product_index report_event
Start dumping database ....
mysqldump: Couldn't find table: "dataflow_batch_export"

When I query the tables in the database I see the table

mgn_dataflow_batch_export

**Comment by cmuench** [comment]
No feedback. If problem exists alredy in 1.95.0 feel free to reopen the issue.
