### ISSUE TITLE
Add newsletter table group for db:dump command

### ISSUE THREAD

**Issue by mam08ixo** [netz98/n98-magerun#428]
When doing a stripped developer dump, I realized that all the newsletter subscribers are still present.

I suggest creating a table group *newsletter* that contains templates, queues, subscribers, and problem reports. This table group should then be [added to the *development* group via config.yml](https://github.com/netz98/n98-magerun/blob/4a7d9a07f467aa92c52eef7a815e07b06dcc808a/config.yaml#L321).

**Comment by cmuench** [comment]
Thanks for reporting. I added the settings to config.
