### ISSUE TITLE
config:dump produces invalid xml

### ISSUE THREAD

**Issue by astayart** [netz98/n98-magerun#441]
Hi, it appears that when using magerun to dump the full config xml, the output produced is not valid xml. In particular, any config.xml lines like: 

&lt;debug&gt;0&lt;/debug&gt;

appear to be getting processed by the Symfony\Component\Console\Output\OutputInterface, which produces invalid XML. I have a module that produces a dump for the system.xml which avoids this problem by adding the "OUTPUT_RAW" flag to the writeln call:
<pre>
&lt;?php

namespace AE\Config;

use N98\Magento\Command\AbstractMagentoCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SysdumpCommand extends AbstractMagentoCommand {
        protected function configure() {
                $this->setName('config:sysdump')->setDescription('Dump merged system config xml');
        }
        protected function execute(InputInterface $input, OutputInterface $output) {
                $this->detectMagento($output);
                if($this->initMagento()) {
                        $config = \Mage::getConfig()->loadModulesConfiguration('system.xml')->getNode();
                        $dom = new \DOMDocument();
                        $dom->preserveWhiteSpace = false;
                        $dom->formatOutput = true;
                        $dom->loadXML($config->asXml());
                        $output->writeln($dom->saveXML(), $output::OUTPUT_RAW);
                }
        }
}
</pre>

**Comment by cmuench** [comment]
Thanks. I added the parameter in config:dump command.
