### ISSUE TITLE
dev:console error

### ISSUE THREAD

**Issue by sonbui00** [netz98/n98-magerun#442]
$ n98-magerun.phar dev:console
$ Interactive mode enabled

PHP Notice:  Undefined index: init in phar:///~/bin/n98-magerun.phar/src/N98/Magento/Application.php on line 699
PHP Stack trace:
PHP   1. {main}() phar:///~/bin/n98-magerun.phar/res/dev/console_auto_prepend.php:0
PHP   2. N98\Magento\Application->initMagento() phar:///~/bin/n98-magerun.phar/res/dev/console_auto_prepend.php:5
PHP   3. N98\Magento\Application->_initMagento1() phar:///~/bin/n98-magerun.phar/src/N98/Magento/Application.php:391

Notice: Undefined index: init in phar:///~/bin/n98-magerun.phar/src/N98/Magento/Application.php on line 699

Call Stack:
    0.0097     897008   1. {main}() phar:///~/bin/n98-magerun.phar/res/dev/console_auto_prepend.php:0
    0.0419    3252912   2. N98\Magento\Application->initMagento() phar:///~/bin/n98-magerun.phar/res/dev/console_auto_prepend.php:5
    0.0419    3253008   3. N98\Magento\Application->_initMagento1() phar:///~/bin/n98-magerun.phar/src/N98/Magento/Application.php:391

**Comment by cmuench** [comment]
Next release 1.95.0 will replace the complete dev:console with Psy\Shell. This is a really awesome replacement. Stay tuned.

**Comment by cmuench** [comment]
Fixed

**Comment by zainengineer** [comment]
@cmuench 

If I checkout git repository it works but phar file triggers error, even after `self-update --unstable`
is it expected at this stage?

**Comment by cmuench** [comment]
@zainengineer Can you post the error messages?

**Comment by zainengineer** [comment]
may be some error in phar packaging

```
PHP Fatal error:  Cannot redeclare class Symfony\Component\Finder\Expression\Regex in phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/finder/Symfony/Component/Finder/Expression/Regex.php on line 17
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/n98-magerun.phar:0
PHP   2. N98\Magento\Application->run() /usr/local/bin/n98-magerun.phar:8
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:620
PHP   4. N98\Magento\Application->doRun() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:560
PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   7. N98\Magento\Command\AbstractMagentoCommand->run() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:882
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:428
PHP   9. N98\Magento\Command\Developer\ConsoleCommand->execute() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP  10. N98\Magento\Command\Developer\Console\Psy\Shell->__construct() phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/Developer/ConsoleCommand.php:62
PHP  11. Psy\Shell->__construct() phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/Developer/Console/Psy/Shell.php:12
PHP  12. Symfony\Component\Console\Application->__construct() phar:///usr/local/bin/n98-magerun.phar/vendor/psy/psysh/src/Psy/Shell.php:75
PHP  13. Psy\Shell->getDefaultCommands() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:91
PHP  14. Composer\Autoload\ClassLoader->loadClass() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP  15. Composer\Autoload\includeFile() phar:///usr/local/bin/n98-magerun.phar/vendor/composer/ClassLoader.php:301
PHP  16. include() phar:///usr/local/bin/n98-magerun.phar/vendor/composer/ClassLoader.php:412
```

**Comment by cmuench** [comment]
@zainengineer We had similar errors in the past. Most of them are related to APC or external autoloaders.
Please try this:

`php -d apc.enable_cli=0 n98-magerun.phar dev:console`

**Comment by zainengineer** [comment]
thanks it worked :)

php -d apc.enable_cli=0 /usr/local/bin/n98-magerun.phar dev:console
