### ISSUE TITLE
Per project configuration not in app/etc

### ISSUE THREAD

**Issue by maxbucknell** [netz98/n98-magerun#444]
From [Issue 38][1]:

> Simply create the file "app/etc/n98-magerun.yaml".

This is great, and I've read through the source on how this all works. But this causes problems for systems where the Magento installation is disposable, and custom config is still needed. Is there a way to add a custom yaml file to configuration, or am I stuck with having to symlink it?

[1]: https://github.com/netz98/n98-magerun/pull/38/files

**Comment by cmuench** [comment]
@maxbucknell We had had this feature request more than once. Currently it's not soooo easy to merge all the different config files. We have to support multiple environments (with composer, without composer, different htdoc folders).
We need a solution which does not break anything.

I think about two options:

* Possibly to specify an additional config by a new command line option
* If .n98-magerun file exists we check if there is an additional .n98-magerun.yaml file in the same folder and merge this config file.

**Comment by cmuench** [comment]
I added support for .n98-magerun.yaml config file (if file exists in the same folder as n98-magerun "stop file").

Example

```
.
├── composer.json
├── composer.lock
├── .n98-magerun    <-- Stop file with relative path to Magento root folder.
├── .n98-magerun.yaml   <-- Alternative project config file
├── vendor
└── www

```
