### ISSUE TITLE
Admin Password reset in 1.14.1

### ISSUE THREAD

**Issue by brentwpeterson** [netz98/n98-magerun#454]
When I reset the password for an Admin user in Magento 1.14.1 I can login but it then requires me to reset the password. It turns out to be an endless loop that we can not get out of.

**Comment by cmuench** [comment]
@brentwpeterson Currently i cannot see a problem in n98-magerun. Sounds like a config problem in your local installation. Can you check the command in a vanilla 1.14.1.?

**Comment by cmuench** [comment]
I closed this. If it always occure please re-open the issue.
