### ISSUE TITLE
List all EE-only-commands seperatly (in Readme)

### ISSUE THREAD

**Issue by joh-klein** [netz98/n98-magerun#468]
Could you maybe list all Enterprise-Edition-only commands separately? Would make it clearer, that i.e. gift cards are EE only (I know, who  doesn't know that?) :)

**Comment by sreichel** [comment]
I'd suggest to close b/c EE commands will be removed in v3.

**Comment by sreichel** [comment]
Thanks @joh-klein  :)

**Comment by sreichel** [comment]
There will be a README-update to reflect all changes.

**Comment by joh-klein** [comment]
> Thanks @joh-klein :)

Sure thing – this is a little blast from the past 😀
