### ISSUE TITLE
Installer option useDefaultConfigParams unclear

### ISSUE THREAD

**Issue by joh-klein** [netz98/n98-magerun#480]
The way I understand this option is: if I provide my own `n98-magerun.yaml` and inside of that add 

    installation:
      defaults:
        currency: EUR
        locale: en_US

and then set `useDefaultConfigParams=yes` it will use these and not the ones from the `config.yaml`, correct?

What happens if I only provide some values? Will the others come from the standard `config.yaml`? Will I get asked? And also: is there a way to provide all values (e.g. *currency*, *locale*) to the installer at runtime?

**Comment by cmuench** [comment]
All config values are merged in order. See https://github.com/netz98/n98-magerun/wiki/Config#config for more details.
It's possbile to override a single parameter. If `useDefaultConfigParams=yes` is used the install command will not prompt for any option. This is useful if you need an unattanded installation. If it is not set the installer prompts for any parameter and show you the defaults which can be used.

See also: https://github.com/netz98/n98-magerun/wiki/Magento-installer#overwrite-default-settings
