### ISSUE TITLE
Mage2 installation fails

### ISSUE THREAD

**Issue by Neologist** [netz98/n98-magerun#491]
At the moment it's not possible to install Magento2 with magerun. You'll end up with the following error:
````
Installation failed.Could not open input file: /var/www/magento2/install.php
````
So the tool is trying to call the "old" installation method via the install.php and not via setup/index.php

**Comment by cmuench** [comment]
Please use n98-magerun2 which is currently in development for Magento 2.

https://github.com/netz98/n98-magerun2
