### ISSUE TITLE
Exporting magento module

### ISSUE THREAD

**Issue by damirock** [netz98/n98-magerun#492]
Hi, i would like to know if it's possible to export module via magerun? I can see this custom module in admin > system > configuration > advanced > advanced

This module is custom and was not installed via magento connect

**Comment by cmuench** [comment]
Hi, this is currently not possible to automatically find all dependent files . An extension can place files in any part of the shop file structure.
There are solutions like "modman" which try to solve this issue. 
In Magento 2 it will be possible, because all module files exist in one single folder.

**Comment by steverobbins** [comment]
We can get some.  Easiest being:

* app/code/`codePool`/`namespace`/`name`/*
* app/etc/modules/`namespace`_`name`.xml

From the `config.xml` we could find the layouts it uses, but we would have to search through each theme (could be in `base/default`, `enterprise/default`, `rwd/default`, etc).  Then search for templates and skin files in the same manor.

What would be tricky is finding templates set in blocks, or skin files included in templates and css.

**Comment by cmuench** [comment]
@steverobbins That's not enough. A module can place files anywhere.
What's up with i.e. template files? Templates could be defined inside a block class and/or layout files.
What's up with skin files or a global js file?
It's not possible to guarantee a 100% complete module. So we should not implement this in n98-magerun core. A 3rd party plugin can do this as well.
