### ISSUE TITLE
dev:module:list does not show version of inactive modules

### ISSUE THREAD

**Issue by jhoelzl** [netz98/n98-magerun#495]
Hello,

why does the command dev:module:list does not show the version of inactive modules? It would be great to have this information as well for inactive modules.

**Comment by cmuench** [comment]
Currently we use the merged config. The merged config contains only the base config with i.e. the module name and the config.xml files of all activated modules. The version is embedded inside the config.xml files.
So we must parse the config.xml files manually if we want the version of the disabled modules.

**Comment by jhoelzl** [comment]
ok, thanks for reply!
