### ISSUE TITLE
External REPL for dev:console (Psysh)

### ISSUE THREAD

**Issue by barryvdh** [netz98/n98-magerun#499]
Hey all,

Have you considered using a full-featured REPL for your `dev:console` command?

Something like http://psysh.org/ should be easy to integrate and provides extra functionality, like more robust error handling, running command froms the console (default commands or magerun commands if you want) and custom presenters, to output variables in a 'pretty' way.

See for example how Laravel implemented it: https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/TinkerCommand.php

It should probably be compatible with your requirements (not tested).

If you're interested but don't have time, I could take a look if you want. Or would this be more fit as a custom package?

**Comment by cmuench** [comment]
You are to late :-) 
It's already committed in develop branch. We use psysh library.

**Comment by barryvdh** [comment]
Ah sorry, missed that. Will check it out! Thanks
