### ISSUE TITLE
no colored output when stdout is not a tty device

### ISSUE THREAD

**Issue by eschmid72** [netz98/n98-magerun#508]
When I type
```
    n98-magerun customer:list | less
```
or output to a file, I'll get this header:
```
+------+-----------------------------------------+----------------------+---------------------------+---------+
|ESC[32m id   ESC[39m|ESC[32m email                                   ESC[39m|ESC[32m firstname            ESC[39m|ESC[32m lastname                  ESC[39m|ESC[32m website ESC[39m|
+------+-----------------------------------------+----------------------+---------------------------+---------+
```
Well, this can be preventedy by checking if the output stream is a tty device or not, and if it's not, don't write escape sequences.

**Comment by tkn98** [comment]
Please use the  `-R` switch of less for `RAW-CONTROL-CHARS` which displays the colors (and only the colors, use `-r` for all control characters):

    n98-magerun customer:list | less -R

As an alternative do not output color codes with n98-magerun:

    n98-magerun --no-ansi customer:list | les

AFAIK it's not easily possible from within PHP to check for a tty device in a stable manner.
