### ISSUE TITLE
Module installation

### ISSUE THREAD

**Issue by dave0783** [netz98/n98-magerun#519]
I have been trying to install custom modules as suggested [here](https://github.com/netz98/n98-magerun/wiki/Modules).

According to the aforementioned wiki post, you can put the modules in the following places:

* /usr/local/share/n98-magerun/modules
* ~/.n98-magerun/modules
* MAGENTO_ROOT/lib/n98-magerun/modules
* %windir%\n98-magerun\modules (only Microsoft Windows)
* %userprofile%\n98-magerun\modules (only Microsoft Windows)

I have tried to place the module in every location mentioned, but magerun does not seem to recognize them.  Am i doing something wrong?

**Comment by cmuench** [comment]
Could be a permission problem. You can run the tool with debug options to check if modules are recognized. 

```
n98-magerun.phar -vvv
```

**Comment by dave0783** [comment]
i just removed the .phar file and reinstalled it an it now seems to be working...that was odd.  Sorry for the confusion
