### ISSUE TITLE
Remove n98-magerun.phar from repo to decrease size

### ISSUE THREAD

**Issue by steverobbins** [netz98/n98-magerun#520]
I don't think it's good to keep such a large binary file in the repository, especially since it changes with each release.  Git isn't very good at tracking these changes in an optimized way.

The size of the repository is now `31M`

```
$ du -sh .git
 31M    .git
```

In [my fork](https://github.com/steverobbins/n98-magerun) I've [removed](https://help.github.com/articles/remove-sensitive-data/) `n98-magerun.phar` from the commit history and the size is down to `7.2M`.

The `.phar` is almost `3M` now so this repository will keep growing by at least that much with each release.  Instead, create a hook for new releases that will build and host the file for download (e.g. at http://magerun.net/n98-magerun.phar).

Note that rewriting history to remove this file will screw a lot of people over, as they'll need to rebase their PRs and force merge master to the forks.  However, in the long run, I think this needs to happen at some point.

**Comment by tkn98** [comment]
Thanks for raising this issue and creating the report. It was just last week I discussed this with Christian as well.

The way you did is not possible for the existing repository, we can't break history here. Can you imagine a way to deal with this by keeping history?

**Comment by steverobbins** [comment]
I don't think there is another way.  To remove this file from the past you have to rewrite history, which means commit SHAs will be changed.  Better to get it over sooner than later.  Why can't you break history?

Also, [GitHub's LFS](https://git-lfs.github.com/) might be worth looking into once it comes out.

**Comment by tkn98** [comment]
I don't wanna sound ignorant, let's just pretend for one scenario we don't want to change history. I think it's possible to remove the file now but keeping the history. This would not stand in the way to comletely break history later on and on the other hand also allows to have the scenario when the file is not in the repository. 

There needs some way to deal with it in either way (with and w/o deleting history) so I think this issue should be right now about how to deal with the case when the file is not in the repository any longer.

**Comment by steverobbins** [comment]
That would just be

    git rm n98-magerun.phar

But you would still hold 24M of waste in the repo.

**Comment by tkn98** [comment]
You "just" suggested to "just" destroy a common installation venue. Not that you intended it, but for this topic it should be kept in mind that this is less a problem what can be done technically (e.g. which batch of commands to roll) but about consequences what users will face afterwards, how to shift from current to new without breaking etc..

As much as I want to understand how hurting the issue for you is as one user of magerun, it's also important to keep other users in mind, too.

**Comment by cmuench** [comment]
@steverobbins As @tkn98 wrote it's currently not possible to remove the phar file from repo.
There are several 3rd party (>100) integrations depending on the phar file.
Removing the phar file will i.e. brake the QA of several open source magento modules.
The tool is widely used in travis or jenkins jobs.

**Comment by steverobbins** [comment]
I think it's possible to phase it out.  You could start compiling the GitHub phar with a deprecated warning showing a message to use the new non-GitHub phar.  You could even do something clever, like make it a few line script that downloads from the new source and self updates.

I just worry that one day `git clone`ing this project will download 100M+ of data when the source is only ~10M.  For poor souls like me even 10M is a lot to ask of my internet connection :smile: 

---

I've since played with [GitHub LFS](https://git-lfs.github.com/) but more locally.  It looks like it would still keep the file in the repo at `./n98-magerun.phar` but it's only a 200K text file.  It does other magic to store the compiled version.  Though, I'm not sure if it will work for other users, depending on if they have the `git-lfs

**Comment by steverobbins** [comment]
@cmuench @tkn98 See my commit for a possible solution: https://github.com/steverobbins/n98-magerun/blob/f8bbb61571d1883dafeb6afa60f3c3e06fb26338/n98-magerun.phar

I used GitHub as the `$newPharSource` since it doesn't exist anywhere else, but this would be changed to `http://magerun.net/download/n98-magerun.phar` or what have you.

I didn't encounter any issues with this solution in testing.  I can `php n98-magerun.phar` the `0.5KB` file, it shows a notice, downloads the correct file, and self executes with the commands I'd given.

**Comment by cmuench** [comment]
@steverobbins First step is done. We now provide a special download page for phar files.
All phar files are nightly builds.
I created a new phar in master with version 1.96.1 which changes the URLs of self-update command. From now we can mark the download from github as deprecated.

For n98-magerun2 i removed the phar file from repository.

**Comment by steverobbins** [comment]
:+1: The download page looks great
