### ISSUE TITLE
db:info [setting] command does not work properly when --skip-root-check option is set

### ISSUE THREAD

**Issue by mswebdesign** [netz98/n98-magerun#521]
When --skip-root-check option is set and e.g. the command 'n98-magerun.phar --skip-root-check db:info host' is executed, the output is the same as if 'n98-magerun.phar --skip-root-check db:info' was called. So the 'host' parameter is not taken into account anymore when --skip-root-check is set.

**Comment by cmuench** [comment]
Confirmed.
