### ISSUE TITLE
Does the tools support Bitnami Magento installation?

### ISSUE THREAD

**Issue by yiukalun** [netz98/n98-magerun#525]
I've try to use the tools to check login issue, try to run the tools under

/{install_dir}
/{install_dir}/app/magento
/{install_dir}/app/magento/htdocs
/{install_dir}/app/magento/htdocs/app

Got the "no such file or directory" error

**Comment by tkn98** [comment]
Thank you for sharing *where* you've used the tool. Could you also share which command you've been exectued (*how*) and provide the whole output (from incl. the command to the next prompt).

**Comment by yiukalun** [comment]
I'm running the n98-magerun sys:check command in the directory provided.

I think the tools is working fine with the standard installation, but it's more simple to install via using the Bitnami Magento Stack. Really hope that the tools can support the Bitnami stack.

**Comment by tkn98** [comment]
Please run the following commands and copy & paste the whole input/out from your console:

1.     $ n98-magerun.phar  --version
2.     $ n98-magerun.phar -vvv --version

Please note: I'm not interested only in what you say that you think you were doing. I want the exact input and output data from your shell to compare that to what you reported so far.

I think we can only progress further with this if you provide the exact information asked for. Otherwise this error-report easily to becomes too broad.

**Comment by yiukalun** [comment]
I'm using  a Mac machine. The output as follows:

>:/Users/yiuivan>n98-magerun.phar --version
n98-magerun version 1.95.0 by netz98 new media GmbH
:/Users/yiuivan>n98-magerun.phar -vvv --version
Load dist config
Search for Magento in folder public
Search for Magento in folder /Users/yiuivan
Search for Magento in folder /Users
DEBUG
n98-magerun version 1.95.0 by netz98 new media GmbH

The BitNami installation base directory will default in Applications/magento-1.9.1.0-1

Should I change the installation base directory to /Users/yiuivan?

**Comment by tkn98** [comment]
Thank you for sharing the additional information. It looks like that you're using n98-magerun on the Windows platform. Support on Windows is limited. Just saying, you can't expect things to fully work and supported.

In any case you should run magerun within the BitNami Magento installation base directory if you have Magento already installed.

If you try to install magento with magerun and you're running windows it might be that it just doesn't work. In that case I personally recommend a source installation of magerun and debugging the application.

Feel free to post more information / feedback and please ask if you've got clarifiaction questions.

**Comment by cmuench** [comment]
@tkn98 He is a mac user.

**Comment by cmuench** [comment]
@yiukalun Can you run this command?

```
n98-magerun.phar --root-dir=Applications/magento-1.9.1.0-1 sys:check
```

**Comment by yiukalun** [comment]
Noop.

The command produce the following error.
[RuntimeException]                    
  Magento folder could not be detected  

I change directory to /Applications/magento-1.9.1.0-1/apps/magento

and issue the command `n98-magerun.phar sys:check`
the follow error display:

 [Zend_Db_Adapter_Exception]                       
  SQLSTATE[HY000] [2002] No such file or directory                                                      

  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by cmuench** [comment]
@yiukalun According to bitnami readme the Magento root folder is "htdocs".
https://bitnami.com/stack/magento/README.txt
Can you try this?

```
n98-magerun.phar --root-dir=Applications/magento-1.9.1.0-1/htdocs sys:check
```

It should also be possible to change in the directory and run n98-magerun directly from there.

**Comment by yiukalun** [comment]
I've try almost all directory under /Applications/magento-1.9.1.0-1

Same error occur

`[Zend_Db_Adapter_Exception]                       `
`  SQLSTATE[HY000] [2002] No such file or directory `

**Comment by cmuench** [comment]
@yiukalun This looks like a not correct configured database connection. Does your shop run correctly in the frontend?

**Comment by yiukalun** [comment]
Sure, it's running normally. Let me check how standalone magento store the DB connection information.

The Bitnami stack may move it somewhere else.
