### ISSUE TITLE
please support --routine

### ISSUE THREAD

**Issue by hgati** [netz98/n98-magerun#529]
```sh
$ magerun db:dump --only-command
$ Filename for SQL dump: [2015-04-21_113916_matrix.sql]
mysqldump --single-transaction --quick --socket='/var/run/mysqld/mysqld.sock' -u'root' -p'mypassword'
'matrix' | sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/' > '2015-04-21_113916_matrix.sql'
```
my magento use custom user-functions and custom triggers.
please support --routine statement.

http://www.ducea.com/2007/07/25/dumping-mysql-stored-procedures-functions-and-triggers/

**Comment by hostep** [comment]
Hi hgati

This option is already in there since version 1.81.0:
`magerun db:dump --add-routines --only-command`

**Comment by hgati** [comment]
ok, great~~~`
