### ISSUE TITLE
Unattended install fail when unable to access database, but still produce clean exit code.

### ISSUE THREAD

**Issue by louim** [netz98/n98-magerun#533]
Hello!

I'm currently automating magento install using Magerun and Ansible. When running unattended install with some wrong database params, I get an exception, with `installation failed`, but then the installer produce another command which exits cleanly. Ansible then thinks all went right, even when the installation did not complete.

```shell
vagrant@magentotest:/var/www$ magerun install --installSampleData=no --dbHost=localhost --installationFolder=/var/www/magento --magentoVersion=1.9.1.0 --dbUser=magento --dbPass=magento --dbName=magento_development --useDefaultConfigParams=yes --baseUrl=http://magentotest.dev/


  Magento Installation


  - Installing magento-ce-1.9.1.0 (1.9.1.0)
    Loading from cache

Created database magento_development
Start installation process.
/usr/bin/env php /var/www/magento/install.php --license_agreement_accepted 'yes' --locale 'de_DE' --timezone 'Europe/Berlin' --db_host 'localhost' --db_name 'magento_development' --db_user 'magento' --db_pass 'magento' --url 'http://magentotest.dev/' --use_rewrites 'yes' --use_secure 'no' --secure_base_url 'https://magentotest.dev/' --use_secure_admin 'no' --admin_username 'admin' --admin_lastname 'Doe' --admin_firstname 'John' --admin_email 'john.doe@example.com' --admin_password 'password123' --session_save 'files' --admin_frontname 'admin' --backend_frontname 'admin' --default_currency 'EUR' --skip_url_validation 'yes'



  [Exception]
  Installation failed.
  FAILED
  ERROR: Database connection error.



install [--magentoVersion[="..."]] [--magentoVersionByName[="..."]] [--installationFolder[="..."]] [--dbHost[="..."]] [--dbUser[="..."]] [--dbPass[="..."]] [--dbName[="..."]] [--dbPort[="..."]] [--installSampleData[="..."]] [--useDefaultConfigParams[="..."]] [--baseUrl[="..."]] [--replaceHtaccessFile[="..."]] [--noDownload] [--forceUseDb[="..."]]

```

If I check the exit code:
```
vagrant@magentotest:/var/www$ echo $?
0
```

Here is a screenshot of the text version :

![capture d ecran 2015-04-23 a 09 36 53](https://cloud.githubusercontent.com/assets/923718/7298445/a297833e-e99d-11e4-9ea5-10eb1c5f230e.png)

Question is: am I doing something wrong? I don't understand the install part example after the exception. Is it supposed to show there?

I'm using PHP 5.5.23:
```
PHP 5.5.23-1+deb.sury.org~trusty+2 (cli) (built: Mar 24 2015 10:58:52)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

And Magerun: `n98-magerun version 1.95.0 by netz98 new media GmbH`

**Comment by tkn98** [comment]
I tried to reproduce your issue but was unable to trigger the exact Exception you have there.

Do you know what I can do to provoke it? I tried with wrong username on the database as well with wrong hostname but this gives me a different exception only:

````
  [InvalidArgumentException]         
  Database configuration is invalid  
````

The exit code then is `1`, so it's not enough to reproduce your case. Any ideas?

**Comment by tkn98** [comment]
Thank you for the quick fix and looking into it  @redshark1802!

**Comment by tkn98** [comment]
@louim: A fix is now part of the development version. You can either wait for the next release or build the phar from devel branch sources.

**Comment by louim** [comment]
Thank you very much for the quick fix!
