### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by tkn98** [netz98/n98-magerun#536]
The travis-ci build is broken. I've seen this in #535

- occasionally: The command "php composer.phar install --dev --prefer-source" failed and exited with 1 during .
- and further when not broken down: php tests/check-coverage.php clover.xml ${COVERAGE} exists with status 1

The first problem *might* be related to network problems.

And is installing latest composer really necessary? travis-ci normally updates once in a month, e.g. current one is:

> Composer version 1.0-dev (ea037305499d300f3a534b36a62abcdd1ba3479d) 2015-04-24 10:08:11

**Comment by tkn98** [comment]
The first  occasionally problem might indeed just be a network issue.

But also the code-coverage is borderline to the 65% limit.

**Comment by steverobbins** [comment]
I'm noticing a lot of issues relating to mysql/creating the database.  These might be related to [reported issues with Travis-CI](https://github.com/travis-ci/travis-ci/issues/3781)

**Comment by redshark1802** [comment]
Hi @steverobbins thanks for noticing, we're looking into it.

**Comment by cmuench** [comment]
This was a temporary GitHub problem.
