### ISSUE TITLE
dev:console disappeared ?

### ISSUE THREAD

**Issue by edi9999** [netz98/n98-magerun#538]
Hi,

it seems that the `dev:console` command has disappeared.
However, it seems to be still there in the code: 

https://github.com/netz98/n98-magerun/blob/4d6e10111f69a05fadb12df7e16a286772825621/src/N98/Magento/Command/Developer/ConsoleCommand.php

Do you know what is the problem ?

I'm using the latest version of magerun (1.95)

**Comment by redshark1802** [comment]
Hi @edi9999,

I was not able to reproduce this issue.
Please redownload the phar and try again.

**Comment by pocallaghan** [comment]
Well this is an interesting one. I checked my local copy too and found the command isn't listed and indeed doesn't work. I tried `self-update`, but no updates found. So decided to try downloading a fresh copy...

```bash
pocallaghan-mbp:Downloads pocallaghan$ wget -q https://github.com/netz98/n98-magerun/raw/master/n98-magerun.phar
pocallaghan-mbp:Downloads pocallaghan$ php n98-magerun.phar | grep dev:console
 dev:console                      Opens PHP interactive shell with initialized Mage::app() (Experimental)
pocallaghan-mbp:Downloads pocallaghan$ mv n98-magerun.phar n98-magerun
pocallaghan-mbp:Downloads pocallaghan$ php ./n98-magerun | grep dev:console
pocallaghan-mbp:Downloads pocallaghan$ chmod +x ./n98-magerun
pocallaghan-mbp:Downloads pocallaghan$ ./n98-magerun | grep dev:console
pocallaghan-mbp:Downloads pocallaghan$
```

**Comment by edi9999** [comment]
Right, seems that removing the `.phar` extension magically removes that command.

Doesn't make any sense to me

**Comment by AydinHassan** [comment]
Makes perfect sense when you look at this line: https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Developer/ConsoleCommand.php#L38 :D

**Comment by edi9999** [comment]
It also seems that it is the only command that disappears:

➜ ./mg.phar | wc -l
151
➜  mv mg.phar mg && ./mg | wc -l
150

**Comment by edi9999** [comment]
The code was included to solve issue https://github.com/netz98/n98-magerun/issues/101, however I'm not sure that part that checks that the extension is `.phar` is necessary.

**Comment by redshark1802** [comment]
Hi @edi9999,

we switched to psy-shell and the file-extension check was removed in this commit https://github.com/netz98/n98-magerun/commit/c52623f308198b9b35cbe74252b407ce1878600c
The check was implemented because the old shell had a problem with the autoloader.

Please use the develop version or wait for the next release.
