### ISSUE TITLE
db:dump to xml format

### ISSUE THREAD

**Issue by davidmpaz** [netz98/n98-magerun#545]
An  improvement would be to have an option on db:dump to output on xml format. Or maybe allow to pass extra options to mysqldump from n98-magerun so we can add the --xml flag to command.

PHPUnit support xml format for database testing, it is a bit cumbersome to export tables group then import again just to have the xml in place.

**Comment by redshark1802** [comment]
Hi @davidmpaz ,

we've added the feature to the development branch.

**Comment by davidmpaz** [comment]
Cool! thank you guys.

**Comment by davidmpaz** [comment]
Hi, I would like to provide some feedback. 

1. When executing the dump I got a file with several xml/root node declarations. I don't think it is a duplicated dump since when the extra declaration appears, is to soon for being duplicated data.

Removing extra tags/document entity from file like: "<?xml ?>", "<mysqldump>" and "<database>" solve issue for DBUnit parser (simplexml_load_file). Please note that when executing mysqldump --xml tool directly issue is not present.

2. Also in my case found similar issues to [this](PCDATA invalid Char value 1). I havent look deeply to my xml but some error were solved with adding the extra --hex-blob flag.

So it is possible to add some feature for adding extra options like --hex-blob when using --xml? or equivalent. Like --extra="hex-blob", this way command line would be flexible enough to accept several flags to mysqldump tool.

Thanks in advance.

**Comment by redshark1802** [comment]
Hi @davidmpaz,

comparing a fresh dump from mysqldump and magerun have both the same nodes.
Could you provide an example-file?

I think passing extra-options directly to mysqldump would be great, but that requires some refactoring of the dumper, which is currently not a priority.

**Comment by davidmpaz** [comment]
Hi @redshark1802

Thanks for coming back. Could you try please to add `--strip` flag. On a magento CE v1.9 sample database  I'm doing like: 
`magerun db:dump --xml --strip="@development" dump.xml`
when I cat it: 
`cat dump.xml|grep "xml version=\"1.0\""` 
I get two xml declarations.

**Comment by redshark1802** [comment]
Hi @davidmpaz ,

thanks for the feedback, I was able to reproduce this issue.
The problem is in the ``--strip`` functionality of magerun: it internally calls mysqldump two times, therefore two xml-documents are created and returned.

As far as I can tell, this isn't a "easy" fix, omitting ``--strip`` would contain unwanted data but return a valid xml-file .

**Comment by davidmpaz** [comment]
Hi, @redshark1802,

No problem. In the mean time I can always remove the extra tags created by the double execution. 

Also please consider merging pull #553 to have the hex-blob flag functionality.

Thanks a lot.

**Comment by tkn98** [comment]
Some of the more mature tools support files that are infact a sequence of XML documents like the output would be here generated with --strip. I don't know if mysql can cope with it when importing data, in PHP a stream wrapper exists that can deal with it: [how to read the multiple xml contents in a file using php](http://stackoverflow.com/a/25233496/367456)  - What I want to say is, that despite this actually is not a valid XML document, you can still find the same principle in the world of XML based files.

**Comment by davidmpaz** [comment]
Hi @tkn98,

Thanks for the hint. I have took a look into it and I agree it would be better to address this outside magerun. I haven't found many references on mysql using the exported xml, [this](https://dev.mysql.com/doc/refman/5.5/en/load-xml.html) show some limited functionality. The wrapper solution looks very nice, to implement maybe on bdunit itself.

Unfortunately I need to dedicate time in other direction now, I will come over this later. 

Many thanks for the help and directions.

**Comment by davidmpaz** [comment]
Hi, allow me to come over this again to ask if it is possible to make the dumper to output export the XML documents in multiple files instead in a concatenated one? So, when --xml and --strip is used, we get one file per XML document.

Thanks in advance

**Comment by tkn98** [comment]
It's some time, could you give a short description / example what the output should be? I can imagine one file per table but if you could given an example with concrete names from which it becomes clear how the feature would look like that would be helpful.

**Comment by davidmpaz** [comment]
I was thinking in something more simple. A request to dump with 'strip' and 'xml' options, dumper will output two files instead one file. Something like this: 
`magerun db:dump --xml --strip=@development`
Will output two files, same naming convention with a suffix/prefix maybe? One for structure of stripped tables and other with rest of tables (data and structure), the same way as used in [dumper lines 232-256](https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Database/DumpCommand.php#L232) but executing command right after building it, not at the end, all at once.

**Comment by tkn98** [comment]
Hmm, that code segment is already pretty much stuck and misses proper command encoding. Adding another differentiation will put it at risk. Even though these lines of code are effectively to be changed, the exec operation(s) need to be factored out so that they can be easily build / extended. Already for the two cases given.

Also was quickly looking into [`--tab` option](http://dev.mysql.com/doc/refman/5.6/en/mysqldump.html#option_mysqldump_tab) but it's not applicable here. So it seems, this needs many *mysqldump* commands then.

For testing purposes one might want to add `--xmls` first to trigger the new feature and question is where to place files / how to specify dump directory/filenames. Interactive mode to ask for these seem hard.

**Comment by davidmpaz** [comment]
In my opinion `--xmls` is a good idea, it would flatten the options reducing complexity. Regards file names and directories I think that the current default behavior is fine. I would update it to add a suffix to the file with table structures (stripped tables). But no clue how much overload would cause to the dumper architecture or in development effort, it is just my user point of view talking.

**Comment by tkn98** [comment]
For the overload I'd say, let's try this out as it's hard to tell. Linux is very well with forking new threads, Windows is experimental only. We perhaps even skip the command on Windows  explicitly IIRC.

Suffix sounds like a sane idea. It perhaps should be with `.xml` extension anyways in that case. I don't remember from top of my head what the default naming is, I think it's with a timestamp in the filename, so all the files should have the *same* timestamp.

**Comment by davidmpaz** [comment]
Closing this since its been quite long since created and main purpose is implemented already.

Thanks guys for the support.
