### ISSUE TITLE
Feature Request - add ability to turn static blocks on / off

### ISSUE THREAD

**Issue by carylewis** [netz98/n98-magerun#556]
It would be very useful to be able to turn static blocks on and off similar to how your cms:banner:toggle command works.

**Comment by tkn98** [comment]
The feature you requested has been merged into the development version of magerun.

Please fetch the latest development version or wait until the next release.

Fetching the development version would help to get direct feedback from you who requested the feature directly and within short time. Please let us know if you need assistance obtaining the development version.
