### ISSUE TITLE
The "-1" option does not exist.

### ISSUE THREAD

**Issue by infabo** [netz98/n98-magerun#560]
It is not possible to set negative values with config:set

```n98-magerun.phar config:set myextension/setting/key "-1"```

or

```n98-magerun.phar config:set myextension/setting/key "-15"```

**Comment by steverobbins** [comment]
Not not sure if this is a limitation of Symfony Console or Bash, but you can work around this with `--`:

    n98-magerun.phar -- config:set myextension/setting/key -1

> Unless otherwise noted, each builtin command documented in this section as accepting options preceded by - accepts -- to signify the end of the options.

http://unix.stackexchange.com/q/11376/32055

**Comment by tkn98** [comment]
Can confirm the workaround with "--". Looks like this is a problem in the command-line parser from symfony. Maybe there is some information available upstream?

**Comment by redshark1802** [comment]
This is a known Issue: https://github.com/symfony/symfony/issues/5545
The workaround for this, as described above, is to use ```--``` which disables option parsing.
