### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by chrom** [netz98/n98-magerun#562]
when i install magento have error

Enter installation folder: [./magento]
  - Installing mageplus-master (dev-master master)
    Cloning master

Please enter the database host [localhost]: /var/run/mysql/mysql.sock
Please enter the database username [root]: root
Please enter the database password []: root
Please enter the database name [magento]: magerun
Please enter the database port  [3306]: 
Please enter the table prefix []:
PHP Warning:  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in phar:///usr/local/bin/magerun/src/N98/Magento/Command/Installer/InstallCommand.php on line 381
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

maybe not supported unix socket?

**Comment by pocallaghan** [comment]
Does it work if you use the default host value of localhost?

**Comment by redshark1802** [comment]
From the mysqli_connect documentation (https://php.net/manual/de/mysqli.construct.php):
host
```Can be either a host name or an IP address. Passing the NULL value or the string "localhost" to this parameter, the local host is assumed. When possible, pipes will be used instead of the TCP/IP protocol. ```

When you use ```localhost``` PHP will check if the configured socket exists and default to that.
You can check your socket configuration with ```php -r "phpinfo();" | grep mysqli.default_socket```

**Comment by tkn98** [comment]
@chrom: A host(name) normally is not a socket. The PDO error shows that PDO tries to resolve "` /var/run/mysql/mysql.sock`" as a hostname. This fails (because it's an invalid hostname and/or the hostname does not exists in your network). Try with just "`localhost`" as others have commented, it should use that socket behind the scenes.

Please comment back if the information helped you or you still have an issue.

**Comment by chrom** [comment]
))
OK, but how can i use socket?

**Comment by pocallaghan** [comment]
Using "localhost" *does* use the socket.

**Comment by tkn98** [comment]
@chrom:

> Try with just "localhost" as others have commented, it should use that socket behind the scenes.
