### ISSUE TITLE
Magento Version

### ISSUE THREAD

**Issue by Schrank** [netz98/n98-magerun#564]
I'm patching a lot of magentos at the moment and it would be super helpful to have a command to just get the magento version. I expected magerun already has this built in but can't find it :)

**Comment by Schrank** [comment]
I think sys:info does what I want ... if it wouldn't be in a VM :-( dammit.

    [Zend_Db_Adapter_Exception]
     SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (61)

**Comment by davidalger** [comment]
@Schrank might be able to get by with this in the meantime:

    php -r 'require "app/Mage.php"; echo Mage::getVersion()."\n";'

**Comment by tkn98** [comment]
The `--version` switch could trigger additional display of:

- the magento project directory Magerun did detect 
- plus the magento version (static) without database interaction

so it's magerun version x.y operating in directory/z/a containing magento version b.c in directory/www.

in case any of these can't be found, the information should be displayed as *unknown*.

How about that idea?

**Comment by Schrank** [comment]
I like the idea, unfortunately it doesn't solve my problem: Getting the Magento version without a database :-)

**Comment by pocallaghan** [comment]
@Schrank you could try [magescan](https://github.com/steverobbins/magescan), which I think may now be usable as a plugin for n98-magerun.

**Comment by davidalger** [comment]
Just submitted a PR which I believe accomplishes what's needed here by adding a separate sys:version command which only spits out the version info, without fully initializing the application. Fingers crossed to make sure none of the unit tests fail after I did this. :)

**Comment by Schrank** [comment]
Thanks, I like this.

**Comment by cmuench** [comment]
@davidalger We don't need a sys:version command. There is already a sys:info command which prints detailed infos about the installed shop.
An enhancement could be to print only the version with a second argument. The db:info command supports this already.

With the enhancement we could print the version with:

`n98-magerun.phar sys:info version`

**Comment by tkn98** [comment]
@cmuench: Does sys:info show the Magento version when the database connection is not working / not configured?

**Comment by redshark1802** [comment]
This is the output I get when no ```local.xml``` exists:
```
dbModel read resource does not implement Zend_Db_Adapter_Abstract
1.14.1.0
```

**Comment by davidalger** [comment]
@cmuench The problem with the existing sys:info command is that if a db connection cannot be made it spits out a Zend_Db_Adapter_Exception, and if the application is not installed at all, a slightly different error message.

So we need the support I implemented to load Magento without initing it completely. I like your suggestion of `sys:info version` to get only that specific piece of info. Would it be acceptable to case this so if the specified `key` is `version` it will use the soft initialization mode allowing one to get the version on an install with no db connection?

**Comment by davidalger** [comment]
@cmuench Pushed up some code to a branch to demonstrate what I'm suggesting. I'll submit a PR for it if you think this is ok.

**Comment by tkn98** [comment]
I'm fine with the softinit parameter. @cmuench can you take care about this one here?

**Comment by cmuench** [comment]
@tkn98 Looks good

**Comment by tkn98** [comment]
As this is merged, it's possible to close this. If you, @davidalger could give feedback would be nice to see that things worked out as intended.

**Comment by davidalger** [comment]
@tkn98 I think it turned out ok. I'd be more curious to hear from @Schrank since he's the one who originally needed what I jumped on implementing. It should come in fairly handy once it hits a release build.

**Comment by Schrank** [comment]
I would love to test, but I'm too dumb for it :) I checked out the master branch, built it and tried. Of course it failed, because it is only develop, then I checked out develop and built it, but the same for me

```
-> % n98-magerun.phar sys:version
  [InvalidArgumentException]
  Command "sys:version" is not defined.
[...]
```

What I'm doing wrong?

**Comment by Schrank** [comment]
-> % n98-magerun.phar --version
n98-magerun version 1.97.0 by netz98 new media GmbH

If this helps maybe?

**Comment by Schrank** [comment]
> n98-magerun.phar sys:info version

works :) Thanks for implementing, makes me totally happy.

**Comment by ktomk** [comment]
@Schrank: Great to see this is working for you! Thanks again @davidalger for the support and care-taking!
