### ISSUE TITLE
How to run the extension on Windows?

### ISSUE THREAD

**Issue by mluzan** [netz98/n98-magerun#565]
We have installed your extension n98-magerun. However, when we tried to run it on Windows, it hasn't worked. Are there any condition we should meet to make it work?

**Comment by redshark1802** [comment]
Hi, 

could you please provide more information:
What Windows version are you using?
What error message do you get?
What php-version do you use?

Or anything that helps us to reproduce this issue.

**Comment by mluzan** [comment]
We have installed the extension according to the instructions on this page http://magerun.net/magerun-addons-by-peter-jaap-blaakmeer/ 
on Windows 7

php-version 5.6 has been used

Error message you can see if you follow this link http://screencast.com/t/cbLXqjL9QR2

And thank you for taking your time!

**Comment by redshark1802** [comment]
Could you please provide the path where you put the extension, it should be located in your home directory.

Please run the following commands in your terminal and give me the output
```
php -r "echo getenv('USERPROFILE');"
php -r "echo getenv('HOME');"
php -r "echo getenv('HOMEPATH');"
```

**Comment by mluzan** [comment]
So, I followed your instructions. The result http://screencast.com/t/JYekumTENc
It's here in my computer http://screencast.com/t/a9XnwIw1p and then http://screencast.com/t/bzJtt58B

**Comment by redshark1802** [comment]
Please try __copying__ your ```.n98-magerun``` folder to ```n98-magerun```

**Comment by mluzan** [comment]
Thank you for your help and guidance! We have succeeded.

**Comment by redshark1802** [comment]
I'm glad I could help.

mageruns global foldername is inconsistent.
the folder should be named ```.n98-magerun``` on all platforms

**Comment by tkn98** [comment]
+1: Folder should be named `.n98-magerun` on all platforms, Windows has no problems with dots in filenames, it's a valid filename. Good opportunity to remove conditional code.

**Comment by redshark1802** [comment]
Hi @mluzan,

I've created a pullrequest to fix this issue.
Could you please rename your local ```n98-magerun```folder, checkout https://github.com/netz98/n98-magerun/pull/568 and run magerun with ```[path to git repo]/vendor/n98/magerun/bin/n98-magerun```  to test if it works.

**Comment by tkn98** [comment]
I also try to test this PR on windows later.

**Comment by tkn98** [comment]
We believe this flaw is fixed in the current stable version of magerun.
