### ISSUE TITLE
Error: command n98:doc:generate

### ISSUE THREAD

**Issue by chrom** [netz98/n98-magerun#570]
Log:

# n98:doc:generate
                                                          
  [InvalidArgumentException]                                 
  There are no commands defined in the "n98:doc" namespace.

**Comment by cmuench** [comment]
@chrom Can you give me more infomations about the exception?

**Comment by chrom** [comment]
I would like to but it is what gives the console.

my OS 
Linux linux-otsr 3.16.7-21-desktop #1 SMP PREEMPT Tue Apr 14 07:11:37 UTC 2015 (93c1539) x86_64 x86_64 x86_64 GNU/Linux

What i can help you?

**Comment by cmuench** [comment]
Did you use a current phar file from http://files.magerun.net/ ?

**Comment by chrom** [comment]
i get them 
curl -sS http://files.magerun.net/n98-magerun-latest.phar -o n98-magerun.phar

**Comment by cmuench** [comment]
@chrom Strange. I cannot find anything in the current file. Can you please re-download the phar file from files.magerun.net and print me the result of `php n98-magerun.phar -vvv` ?

**Comment by hostep** [comment]
I think there is some misunderstanding here, I think @chrom is trying to execute `php n98-magerun.phar n98:doc:generate` but this fails as that command doesn't exist.
I believe he found the command on the wiki: https://github.com/netz98/n98-magerun/wiki/Command-Reference
So I think the solution is to remove the commands from the wiki which aren't supported anylonger?

**Comment by tkn98** [comment]
@chrom: The error message is correct, there aren't any such commands in that namespace.

**Comment by cmuench** [comment]
@chrom @hostep @tkn98 I removed the command reference from wiki. This commands are not available in open source version n98-magerun.

**Comment by chrom** [comment]
Snx

**Comment by hostep** [comment]
@cmuench: I think you forgot to remove some references further down the page ;)

https://github.com/netz98/n98-magerun/wiki/Command-Reference#n98dbtruncate-tables
https://github.com/netz98/n98-magerun/wiki/Command-Reference#n98docgenerate
https://github.com/netz98/n98-magerun/wiki/Command-Reference#n98qacheck-documentation

**Comment by cmuench** [comment]
@hostep :+1:
