### ISSUE TITLE
ZSH completion not working on OS X

### ISSUE THREAD

**Issue by joeyhoer** [netz98/n98-magerun#589]
zsh completion, and I assume bash completion as well, fails on OS X due to the flavor of regex being used. The use of the `\s` shorthand character class in `sed` is only available on some systems as it's a GNU extension.

```
n98-magerun.phar --raw --no-ansi list | sed "s/\s.*//g"
```

should be updated to:

```
n98-magerun.phar --raw --no-ansi list | sed "s/[[:space:]].*//g"
```

to make the script more portable. This should work in all flavors of `sed`.

Additionally, I'd like to suggest that the zsh completion directory be renamed from `oh-my-zsh` to simply `zsh`, as there appear to be no `oh-my-zsh` dependancies, and everyone using `zsh` could benefit from the autocompletion.

**Comment by tkn98** [comment]
:+1: for portability and also the renaming.

**Comment by joeyhoer** [comment]
Everything should be in order.
