### ISSUE TITLE
n98-magerun.phar dev:module:create --add-all does not create setup scripts

### ISSUE THREAD

**Issue by luemic** [netz98/n98-magerun#593]
Hi guys,

after running the `n98-magerun.phar dev:module:create --add-all` there are no setup folders are created for the module. Is it intended behavior or a bug?

**Comment by AydinHassan** [comment]
https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Developer/Module/CreateCommand.php#L81-L85

Looks like `add-setup` was added after `add-all` was. It was probably just missed :)

**Comment by tkn98** [comment]
@luemic: Thanks for reporting. Can you make this as a pull-request (or do I have overlooked that you made one already?).

**Comment by luemic** [comment]
@tkn98 it's already merged into develop branch :)

**Comment by tkn98** [comment]
Could you give it a try if it solved your issue?

You should be able to install the development version by updating to it:

    $ n98-magerun.phar self-update --unstable

I'll close this ticket for now, if it didn't yet resolve, please just re-open and we take a further look.
