### ISSUE TITLE
n98-magerun in jailkit ubuntu

### ISSUE THREAD

**Issue by mwh03** [netz98/n98-magerun#597]
hello,

how install/share n98-magerun in a jailkit env.... ubuntu.
when i run n98-magerun i get no output.... , no errors also

xxxxxx:~$ n98-magerun
xxxxxx:~$

where i can find any debug of this? if i run it as root it will work i will get output

greetz

**Comment by tkn98** [comment]
Please try `$ n98-magerun -vvv --version`. also please provide the exit code of the command.

The [general suggestion of jailkit](http://olivier.sessink.nl/jailkit/jailkit.8.html) applies, too:

> Check your logfiles if things don't work as expected.

Any of these should provide more information.

**Comment by ktomk** [comment]
Closed because there was no further feedback on the issue.
