### ISSUE TITLE
Generate product thumbnail

### ISSUE THREAD

**Issue by ihsanberahim** [netz98/n98-magerun#607]
I need this feature. I posted my php script at

http://community.magento.com/t5/Programming-Questions/Generate-Thumbnail-Programmatically/td-p/9750

**Comment by fbrnc** [comment]
Hi @ihsanberahim,

this project is open source. Feel free to create a pull request and there's a chance that it's going to be merged. If not you can always create a custom plugin for n98-magerun. Find some information here:
https://github.com/netz98/n98-magerun/wiki/Add-custom-commands

Have a great day,
Fabrizio

**Comment by ihsanberahim** [comment]
Cool. Thanks.
