### ISSUE TITLE
Customer Delete Error in OSX 10

### ISSUE THREAD

**Issue by rafaelstz** [netz98/n98-magerun#608]
```
n98 customer:delete
```
Show this errors

    Fatal error: Call to undefined method Symfony\Component\Console\Helper\DialogHelper::getQuestion() in n98-magerun.phar/src/N98/Magento/Command/Customer/DeleteCommand.php on line 86

**Comment by tkn98** [comment]
Hi @rafaelstz, thanks for reporting this error. We're tracking this as an issue already in #563 and another related issue is #581. Your issue has been cross-referenced and I'll close it as it is a duplicate. Feel free to continue at #563 or if you think this is wrong, just re-open the issue here.
