### ISSUE TITLE
Magento 1.9.2.0 is out

### ISSUE THREAD

**Issue by joeyhoer** [netz98/n98-magerun#609]
Magento CE 1.9.2.0 has been released, and should be added to the installer, though it does not appear that the usual URL scheme is working any longer (for the 1.9.2.0 release).

http://www.magentocommerce.com/downloads/assets/1.9.2.0/magento-1.9.2.0.tar.gz results in a 404 error.

**Comment by ktomk** [comment]
Thanks for reporting, and yes, right now Magento is only providing downloads protected by cookie which is provided after login. Until there is a public download URL, please see [Add own magento repositories](https://github.com/netz98/n98-magerun/wiki/Magento-installer#add-own-magento-repositories).

Hopefuly this changes soon.

The currently given file behind Cookie-Login is:

- File: `magento-1.9.2.0.tar-2015-07-07-08-55-45.gz`
- MD5: `b9610a2e0982dd4e5a5edc118a05b9af`
- SHA1: `5a1a7ea0bdaaa8e14cd96fc8158a3227b631d45d `

**Comment by tkn98** [comment]
The currently given file behind Cookie-Login is:

File: `magento-1.9.2.0.tar-2015-07-08-02-50-14.gz`
MD5: `19435a588ddd5d4999761223648644e6`
SHA1: `5e15742b4d995d3cbfbaee7caa95e45dc954f2c8`

So we see unversioned revisions.

**Comment by davidalger** [comment]
@tkn98 My first thought was, I wonder if the updated 6285 patch had anything to do with it, but it doesn't appear to be the case. First thing we do after a new release drops is stash it in our internal releases location, renaming the file to match an internal pattern for all releases. So I've got both copies to compare with each other.

The hashes below match the two different hashes you got, followed by a diff --stat which shows where the changes are. Running an actual diff shows they are *formatting* and *copyright header* fixes! 

    dalger:01:48 PM:~$ md5sum /Users/dalger/Dropbox\ \(Classy\ Llama\)/CLS_Dev/releases/community-1.9.2.0.tgz
    b9610a2e0982dd4e5a5edc118a05b9af  /Users/dalger/Dropbox (Classy Llama)/CLS_Dev/releases/community-1.9.2.0.tgz
    dalger:01:48 PM:~$ md5sum /Users/dalger/Downloads/magento-1.9.2.0.tar-2015-07-08-02-50-14.gz
    19435a588ddd5d4999761223648644e6  /Users/dalger/Downloads/magento-1.9.2.0.tar-2015-07-08-02-50-14.gz
    dalger:01:48 PM:~$ mkdir 1.9.2.0.a 1.9.2.0.b
    dalger:01:49 PM:~$ tar -xzf /Users/dalger/Dropbox\ \(Classy\ Llama\)/CLS_Dev/releases/community-1.9.2.0.tgz --strip-components 1 -C 1.9.2.0.a
    dalger:01:49 PM:~$ tar -xzf /Users/dalger/Downloads/magento-1.9.2.0.tar-2015-07-08-02-50-14.gz --strip-components 1 -C 1.9.2.0.b
    dalger:01:49 PM:~$ git diff --stat 1.9.2.0.a 1.9.2.0.b
     .../skin/frontend/rwd/default/css/styles.css       |    1 -
     .../elevatezoom/jquery.elevateZoom-3.0.8.min.js    |   26 +-
     .../js/lib/elevatezoom/jquery.elevatezoom.js       | 3190 ++++++++++----------
     .../skin/frontend/rwd/default/js/lib/enquire.js    |   26 +-
     .../skin/frontend/rwd/default/js/lib/fastclick.js  |   26 +-
     .../frontend/rwd/default/js/lib/imagesloaded.js    |   26 +-
     .../rwd/default/js/lib/jquery.cycle2.min.js        |   26 +-
     .../rwd/default/js/lib/jquery.cycle2.swipe.min.js  |   26 +-
     .../rwd/default/js/lib/matchMedia.addListener.js   |   24 -
     .../skin/frontend/rwd/default/js/lib/matchMedia.js |   24 -
     .../rwd/default/js/lib/modernizr.custom.min.js     |   26 +-
     .../frontend/rwd/default/js/lib/selectivizr.js     |   26 +-
     .../Interface_Frontend_Rwd_Default-1.9.2.0.xml     |    6 +-
     13 files changed, 1594 insertions(+), 1859 deletions(-)
    dalger:01:49 PM:~$ 

So it essentially got released with the Magento doc block at the top of some js files and indentation that wasn't up to snuff, and then got silently repackaged and uploaded to the downloads server. Crazy.

I wonder if @benmarks might like to chime in here…

**Comment by ktomk** [comment]
@LeeSaferite: Could you for what you comitted as 1.9.2.0 into OpenMage (https://github.com/OpenMage/magento-mirror/commit/cb52550f2aa31026dfa9cb95709c567ebe3fded7) say which of the (at least two) Magento 1.9.2.0 versions you did commit? Would be good to know (and perhaps if you update it, it might also solve a problem we had in #614). Would be great to know/see.
