### ISSUE TITLE
install from a Magento core zip file located on local drive instead of downloaded?

### ISSUE THREAD

**Issue by gavinengel** [netz98/n98-magerun#615]
I have a handful of Magento sites on different servers that I want to use magerun install with.  I'd love to be able to use the latest Magento CE 1.9.2 even though this is currently being worked on: https://github.com/netz98/n98-magerun/issues/609

If I can download the Magento CE 1.9.2 zip file from magento.com and manually pop it onto my server's drive, can I have magerun use this as the install source instead of trying to contact magento.com?  Perhaps a command like this?:

$ magerun install --local=/tmp/magento-1.9.2.0.tar-2015-07-08-02-50-14.gz

**Comment by tkn98** [comment]
You can already unzip / untar yourself and use the *noDownload* and the *installationFolder* option to not download the package *and* specifiy the installation folder into which you've extracted the package.

Next to that what you suggest would allow to pass a package-file from a local source, which seems more practicable. It should also allow to test packages more easily.

There might be some room to integrate it with the changes required in #609 .

**Comment by tkn98** [comment]
@gavinengel: Apart from what I just commented, have you tried to add your own packages (please see [*Add own magento repositories*](https://github.com/netz98/n98-magerun/wiki/Magento-installer#add-own-magento-repositories))? Magerun uses composer under the hood, it should support `file:///` "downloads" from localhost. And IIRC it also supports pure POSIX and Windows pathnames.

**Comment by gavinengel** [comment]
Great options, thank you.  The custom Magento repository is the solution I prefer.
