### ISSUE TITLE
db:dump --exclude

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#616]
Add a new switch to exclude tables from the dump.
Different to `--stripped`, the tables would not be included at all, also no drop.
The table specification should be the same as in stripped.

**Comment by amenk** [comment]
I accidentally pushed this directly to `develop`. You might want to remove my push rights :)

**Comment by ktomk** [comment]
That not :) But please if you push: First fixes, then new features - even if we find the bugs while we write a new feature.  Thanks ;)

**Comment by ktomk** [comment]
Thank you for your contribution! Download the unstable version to profit from this new feature or wait until the next stable release.
