### ISSUE TITLE
PHP Fatal error: Allowed memory size - Is this an Issue?

### ISSUE THREAD

**Issue by SunshineTech** [netz98/n98-magerun#617]
When I install magento 1.9.2.0 using n98-magerun, there is the following error:

- Installing sample-data-1.9.1.0 (1.9.1.0)
    Downloading: 55%PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 250085376 bytes) in phar:///usr/local/bin/n98-magerun.phar/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 174

How much memory downloading sample data need?

**Comment by SunshineTech** [comment]
- Installing sample-data-1.9.1.0 (1.9.1.0)
    Downloading: 100%         
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 438581479 bytes) in phar:///usr/local/bin/n98-magerun.phar/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 247

**Comment by ktomk** [comment]
>  How much memory downloading sample data need?

For the 1.9.x Sample Data you need ca. 1024M  of memory.

This issue has been earlier discussed in #365, see especially [this comment about running magerun with more memory](https://github.com/netz98/n98-magerun/issues/365#issuecomment-96842652)  which suggest to raise the memory limit on call:

    $ php -dmemory_limit=1024M -f /path/to/n98-magerung.phar -- install

Alternatively you can raise the memory limit in your php.ini file for PHP cli. Please provide feedback if the information was helpful and if you were able to resolve the issue.

**Comment by SunshineTech** [comment]
I am sorry. But I can't try it, because my vps only 1024M memory.

**Comment by ktomk** [comment]
@SunshineTech: There are alternative data-dumps that are smaller in size for 1.9. These could be an option in your case then.
