### ISSUE TITLE
cache:disable does not validate code

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#620]
n98-magerun.phar ca:disable foobar

prints

`Cache foobar disabled`

Even such a cache is not existing.

Same for `cache:enable`

**Comment by tkn98** [comment]
The commands `cache:enable`, `cache:disable` and `cache:clean` have been updated in the development version to report invalid cache codes/types.

The exit status is 1 in such a case.

Please try the development version and provide feedback if it solved your issue.

**Comment by amenk** [comment]
seems to work
