### ISSUE TITLE
Dry run mode?

### ISSUE THREAD

**Issue by pquerner** [netz98/n98-magerun#623]
Hey,

when debugging a command do we have to have a "real" magento somewhere or is there something like a dry-run command/switch?

**Comment by tkn98** [comment]
You have the real Magento. I've not seen a single dry-run in Magento, only know it from git and it's somewhat nice for some operations.

**Comment by pquerner** [comment]
I do not mean a magento dryrun mode but a dryrun mode for magerun.
eg. when trying to create an admin user with flag --dry-run it just "shows" what could be done, its not actually doing anything.

**Comment by tkn98** [comment]
My fault, I was meaning Magerun not Magento. For commandline usage, I know it from git, it checks if all parameters are correct and starts to do things, so merely checks pre-conditions. Just no changes. Correct my last comment to that.

**Comment by cmuench** [comment]
@pquerner What's the use case for that? Why should we only simulate admin user creation?

**Comment by pquerner** [comment]
@cmuench I meant "for example when creating a admin user".

Use case: to easier debugging certain cmd actions. "On the go", without a magento somewhere
Could be used for testing aswell.

For example (was rejected; but I'll use it as an example anyway)
create admin user from cmd where you have to enter your password twice
The test would run this command in ```--dry-run``` mode with parameters
a) correct passwords
b) incorrect passwords

**Comment by cmuench** [comment]
@pquerner I think your approach needs a Magento as base system which is fully mockable. Currenlty i see now way to bootstrap Magento for a dry mode. We added a soft init mode in the last release for commands which only uses the class loading. How should we do this for any command relying on Mage::app() ?

**Comment by tkn98** [comment]
> "On the go", without a magento somewhere

This is not what I understand with dry-run. Dry-run is not without the system, but with the concrete system configuration (compare with git) but not applying changes. So validating input values to the largest extend but not applying changes. Similar to read-only mode or to doing data-base transactions but then rolling back (not very strictly, a transaction modifies the underlying system even rolled back for primary key sequences for example).

I had similar thoughts as @cmuench when thinking about this request the last week and the only thing that was imagineable to me would be that certain commands would need to understand what dry-run would mean to them. This is quite some work for the implementation and also the upfront design.

**Comment by pquerner** [comment]
Ok maybe we got the term "dry-run" wrong.
By this mode, dry-run, I mean it wont init Mage, it wont init a dabase, it wont init anything BUT simply execute the commands (whatever command) and returns the result.

So:
'php magerun.phar some-cool-command --dry-run' would execute the functionality behind 'some-cool-command' but would only echo certain stuff (which has to be implemented in some way, of course).

Example:
```
php magerun.phar admin:user:create --dry-run
Username: xxx
Email: xxx
....

Summary:
(data from above)

OK: Admin can be created (or)
ERROR: Check your password (or)
INFO: BLA BLA BLA
```

So its executing the logic (for example create a admin user) but before "doing that" to magento it will return and NOT execute anything on that system.

**Comment by tkn98** [comment]
For CLI commands as we have them this would be merely the filtering and validating of input values. However validating sometimes already requires knowledge of the underlying system (e.g. for setting a user password, one can validate if the user actually exists) and therefore a dry-run would need to do more than just not having the underlying magento system.

So where to draw the line. And how to clearly communicate to the user what such a dry-run mode would be. Also how much use would it actually provide for the work involved?

E.g. I'm fine with adding some new mode to certain commands if some of our users sees real use of that, but it should be because of a concrete need.

Perhaps you can outline the scenario you have in mind for this a bit and say more directly what you missed in concrete? I personally do love the dry-run principles in git, that's for my personal background. I do see, that you have a different background on this, no problem with that. Just saying.

**Comment by pquerner** [comment]
Yes its true that a "dry-run" mode in a "creation process" wouldnt be clever. It cant actually check if everything is met so this command can be executed (as you said, it wont know if a user by that name/email already exists etc.).

Although it makes perfect sense with your suggestion that we have some sort of "rollback" service IF we're in the "dry-run" mode.

This way (line above) would perfectly match my needs tbh.
I can then
a) see if my custom command works (without doing anything to magento)
b) can debug my custom command if needed

This applies to any other existing command aswell, of course.

**Comment by ktomk** [comment]
A "--dry-run" mode would need to be created on a per command basis. What I also found out is, that you normally want to give more information when doing a dry run (for example that an operation is a dry run and therefore does not apply changes etc.).

So I'll close this issue for now here as it's too broad. But closing this ticket does not mean we won't accept patches. If there is a dry-run suggestion for a concrete command, feel free to create an issue describing it.
