### ISSUE TITLE
n98-magerun: command not found

### ISSUE THREAD

**Issue by Qbixx** [netz98/n98-magerun#627]
Hello,

I've followed the steps in the installation guide:
1. wget http://files.magerun.net/n98-magerun-latest.phar -O n98-magerun.phar
2. chmod +x ./n98-magerun.phar

However when I try to use a n98-magerun command inside the terminal (i'm in the same folder as the n98-magerun.phar file), I get the following message:
$ n98-magerun: command not found

Am I missing a step in the installation? Or how can I make the command to get working?

Thanks

**Comment by ktomk** [comment]
The command is named `n98-magerun.phar` (you missed the `.phar` extension). Additionally you need to specify the (relative) path to the command which then is `./n98-magerun.phar`. Alternatively you can put the binary into your path then you won't need to specify the path and you could use the command by it's name alone.

Can you leave the link to the installation guide you followed so it's more clear to which documentation you refer to with your issue report here?

And would you share the operating system you're using?

**Comment by Qbixx** [comment]
Thanks, running the `./n98-magerun.phar` command works.

For future reference:
- I've used the installation guide in the README file on https://github.com/netz98/n98-magerun
- I'm using Mac OS X 10.10.4

**Comment by tkn98** [comment]
@Qbixx: Thanks for the detailed feedback. I think we can update and make that more clear within the readme for a smooth start (display version to verify install worked).

**Comment by tkn98** [comment]
I've updated the readme and the instructions *should* be more clear now :) It's also shown how to verify the download and the installation of the command itself. You can see the changes on the development branch: https://github.com/netz98/n98-magerun/blob/develop/readme.rst
