### ISSUE TITLE
Magento 1.9.2.1 is out

### ISSUE THREAD

**Issue by ktomk** [netz98/n98-magerun#630]
New security patch and revision. I assume it will be similar to #609, so pro-forma creating this issue and waiting for the mirror to update.

**Comment by ktomk** [comment]
Magneto-Mirror has 1.9.2.1 now. Upstream reference is: https://github.com/OpenMage/magento-mirror/pull/24

**Comment by tkn98** [comment]
The currently given file behind Cookie-Login is:

- File: `magento-1.9.2.1.tar-2015-08-03-06-35-45.gz`
- MD5: `61faafc54f3f1e81bd2d89f358aaba80`
- SHA1: `41b4b9ae2e02fa9fecf3330e19790120aeeced92`
