### ISSUE TITLE
PHP Fatal error:  [] operator not supported for strings

### ISSUE THREAD

**Issue by Den4ik** [netz98/n98-magerun#632]
Using with `$ magerun dev:module:observer:list`.

	PHP Fatal error:  [] operator not supported for strings in phar:///usr/local/bin/magerun/src/N98/Magento/Command/AbstractMagentoCommand.php on line 558
	PHP Stack trace:
	PHP   1. {main}() /usr/local/bin/magerun:0
	PHP   2. N98\Magento\Application->run() /usr/local/bin/magerun:8
	PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/magerun/src/N98/Magento/Application.php:643
	PHP   4. N98\Magento\Application->doRun() phar:///usr/local/bin/magerun/vendor/symfony/console/Symfony/Component/Console/Application.php:126
	PHP   5. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/magerun/src/N98/Magento/Application.php:583
	PHP   6. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/magerun/vendor/symfony/console/Symfony/Component/Console/Application.php:195
	PHP   7. N98\Magento\Command\AbstractMagentoCommand->run() phar:///usr/local/bin/magerun/vendor/symfony/console/Symfony/Component/Console/Application.php:882
	PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/magerun/src/N98/Magento/Command/AbstractMagentoCommand.php:448
	PHP   9. N98\Magento\Command\Developer\Module\Observer\ListCommand->execute() phar:///usr/local/bin/magerun/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
	PHP  10. N98\Magento\Command\AbstractMagentoCommand->askForArrayEntry() phar:///usr/local/bin/magerun/src/N98/Magento/Command/Developer/Module/Observer/ListCommand.php:58

**Comment by ktomk** [comment]
Can you please try if you have the same issue with the development version of magerun? You should be able to switch between stable and dev version with the self-update command.

**Comment by tkn98** [comment]
Thanks for reporting the issue. I can confirm the problem. A fix is on the way.

**Comment by tkn98** [comment]
This has now been fixed in the development version. It might take some minutes until it updates and you can test with self-update of the unstable version if it solved your issue.

The original fix still had a flaw, I just fixed it within the development version directly.

The fix will be available in the next stable release.

**Comment by Den4ik** [comment]
Thanks for fix
