### ISSUE TITLE
Update version of faker

### ISSUE THREAD

**Issue by RSully** [netz98/n98-magerun#646]
My project uses `fzaninotto/faker` version `^1.5` per `composer require`, but since magerun requires `1.4.*` I cannot use the two together (`composer require n98/magerun` fails).

**Comment by ktomk** [comment]
What would be your suggestion for the requirement of `fzaninotto/faker` in Magerun? I don't have much of an insight with that library so some suggestions would be helpful. Is `~1.4` sane with that library for example? If so this would be an easy way to deal with your issue here.

**Comment by RSully** [comment]
I would expect that `~1.4` is safe, but I have not looked into how you guys use it internally.

**Comment by tkn98** [comment]
From top of my head it's used to generate fake customer / order data.

I'd say give it a try and create a pull request with these changes and then you can see how tests run on travis.

**Comment by ktomk** [comment]
@RSully: Do you want to try a patch for this one?

**Comment by jameshalsall** [comment]
The work done in #651 has fixed this issue.

**Comment by RSully** [comment]
Great. @ktomk sorry it has been a few weeks since I've touched the project, but it should be fixed now if that was merged.

**Comment by ktomk** [comment]
@RSully; Yes, sorry for the mass ping and no futher updates, went out of my viewport. Please give it a try and report back if it is actually fitting your needs or not. I'm with you that it should be fixed, but as you opened the issue, your feedback is greatly appreceated.
