### ISSUE TITLE
FPC cleared - even if not

### ISSUE THREAD

**Issue by tkn98** [netz98/n98-magerun#648]
The command does not provide any error information in case FPC clearing was NOK.

**Comment by ktomk** [comment]
Needs an enterprise instance to test:

    \Enterprise_PageCache_Model_Cache::getCacheInstance()->flush();

**Comment by steverobbins** [comment]
What command are you referring to?  It doesn't look like either caches are being validated after a cleaning/flush

* https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Cache/CleanCommand.php#L54-L56
* https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Cache/FlushCommand.php#L33-L34

**Comment by tkn98** [comment]
Wow, thanks for the quick changes. Yes, these places.
