### ISSUE TITLE
new magento upgrade (version 1.14.2.1) detected as magento 2 

### ISSUE THREAD

**Issue by magicaner** [netz98/n98-magerun#652]
at src/N98/Util/Console/Helper/MagentoHelper.php doing check by searching bootstrap.php and mage.php. At magento 1.14.2.1 those files are exists which results as wrong version detection.

**Comment by ktomk** [comment]
Just checked your report in the development tree for the file [src/N98/Util/Console/Helper/MagentoHelper.php](https://github.com/netz98/n98-magerun/blob/develop/src/N98/Util/Console/Helper/MagentoHelper.php) and even it is checked for both files you name (`Mage.php` (not `mage.php` (!)) and `bootstrap.php`), when `Mage.php` is found, this is a *not* condition of Magento 2.

At least this is what I see from the code alone. I would therefore say your report is bogus, as you wrote that when `Mage.php` is found, Magento 2 would be detected. But that is not the case: https://github.com/netz98/n98-magerun/blob/develop/src/N98/Util/Console/Helper/MagentoHelper.php#L309

I'm pretty sure 1.14.2.1 has the file named `Mage.php`.

Please review what I just wrote and let me know if you still see an issue.

**Comment by adam-paterson** [comment]
@ktomk I managed to replicate this once too, but couldn't replicate it again.

**Comment by ktomk** [comment]
@adam-paterson: Hmm, if I get a way to replicate it, okay. Maybe code-review needs a second pair of eyes as well, couldn't spot the issue in the code on my own. Maybe you spot something?

**Comment by davidalger** [comment]
Cross-reference: #465

**Comment by ktomk** [comment]
@magicaner: For which Magerun version is your report?

**Comment by magicaner** [comment]
i am using 1.90.0

**Comment by magicaner** [comment]
looks like i am using old version :)

**Comment by ktomk** [comment]
@magicaner: Yes, we suspected that :) Is there a reason you're tight to that version? Why not upgrade to the current one?

**Comment by magicaner** [comment]
@ktomk: no reason :), i just forgot to rebase forked branch on original branch

**Comment by ktomk** [comment]
ah, okay, so I'll close for now. If you still see things to do, you can re-open at any time.
