### ISSUE TITLE
PHP Fatal error: on Cannot redeclare class abstractrepositorycommand

### ISSUE THREAD

**Issue by rileyhawbaker** [netz98/n98-magerun#653]
Getting this error when attempting to run `sys:check`. 
All other n98-magerun commands seem to work properly.
This was happening before I self-updated and still happening after a complete delete and reinstall.

```
PHP Fatal error:  include(): Cannot redeclare class n98\magento\command\script\repository\abstractrepositorycommand in phar:///chroot/home/user/n98-magerun.phar/vendor/composer/ClassLoader.php on line 382
Segmentation fault
```

**Comment by tkn98** [comment]
Do you remember from which version you upgraded? And can you say if you use stable or unstable versions?

**Comment by tkn98** [comment]
Also please check this issue: https://github.com/netz98/n98-magerun/issues/314

**Comment by ktomk** [comment]
@rileyhawbaker: Do you still have this issue? Are you able to share some more details? Please see the other comments as well.
