### ISSUE TITLE
PHP Fatal error:  Cannot redeclare class Symfony\Component\Finder\Expression\Expression

### ISSUE THREAD

**Issue by astorm** [netz98/n98-magerun#655]
Just grabbed a copy of `n98-magerun` via wget and dropped it onto a Nexcess MCE server.  I'm getting the following error when I try to run Magerun (happens with or without the APC flags)

    $ ~/bin/n98-magerun.phar -d apc.enable_cli=0
    PHP Fatal error:  Cannot redeclare class Symfony\Component\Finder\Expression\Expression in phar:///chroot/home/[username]/bin/n98-magerun.phar/vendor/symfony/finder/Symfony/Component/Finder/Expression/Expression.php on line 17

Is this a known thing -- i.e. any workarounds until the core cause has been found.

Thanks!

**Comment by tkn98** [comment]
@astorm: Not that I know of. APC was in the past but if you disabled it this shouldn't be it (there is a related issue about APC alone but I don't have the reference at hand).

When I retrive both the current and the stable builds  and I check for the versions I don't see this issue:

	$ build/bin/files.php 
	===========================================================
	= unstable: http://files.magerun.net/n98-magerun-dev.phar =
	===========================================================
	Status..: HTTP/1.1 200 OK
	Size....: 9 110 522 (bytes)
	Modified: Tue, 25 Aug 2015 00:00:31 GMT

	============================================================
	= stable: http://files.magerun.net/n98-magerun-latest.phar =
	============================================================
	Status..: HTTP/1.1 200 OK
	Size....: 2 787 592 (bytes)
	Modified: Sun, 16 Aug 2015 16:31:24 GMT

	==============================
	= Verify Phar-Files Versions =
	==============================
	Unstable: n98-magerun version 1.97.6 by netz98 new media GmbH
			  MD5.: 078459df2f6397fa240c1def8f8f925a
			  Size: 9 110 522 (bytes)
	Stable..: n98-magerun version 1.97.5 by netz98 new media GmbH
			  MD5.: 158e64856535f10e2259e9431b81ed82
			  Size: 2 787 592 (bytes)

The large file-size for the development build however is fishy. Have you picked the stable (master) or the unstable (develop) version?

**Comment by ktomk** [comment]
The fishy development build looks like a setting for the nightly build. Pushing to develop triggering a fresh build looks good (/cc @cmuench).

**Comment by astorm** [comment]
Will close out for now then -- will reopen if is reoccurs.

**Comment by tkn98** [comment]
@astorm: Thanks for keeping track. And please re-open whenever this re-occurs, let's make this a true Heisenbug :)
