### ISSUE TITLE
Script mode without script parameter

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#674]
On some of the hosting environments we can install magerun to `/usr/local/bin`. I would like to use the env command to call magerun in scripts, so the scripts stay portable.

Example script file:

```
#!/usr/bin/env n98-magerun.phar script
db:info
```

Unfortunately this is not working because env does not accept params for the command.
What would work is

```
#!/usr/bin/env n98-magerun.phar
db:info
```

But here magerun does not know to execute a script.
Can we change magerun to auto-detect whether it should be called using a script, for example the way it is working with `bash` scripts?

**Comment by tkn98** [comment]
The problem in your scenario is the `/usr/bin/env` executeable. Please try with the one you suggest in your question:

    #!/usr/local/bin/n98-magerun.phar script

this should work. is that helpful?

**Comment by amenk** [comment]
Yes that is working. But I want the script to be portable on other systems. While on my dev machine magerun is in `/usr/local/bin`, on the server it is `~/bin` - that is why I use env to resolve this which is quite common for such scripts.

**Comment by amenk** [comment]
Some workarounds at: http://stackoverflow.com/questions/3306518/cannot-pass-an-argument-to-python-with-usr-bin-env-python - but all not nice. Especially `env -S` does not work on ubuntu.

**Comment by tkn98** [comment]
`/usr/bin/env` is not portable as well, not all systems have `env` in that path. But good to read that the path to the binary works. Can an alias be of help here? For everything else I would need to review this more, I like the idea to have it as an executeable for scripts.

**Comment by amenk** [comment]
I think aliases would not work.. I think the shebang is not parsed by the shell.

**Comment by tkn98** [comment]
While you bring this problem up, I just see it's also not easy to run a script from STDIN / pipe. This could also fall into the topic of shell integration.

**Comment by cmuench** [comment]
Closed due to inactivity. Feel free to re-open if needed.
