### ISSUE TITLE
cache:clean Command withTurpentine Module (Varnish)

### ISSUE THREAD

**Issue by lundsted** [netz98/n98-magerun#677]
When i run magerun `cache:clean`, it makes issues with sites that have varnish installed. 
cache:clean removes the base URL, so all content goes into index.php (with the turpentine module installed).

Before:

    <link rel="stylesheet" type="text/css" href="http://site.com/media/css/982547485a263066e6661a486c29625c_1441634392.css" media="all" />
                                                 ^^^^^^^^^^^^^^^^

After:

    <link rel="stylesheet" type="text/css" href="/media/css/982547485a263066e6661a486c29625c_1441634392.css" media="all" />
                                                 ^

(http://pastebin.com/MBtUUkpH)

This makes the site crash, since it spawns a lot of other php instances to deal with the high load of index.php.

**Comment by ktomk** [comment]
Can you share the version of Magerun you are experiencing this problem with and what are the versions of Magento and the Turpentine module you describe the issue with?

Are you able to test with the unstable version of Magerun (e.g. on a development box) and if so can you give it a try and see if it still has the issue?
