### ISSUE TITLE
Show error when maintenance command fails

### ISSUE THREAD

**Issue by wojtekn** [netz98/n98-magerun#678]
It's similar to issue #412 which is about cache permissions.

When I enable maintenance mode on directory where I don't have write permissions I get false success message:

    $ n98-magerun.phar sys:maintenance --on
    Maintenance mode on

What do you think about adding error checking in `_switchOn` and `_switchOff` methods?

https://github.com/netz98/n98-magerun/blob/1a4308ed8c3ac5f5b4b94d61d3f202c0cb0d2ff9/src/N98/Magento/Command/System/MaintenanceCommand.php#L49

**Comment by tkn98** [comment]
Thanks for bringing up that issue.

http://php.net/touch and http://php.net/unlink do indeed have return values. Additionally there could be a check routine that checks whether or not maintenance mode is on. That should make it rather robust.

I like your idea. Are you willing to contribute a patch?

**Comment by wojtekn** [comment]
@tkn98 I've just added pull request, however I see @steverobbins added one in the meantime. 

FYI, I've compiled phar build containing my change and tested it on environment without write permissions and it worked fine. I thought about adding test for this however at this moment I don't see an easy way to mock up this.

**Comment by tkn98** [comment]
Yes @steverobbins did add a PR but he did a lot more than just fixing the flaw. I'd like to keep these things separated for the moment, so please re-create your PR against the develop branch (as I commented in your PR).

**Comment by tkn98** [comment]
@steverobbins: Thanks for providing a pull request, but there is acutally a user taking care of that flaw. I know that you take care of more here, but at least please consider to wait a little for the refactoring (fixes first) and also we can't accept PR's against master (feel free to rebase your changes on top of develop after we have the fix in and open a new PR).

**Comment by ktomk** [comment]
Thanks for your contribution! This has been fixed in the development branch of Magerun which is available as the *unstable* version and it will be part of the next stable release. Thank you for taking care!
