### ISSUE TITLE
Modman generator command

### ISSUE THREAD

**Issue by barryvdh** [netz98/n98-magerun#685]
I've created a simple Magerun command to simplify the generation of modman files, with the following features:
- Scan all files in current directory
- Combine app/code/(community|local)/<vendor>/<package> directories
- Possibility to have subdir with module code (eg. `src/app/code` etc)

It doesn't actually do anything with Magento, but just use the Magerun command framework for the current directory.

Is this something you are interested in for including, or should I create my own repo and add as 3rd party?

Initial working version: https://gist.github.com/barryvdh/b3523bf30d7d4c379e05

**Comment by sprankhub** [comment]
:+1: for including it into n98-magerun core (though I did not test it yet)!

**Comment by barryvdh** [comment]
I've create a module version, let me know if this is something for the core!

https://github.com/fruitcakestudio/magerun-modman

**Comment by ktomk** [comment]
Hi @barryvdh, thanks for opening an issue.

First of all and as you did, creating a third-party-module is always an option. 

You can also give @oasisfleeting a ping as he has created an amazing list of magerun addons (ref: #624).

I can't say tonight if this is something for the core as I even haven't tried it myself yet, but from what you write it does I think this is a great idea! I normally edit those files by hand but for initial creation I can imagine this is helpful.

Code looks good on first glance, one can see it's new but looks very well for that. I can imagine it works nicely. And nice move to format the file with the Table display.

For core this needs some decision. So if anyone wants to raise opinion please do! :)

**Comment by tkn98** [comment]
It's not easy to decide for core functionality. On the one hand, it seems that the dev: namespace is fitting for this, on the other hand this could trigger quite some support and for support triaging we're not well set-up currently (e.g. we could use some manpower).

I personally would love to see more traction on #624 so that it's easier for magerun users to discover the available third party tools.

@barryvdh: Some feedback from you on these thoughts would be really appreceated. What would you prefer? What would be acceptable for you? What would be ideal?

**Comment by razbakov** [comment]
this module do it cleaner - https://github.com/mhauri/generate-modman

**Comment by barryvdh** [comment]
You mean different?

**Comment by barryvdh** [comment]
Dev namespace would work. I understand the maintenance thing, I'm okay with you guys pinging me for issues, but can't guarantee long time support.
But modman isn't new so I guess there isn't much change, once implemented.

**Comment by tkn98** [comment]
@barryvdh: Could the differences with the other module combined with your approach? And PR's are always welcome, if you say you can't give long time support that's fine, better to say it before than afterwards. Much appreciated.

And if you create a PR and it's a derivative work (which IIRC is the case with your gist), please give credits / source and highlight that you changed it. Thanks.

**Comment by barryvdh** [comment]
@tkn98 Which other module? https://github.com/mhauri/generate-modman is a shell script, so not really much to combine. But I've based my logic on that module, as well as other (as mentioned).

I've stated that I based that method on a different gist (https://gist.github.com/schmengler/88fa071822a95224373f) , in the source. Or where do you want to put it exactly?

**Comment by tkn98** [comment]
@barryvdh: Okay, was not aware of the shell script detail, was just asking in case something can go together. Fine so! For the credits, do as you see fit, I'll review the PR, this does not need to be fancy or anything, just do as *you* see fit.

**Comment by cmuench** [comment]
Closed due to inactivity. Feel free to re-open if needed.
