### ISSUE TITLE
sys:cron:run does not trigger observers if an event is dispatched in cronjob model

### ISSUE THREAD

**Issue by a-dite** [netz98/n98-magerun#689]
Was tested with adminthml and global observers. Running `cron.php`, observer methods are triggered, running `sys:cron:run` - not.

**Comment by tkn98** [comment]
can you share the magento and magerun version for this issue?

**Comment by therouv** [comment]
EE 1.14.1.0 / magerun 1.97.6

**Comment by robbieaverill** [comment]
I've just tested this on Magento EE 1.14.2.1 / Magerun 1.97.7 by creating a method on a local module's event observer model (and configuring it as a cron job of course):

```
    public function robbieTest()
    {
        Mage::dispatchEvent('robbie_test_event');
        echo 'Finished.' . PHP_EOL;
    }

    public function robbieTestObserved()
    {
        echo 'Observer called!' . PHP_EOL;
    }
```

Configuring `robbieTestObserved` to be called on the `robbie_test_event` event in the **global scope**, and running the test against Magerun and a quick test shell script, the results are the same:

```
include 'app/Mage.php';
Mage::app('admin');
Mage::getModel('robbie_test/observer')->robbieTest();
```

Output:

```
$ php test.php
Observer called!
Finished.

$ n98-magerun.phar sys:cron:run robbie_test_cronjob
Run Robbie_Test::robbieTest Observer called!
Finished.
done
```

Seems to be working correctly to me.
