### ISSUE TITLE
Class N98\Util\String is not compatible with PHP 7

### ISSUE THREAD

**Issue by yireo** [netz98/n98-magerun#691]
When running Magerun with a PHP CLI of version 7, the following error occurs:

```
PHP Fatal error:  Cannot use N98\Util\String as String because 'String' is a special class name in phar:///.../magerun/src/N98/Magento/Application.php on line 11
```

The reason for this is that - well the error already says it - String is a reserved name and can't be used for classnames. To fix this, the String class needs to be renamed. In other PHP projects, I've already seen renaming to "Text" or "Strings" or something similar.

Do you have any ideas on what would be the best name?

**Comment by tkn98** [comment]
Thank you for the report. This should be easy to fix.

**Comment by yireo** [comment]
Thanks, it is not that difficult. Unforunately (?) I'm on a holiday and working from a computer that does not play nice for development, so no PR yet from my side :(

**Comment by tkn98** [comment]
No worries, I assigned myself already, I try to have a patch ready when I find some minutes.

**Comment by ktomk** [comment]
We now have a PHP 7 syntax check on Travis and the problems have been fixed. You can find the changes in the unstable development version already. Thanks again for taking the time to report this, PHP 7 is around the corner and this is adding good precautions.

**Comment by yireo** [comment]
That's really awesome - I'm definitely going to check upon the PHP 7 syntax check in Travis. Sounds really useful. Thanks for the great contribution!
