### ISSUE TITLE
Cannot `n98-magerun install magento-ce-1.9.2.1`

### ISSUE THREAD

**Issue by connerbw** [netz98/n98-magerun#693]
Steps to reproduce:

Get and install latest dev version:
 + http://files.magerun.net/n98-magerun-dev.phar

Do `n98-magrun install`

Expected:
**magento-ce-1.9.2.1** available as a choice

Actual:
**magento-ce-1.9.1.1** 

I see the work has been done early August: 

https://github.com/netz98/n98-magerun/issues/630

When will this be merged down for users?

Thanks.

**Comment by connerbw** [comment]
Ok. Now I see it's named **magento-mirror-1.9.2.1**

Sorry. No bug.

**Comment by ktomk** [comment]
Yes that's correct, magento 1.9.2.1 is only available from mirror. An no problem at all :)
