### ISSUE TITLE
Bash autocomplete doesn't allow path completion

### ISSUE THREAD

**Issue by bluec** [netz98/n98-magerun#695]
The autocomplete is a nice feature but enabling it breaks path completion.

Example:

magerun --root-dir=/[TAB][TAB]

This should start to autocomplete the path, but it doesn't do anything. Particularly annoying when using mpmd:corehacks which I realise is not a core component but it's one of the most useful magerun tools.

Can anyone confirm this behaviour? I am going to dig around some bash completion scripts and see if I can figure out how to fix it.

**Comment by bluec** [comment]
Ah ok this is easier to fix than I thought:

complete -o dirnames -F _n98-magerun n98-magerun.phar
complete -o dirnames -F _n98-magerun n98-magerun
complete -o dirnames -F _n98-magerun magerun

Ref: http://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html

**Comment by ktomk** [comment]
@bluec: We recently changed the bash autocomplete again, the feature you've been asking for is still available but it's perhaps a bit different now, so you probably want to try if it suits your needs. Commandline options and flags are now autocompleted, too.
