### ISSUE TITLE
ioncube: feature request for sys:check

### ISSUE THREAD

**Issue by it-scripter** [netz98/n98-magerun#697]
For me it would be fine to have an information if iconcube is installed and the used version.

Sometime there are encrypted extensions and you must have ioncube installed to run the shop. 

Greetings

**Comment by ktomk** [comment]
@it-scripter: Are you willing to create a pull-request for it? And just a heads up, don't let yourself be stopped by this: we have a known problem with the sys:check command: It takes the PHP configuration for CLI (Command-Line) which can (often is) differently configured than the PHP SAPI used in the webserver configuration. Just saying, a related issue for that known problem is the one about the memory limit: #586. In your case as cron.php is run via PHP CLI as well, the check would make sense in your scenario anyway.

**Comment by ktomk** [comment]
Ioncube also has host-based protection. the sys check command when finding out about that ioncube is installed should as well offer the hostname as it should be used in ioncube host-based license files. I'm not that fluent with ioncube, perhaps @it-scripter you can offer some information how ioncube obtains the hostname for it's license files?

**Comment by it-scripter** [comment]
@ktomk Sorry, I have no experience as an user of the ioncube encoder, just as an user of lisensed and encoded scripts. 
But in the enoder manual on page 29 "Locking Files to Specific Domains and Servers" you will find the hint that there is the command

`--allowed-server [<domain names>][@[<IP addresses>]][{<MAC address>}]`

and this is checked against  
`$_SERVER['SERVER_NAME']`

May this is helpful for you. 
Merry x-mas

http://www.ioncube.com/sa/USER-GUIDE.pdf

**Comment by tkn98** [comment]
@it-scripter: Thanks for the info. I was actually looking for the `$_SERVER['SERVER_NAME']` info, so the command can output the hostname.

**Comment by it-scripter** [comment]
Great. Is this global variable available in the cli environment? I believe to remember that there is sometimes a problem with cli-calls of encoded scripts when the server-name isn't set right. In this cases (started by cron job, even with mage:run?) the script have to be encoded additional with the ip-address.

**Comment by tkn98** [comment]
Well, if that `$_SERVER` entry is not set for the CLI configuration, magento cronjobs incorporating host-encoded ioncube PHP scripts, I think a fatal error is given. I don't think that ip-adress helps here if the entry is empty (NULL).

**Comment by it-scripter** [comment]
Right. But encoded scripts for cron jobs must than encoded with ip - or the `$_SERVER` should set well

**Comment by ktomk** [comment]
@it-scripter: Is it so then that if $_SERVER is empty ioncube looks for the IP? Do you know how ioncube then looks for the IP so that it's clear which one to use in the report of the command?

**Comment by cmuench** [comment]
Closed due to inactivity. Feel free to re-open if needed.
