### ISSUE TITLE
Debug cron job run by magerun with PHPStorm/Xdebug

### ISSUE THREAD

**Issue by marvinosswald** [netz98/n98-magerun#699]
Really don't know how to connect debug to magerun, so maybe one of you guys have done this before and can provide some advice

Cheers Marv

**Comment by tkn98** [comment]
First of all make your IDE listen for Xdebug connections and test if that works. Then:

Within the shell, prefix the call to Magerun with setting an environment variable:

    $ XDEBUG_CONFIG=1 ....

If you want to debug Magento code, you can use the phar file:

    $ XDEBUG_CONFIG=1 n98-magerun.phar ....

If you want to debug magerun sources as well, you need to invoke the source (in project this is `bin/n98-magerun` which is a PHP file):

    $ XDEBUG_CONFIG=1 php -f path/to/bin/n98-magerun -- ...

This is typed quickly, I think this is what you're looking for and I hope there are no errors with it. Please let me know if you have further questions. Basically this is Xdebug in the terminal and you need to decide which code to debug (Magerun or Magento or perhaps even both).

**Comment by marvinosswald** [comment]
Thanks, you've shown me the right direction :+1: 

This line finally did it for me:

`PHP_IDE_CONFIG="serverName=Vagrant" XDEBUG_CONFIG="remote_host=10.3.8.65 idekey=PHPSTORM" n98 sys:cron:run`

**Comment by tkn98** [comment]
Thanks for your feedback and great to read it worked for you. Indeed the variables can vary, and I didn't consider a different remote host. :+1:

**Comment by bharathkumarj-tech** [comment]
Hey hi all , first of all I will tell you how I got the breakpoint set in one of my custom module's cron file, Actually it is very simple , make sure your xdebugger is working all right in magento setup , after that place the breakpoint in your scheduled cron file , in my situation my file was scheduled to run every 1 minute , and open the debugger for listening and just wait for a minute , yes this is a frustrating moment and after that moment your breakpoint will take the execution.So this is how it worked for me.
