### ISSUE TITLE
Phar file not up-to-date

### ISSUE THREAD

**Issue by p-makowski** [netz98/n98-magerun#700]
Hello Netz98 Team, 

I noticed that n98-magerun.phar file in this repository is not in the latest version. 
[n98-magerun version 1.96.1 by netz98 new media GmbH]

Is it on purpose? If it is not maintained in this repo anymore (I saw it is OK in http://files.magerun.net/) then maybe it should be removed from here?

Regards,
Patryk

**Comment by tkn98** [comment]
Yes, that is on purpose (both that is outdated *and* in there). The way we distribute the phar file changed, see #520 and #530 for some context.
