### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by chrom** [netz98/n98-magerun#703]
./n98-magerun.phar --version
PHP Notice:  Undefined index: argv in phar:///html/magento-de/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php on line 57
PHP Warning:  array_shift() expects parameter 1 to be array, null given in phar:///html/magento-de/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php on line 61
PHP Warning:  Invalid argument supplied for foreach() in phar:///html/magento-de/n98-magerun.phar/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php on line 287

**Comment by pocallaghan** [comment]
It sounds like you're running on a system where register_argc_argv is set to false/off in your php.ini. Try running the following `php -i | grep register_argc_argv`.

**Comment by chrom** [comment]
yepp
you're a right
<tr><td class="e">register_argc_argv</td><td class="v">Off</td><td class="v">Off</td></tr>

**Comment by chrom** [comment]
can you tell my for what we use register_argc_argv?

**Comment by tkn98** [comment]
The setting is used in PHP CLI to have the commandline parameters available. The ini-directive description is a little short (http://php.net/manual/en/ini.core.php#ini.register-argc-argv), you can find a better explanation on the [SAPI differences page in the manual](http://php.net/manual/en/features.commandline.differences.php).

In short: We use that setting (by it's default value `TRUE`) for the commandline interface, namely the parameters (also called switches).

You *might* have you PHP installation "misconfigured" by copying over an ini for HTTP usage (a different SAPI) for the CLI binary. But that is only a guess.
