### ISSUE TITLE
Cannot run n98-magerun

### ISSUE THREAD

**Issue by santosjoni** [netz98/n98-magerun#706]
I'm trying to install magerun on my magento server but I just cannot make it run properlly.

I followed all the instructions from [https://github.com/netz98/n98-magerun][1]

> # #wget http:// files.magerun.net/n98-magerun-latest.phar -O n98-magerun.phar
--2015-10-09 11:02:51--  http:// files.magerun.net/n98-magerun-latest.phar
Resolving files.magerun.net... 5.35.244.165
Connecting to files.magerun.net|5.35.244.165|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2787592 (2.7M) [application/octet-stream]
Saving to: `n98-magerun.phar'
100%[=============>] 2,787,592   9.09M/s   in 0.3s
> 
> # #md5sum n98-magerun.phar
158e64856535f10e2259e9431b81ed82  n98-magerun.phar
> # #chmod +x ./n98-magerun.phar
> # #./n98-magerun.phar --version
𑀀y?

As you can see, as I try to get the version installed I just get this "y?", as response.

Can someone help me with this please, thanks in advance

  [1]: https://github.com/netz98/n98-magerun

**Comment by cmuench** [comment]
@santosjoni I checked the current file. The checksum is ok. It's running on my local machine after i download the file.
Can you please check if phar file exection is disabled by your PHP configuration (i.e. suhosin)?

Add this to your php.ini:
    
     suhosin.executor.include.whitelist="phar"

**Comment by tkn98** [comment]
@santosjoni: Can you please share your PHP version (`php --version` ) your using? And can you check if you've got the GZ (and other compression related) extension enabled? `𑀀y?` smells like things can't be uncompressed (only a guess). The phar file *should* use the GZ compression.

Next to that is that a quick check revealed that the *nightly build* of the unstable phar is different to the inteded build. *In short that means it is broken*. This is not your fault.

Ich you can, please clone the git repository and checkout the *develop* branch, cd into the project directory and then invoke `build.sh`. This should create the phar file for you.

**Comment by santosjoni** [comment]
Hi guys,

I manage to run **magerun**. The problem was with php directly. Something with Unicode detection.

>]# curl -sS https://getcomposer.org/installer | php
#!/usr/bin/env php
Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

>The detect_unicode setting must be disabled.
Add the following to the end of your `php.ini`:
    detect_unicode = Off

>The php.ini used by your command-line PHP is: /usr/local/php53/lib/php.ini
If you can not modify the ini file, you can also run `php -d option=value` to modify ini values on the fly. You can use -d multiple times.

# php -d detect_unicode=Off n98-magerun.phar

Thanks all

**Comment by tkn98** [comment]
@santosjoni: Thanks for your feedback. What you write makes sense, however as far as the magerun application is concerned, consider to switch the `zend.multibyte` mode off (`-dzend.multibyte=0`). It's not required and as your example shows, it is flawed (stable is not of its properties, the use is limited (neglectable) in face of the UTF-8 Unicode encoding). This is also the reason in the first play why you need to set `detect_unicode` to `Off`. When you switch to PHP 5.4 that setting will be renamed to a different one. Setting `zend.multibyte` to `0` is more stable across PHP versions. Just FYI.

**Comment by tkn98** [comment]
I consider this closed, feel free to still post feedback on the topic here.
