### ISSUE TITLE
Magerun should self-test required PHP settings

### ISSUE THREAD

**Issue by ktomk** [netz98/n98-magerun#707]
There are some PHP settings that should be checked by magerun before starting up:
1. [`register_argc_argv`](http://php.net/register_argc_argv) must be enabled (required by symfony console input) - Reported in #703
2. [`STDIN`](http://php.net/manual/en/features.commandline.io-streams.php) is only available in PHP CLI (required by symfony console input) - Reported in #761  
3. [`zend.detect_unicode`](http://php.net/zend.detect_unicode) / [`detect_unicode` (5.3)](http://php.net/detect_unicode) must be disabled if zend.multibyte  [`zend.multibyte`](http://php.net/zend.multibyte) is enabled - Reported in #706
4. APC enabled in CLI can cause problems; [`apc.enable_cli`](http://php.net/manual/en/apc.configuration.php#ini.apc.enable_cli) / [`apc.enabled`](http://php.net/manual/en/apc.configuration.php#ini.apc.enabled); see #655, #314, #181 and #153 and [comment below](https://github.com/tkn98).
5. Memory limit and [fatal error handling](https://github.com/netz98/n98-magerun/issues/365#issuecomment-88794866); see #365

For starters I had the idea to do that within the phar stub to exit early on error.

**Comment by ktomk** [comment]
There might also use to check for PHP extensions however those are more functionality related required. At least those should be suggested within the composer.json. See https://github.com/netz98/n98-magerun/issues/713#issuecomment-150233394

**Comment by tkn98** [comment]
If APC is enabled in CLI there can be errors like

>  Fatal error: include(): Cannot redeclare class n98\util\binarystring in phar:///path/to/bin/n98-magerun.phar/vendor/composer/ClassLoader.php on line 382

See as well #655, #314, #181 and #153. in the composer repo there is a related thread: https://github.com/composer/composer/issues/264 .

PHP Settings involved:

* `apc.enable_cli=0` (fix because it disables APC)
* `apc.enabled=0`(fix because it disables APC; this was reported today)
