### ISSUE TITLE
Wrong composer installation documentation

### ISSUE THREAD

**Issue by andkirby** [netz98/n98-magerun#708]
```
php ./composer.phar create-project n98/magerun <folder>

#. Run cli.php
php vendor/bin/n98-magerun
```
It should be `php bin/n98-magerun`.

**Comment by ktomk** [comment]
Thanks for reporting, this has been fixed. If you like, take a look:

- https://github.com/netz98/n98-magerun/wiki/Install-from-source-with-Composer

(I think that's the page you were referring to).
