### ISSUE TITLE
Reindex All Command ignores errors

### ISSUE THREAD

**Issue by AydinHassan** [netz98/n98-magerun#709]
It seems the Reindex All command silently ignores errors. See: https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Indexer/ReindexAllCommand.php#L62

It should probably display some sort of error, I can take a look at implementing this in the next couple of days.

**Comment by tkn98** [comment]
Good idea. I'd say it should be like in the positive case, just as an error: https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Indexer/ReindexAllCommand.php#L53

**Comment by cmuench** [comment]
Please verify if everything is ok. We supplied a fix for that with #911.
I close this ticket. Feel free to re-open it if there is any issue.
