### ISSUE TITLE
/usr/bin/env: php: No such file or directory

### ISSUE THREAD

**Issue by YeserYap** [netz98/n98-magerun#713]
Hello,
I've followed the steps in the installation guide:
1. wget http://files.magerun.net/n98-magerun-latest.phar -O n98-magerun.phar
2. chmod +x ./n98-magerun.phar
However when I try to use a n98-magerun command, I get the following message:/usr/bin/env: php: No such file or directory
Am I missing a step in the installation? Or how can I make the command to get working?

**Comment by tkn98** [comment]
Please check if the `php` command is available in your terminal. You can check that by entering:

     php --version

If PHP is installed for the command-line it should show something along the lines like:

    PHP 5.5.26-1~dotdeb+7.4 (cli) (built: Jun 18 2015 17:32:35) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

If not you should see an error message similar to:

    -bash: php: command not found

(can vary depending on login shell)

Please report back with the outcome.

If PHP is not available on the commandline, please install it first. I assume this is the problem but by the information you've provided so far, this is just an assumption.

Please also report which operating system you're using.

**Comment by YeserYap** [comment]
Hello,Tom
PHP 5.3.3 (cli) (built: Jul  9 2015 17:39:00)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

**Comment by tkn98** [comment]
@YeserYap: Thanks for you quick feedback. It's perhaps then an issue with your system configuration.

On your system you're for the moment required to launch magerun via PHP:

    php -f n98-magerun.phar -- <all magerun parameters follow here>

For example:

    php -f n98-magerun.phar -- --version

Can you please share on which operating system you're having this issue?

**Comment by YeserYap** [comment]
n98-magerun version 1.97.5 by netz98 new media GmbH，my operating system is CentOS 6.5 x64

**Comment by tkn98** [comment]
So this issue is related to /usr/bin/env on CentOS 6.5 x64 - thanks for the info.

Was the information so far helpful and can you make use of magerun that way?

**Comment by YeserYap** [comment]
Hello,Tom
It works now,thank you very much!

**Comment by YeserYap** [comment]
as n98-magerun.phar sys:website:list
get information:
  [RuntimeException]
  Magento folder could not be detected

**Comment by tkn98** [comment]
Try with `-vvv` it should output where it looks. That might give you some hints to get started. Additionally please check the blog, you can create a file to hint the location within a project (`.n98-magerun` it's called, see #444 etc.).

**Comment by YeserYap** [comment]
as n98-magerun.phar ---v
Note:Cannot initialize Magento. Please check your configuration. Some n98-magerun command will not work. Got message: The PDO extension is required for this adapter but the extension is not loaded

**Comment by cmuench** [comment]
@YeserYap Does it run with installed PDO module?

**Comment by YeserYap** [comment]
still not

**Comment by ktomk** [comment]
please check the output of `php -i` (or `php -m`) on the commandline that PDO is actually active. See `php -h` for more detailed infos on the command line switches.

**Comment by ktomk** [comment]
That message means the *php cli* on your system does not have PDO configured. PDO is needed for both Magento and Magerun. Magerun uses the command line interface version of PHP (php cli sapi) which normally has a php.ini configuration file on it's own (read: next to the webserver php configuration).

Entering

    php -i | grep -A3 "Configuration File"

on the commandline should show you which php.ini there is to check for PDO.

**Comment by YeserYap** [comment]
Hi,Ktomk
after enter php -i,get info:
n98-magerun.phar ---v
Cannot initialize Magento. Please check your configuration. Some n98-magerun command will not work. Got message: The PDO extension is required for this adapter but the extension is not loaded

**Comment by ktomk** [comment]
@YeserYap: You must have misunderstood me. Please enter

    php -i

only on the command line. Nothing else. It will create a long, very long output which you need to read from top to bottom containing all the available information about your command-line version of php installed. Please consult the documentation of the PHP interpreter you're using.

You can learn about PHP commandline options in the PHP manual here:

- http://php.net/manual/en/features.commandline.options.php

If you're not a native English speaker, the PHP manual also offers translations.

In the end you need to ensure and proof for yourself that the PHP version used on the command line on your system is configured with the PHP PDO extension. As long magerun tells you that this is not the case I would suggest to assume that this really *is* the case, which means, the PDO extension is *not* configured with your command line version of PHP installed.

So you need to first verify this situation with the tools PHP itself has on board independent to magerun. It's perhaps most straight forward you look up in the documentation of your operating system on how to install PHP with PDO.

**Comment by ktomk** [comment]
@YeserYap: Is this still an issue for you? Could you figure out how to setup a working base-system on top of Cent OS  6.5  for PHP/magento/magerun for PHP cli?
