### ISSUE TITLE
Info notice if dev:class:lookup returns a class that doesn't exist

### ISSUE THREAD

**Issue by robbieaverill** [netz98/n98-magerun#720]
Hi,

This is a feature request to add a notice when looking up a Mage resolution that returns a non-existant class, e.g.:

```
$ n98-magerun.phar dev:class:lookup helper catalog/nothing_to_see_here
Helper catalog/nothing_to_see_here resolves to Mage_Catalog_Helper_Nothing_To_See_Here
```

It might be nice to add a message at the bottom e.g. "Note: the resolved class does not exist."

It seems feasible to add it here: https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Developer/ClassLookupCommand.php#L40 in the form of something like:

```
if (!class_exists($resolved)) {
    $output->writeln('<info>Note:</info> <comment> ' . $resolved . '</comment> does not exist!');
}
```

...however I haven't managed to get my builds working yet so can't test it.

Let me know what you think.

Cheers,
Robbie

**Comment by tkn98** [comment]
Can you tell shortly what fails with your build? And we have a recent fix with it just some days ago, perhaps it works now directly? Just interested.

And you can create a pull request even if you can't build it yourself. We have automated builds when you create and/or update a pull request. Please create pull requests against the develop branch.

**Comment by robbieaverill** [comment]
Hi @tkn98 ,

Thanks for that. I've tested without the build and pushed up a pull request for it.

FYI the build wouldn't complete for me due to openfiles limit being too low (OSX El Capitan). I didn't persist much further with my testing of it.

Cheers,
Robbie

**Comment by ktomk** [comment]
Okay, openfiles limit was touched in the recent fixes. The issue is #714 and the PR is  #715 - it contains some information, maybe it helps. Would be great to see getting it some traction because I can't test on OSX - but @cmuench I think can. Maybe you can report what hard- and soft-limit you've got on your system (command-line: `echo -n "soft: "; ulimit -Sn && echo -n "hard: "; ulimit -Hn` it's on linux, but maybe it work on OSX, too)?

**Comment by robbieaverill** [comment]
Hey Tom,

I'll let you know how it goes later on today.

Thanks
Robbie

On Tuesday, 3 November 2015, Tom Klingenberg <notifications@github.com>
wrote:

> Okay, openfiles limit was touched in the recent fixes. The issue is #714
> <https://github.com/netz98/n98-magerun/issues/714> and the PR is #715
> <https://github.com/netz98/n98-magerun/pull/715> - it contains some
> information, maybe it helps. Would be great to see getting it some traction
> because I can't test on OSX - but @cmuench <https://github.com/cmuench> I
> think can. Maybe you can report what hard- and soft-limit you've got on
> your system (command-line: echo -n "soft: "; ulimit -Sn && echo -n "hard:
> "; ulimit -Hn it's on linux, but maybe it work on OSX, too)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netz98/n98-magerun/issues/720#issuecomment-153102863>.
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by robbieaverill** [comment]
Hi again @ktomk / @tkn98 

#714 was useful. My soft/openfile limit was 256 as exhibited by `ulimit -a` or `ulimit -Sn`. If I change this to 2048 (for example) then the build *almost* completes correctly:

```
$ ulimit -n 2048
$ ulimit -Sn
2048
$ ./build.sh
# ...
BUILD FINISHED

Total time: 5.9363 seconds

n98-magerun version 1.97.6 by netz98 new media GmbH
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
SHA1: 356d0fcf870d19af95b18a9165730e4caf991972
MD5.: 8ef9799bc085a6b84837e0170b26a0f7
```

Looking at `build.sh` it looks like that error occurs after the build has completed, so I'm not overly concerned about it TBH.

**OS: OSX El Capitan 10.11**

Cheers,
Robbie

**Comment by ktomk** [comment]
Latest build.sh in develop does not have the `ls` problem any longer. Also it should automatically raise the soft limit up to the hard limit, so it should now work out of the box. Please give it a try without manually raising the soft limit. It *should* work. I'll close for now. Thanks again.
