### ISSUE TITLE
Adding missing versions from magento-mirror

### ISSUE THREAD

**Issue by fbrnc** [netz98/n98-magerun#724]
Looks like 
a) there are a couple of Magento versions from https://github.com/OpenMage/magento-mirror/releases missing in https://github.com/netz98/n98-magerun/blob/master/config.yaml
b) there are a couple or Magento versions missing on https://github.com/OpenMage/magento-mirror/releases (e.g. 1.8.0.0)

Since downloading packages from Magento.com is so painful and currently broken, it would be nice to rely on magento-mirror (e.g. for test runs using MageTestStand)

**Comment by fbrnc** [comment]
Ok, I just tagged 1.8.0.0 in magento-mirror (see https://github.com/OpenMage/magento-mirror/pull/27)

**Comment by ktomk** [comment]
These are in there now. Thanks for taking care!
