### ISSUE TITLE
Cron Job List command sys:cron:list does not merges system config path values

### ISSUE THREAD

**Issue by atishgoswami** [netz98/n98-magerun#727]
The `sys:cron:list` command does not consider the path values saved in the `core_config_data` table.

Example:
In the config.xml we have the following:
```xml
<crontab>
        <jobs>
            <foo_bar_cron>
                <run>
                    <model>foo_bar/observer::runFooJob</model>
                </run>
            </foo_bar_cron>
        </jobs>
</crontab>
```
and in `core_config_data` table we have:

Path  = `crontab/jobs/foo_bar_cron/schedule/cron_expr`
Value = `0 0 * * 1`

When we run `php n98-magerun.phar sys:cron:list` output 
does not show the scheduled time

```
+------------------------------------------------+------+----+----+----+----+
| Job                                            | m    | h  | D  | M  | WD |
+------------------------------------------------+------+----+----+----+----+
| foo_bar_cron                                   |      |    |    |    |    |
+------------------------------------------------+------+----+----+----+----+

```

**Comment by ktomk** [comment]
Is this also the case after flushing the cache?

**Comment by atishgoswami** [comment]
@ktomk I don't have cache enabled in my development environment.

**Comment by tkn98** [comment]
Can you just for clarity add as well the expected result? I guess it's 

    +------------------------------------------------+------+----+----+----+----+
    | Job                                            | m    | h  | D  | M  | WD |
    +------------------------------------------------+------+----+----+----+----+
    | foo_bar_cron                                   |  0   | 0  | *   | *  | 1   |
    +------------------------------------------------+------+----+----+----+----+

so that magento merges XML + config paths, correct?

**Comment by atishgoswami** [comment]
@tkn98 Exactly !!

**Comment by tkn98** [comment]
The fix is now part of the development version. Please update to the non-stable variant and report back if it fixed/didn't fix your issue. Thanks!

**Comment by atishgoswami** [comment]
@tkn98 Sure will test it out. Thanks for the update

**Comment by ktomk** [comment]
No feedback provided, I assume in good faith that it is fixed.

**Comment by atishgoswami** [comment]
Hello,

Sorry for the late reply got a it little distracted with other things.

Yes the fix seems to be working !!!

Thanks @robbieaverill and @tkn98

**Comment by ktomk** [comment]
@atishgoswami; No problem at all, I just closed the ticket for workflow reasons and just wanted to show that I already *assumed* it does the job for you. In case it would have not, there is no problem to re-open it and further look into it. Thanks for your report and the overall feedback even you're distracted atm. So thank you as well!
