### ISSUE TITLE
n98 dev:console - PHP Fatal error:  Class 'Mage' not found in eval()'d code on line 1

### ISSUE THREAD

**Issue by razbakov** [netz98/n98-magerun#728]
I call dev-console:
```
$ n98 dev:console
```

And `Mage` class not found:

```
Magento is not initialized.
At the prompt, type help for some help.

To exit the shell, type ^D.
Psy Shell v0.4.4 (PHP 5.5.30 — cli) by Justin Hileman
>>> Mage::getModel('catalog/product');
PHP Fatal error:  Class 'Mage' not found in eval()'d code on line 1
```

**Comment by razbakov** [comment]
I called it not from magento webroot

**Comment by ktomk** [comment]
Do you know that you can hint the magento webroot in a project with the [`.n98-magerun` stop-file](http://magerun.net/released-n98-magerun-version-1-95-0/)? I don't know your concrete use-case but this might be helpful.

**Comment by cmuench** [comment]
@razbakov You can alternatively set the webroot with --root-dir option.

**Comment by razbakov** [comment]
@ktomk @cmuench i didn't know it! Thank you for info!

**Comment by ktomk** [comment]
@razbakov you're welcome.
