### ISSUE TITLE
ConfigurationLoader->loadDistConfig should not be passing file path to Yaml::parse

### ISSUE THREAD

**Issue by danemacmillan** [netz98/n98-magerun#729]
The `ConfigurationLoader` class' `loadDistConfig` method passes the `config.yaml` file path instead of its file contents. From Symfony 3 onward, that ability will be removed:

```
Deprecated: The ability to pass file names to the Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead. in /vendor/symfony/yaml/Yaml.php on line 55
```

The method:
```php
    protected function loadDistConfig($initConfig)
    {
        if ($this->_distConfig == null) {
            $this->_distConfig = Yaml::parse(__DIR__ . '/../../../../config.yaml');

            if (OutputInterface::VERBOSITY_DEBUG <= $this->_output->getVerbosity()) {
                $this->_output->writeln('<debug>Load dist config</debug>');
            }
        }

        $config = ArrayFunctions::mergeArrays($this->_distConfig, $initConfig);

        return $config;
    }
```

**Comment by ktomk** [comment]
Thank you for the report, I'll assign this to me if you've got no objections.

**Comment by danemacmillan** [comment]
@ktomk I just submitted a PR. After looking through the file, I realize there are many other calls to `YAML::parse`, so I can leave that. It might be good to create another ticket to specifically target this codebase-wide update.

**Comment by ktomk** [comment]
@danemacmillan: Good to see you on it! I just quickly looked into the code my own, will take a look on your PR now.

Do you see these warnings in logs or somewhere? I ask because I'd like to know if it's a bummer (or how much of a bummer).

Are that many places? Why not fix them all with this round?

**Comment by danemacmillan** [comment]
@ktomk I typically write code with `xdebug.scream` on, which forcefully shows all warnings, errors, and exceptions. I got that when running N98.

I can do the whole codebase, but not this afternoon. I just caught this while developing something else that uses N98.

**Comment by ktomk** [comment]
@danemacmillan: I just checked, it's only another change in the same file. I'll take your PR in an ammend it.

**Comment by danemacmillan** [comment]
:+1:

**Comment by ktomk** [comment]
I've fixed it in the develop branch. You shouldn't see these triggered errors any longer when you update to the unstable version. Just let me know if you've got any further issues with this.
