### ISSUE TITLE
Configure Magento default Path and project aliases

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#73]
- Allow for configuration of the default magento path.

Example: If I have a project 

   webroot/ <--- here is the magento root
   someotherstuff

And call n98-magerun in the root folder, the magento path could not be detected.

Solution: Create a .n98-magerun.yaml and specify the path webroot/ as a root.
For this to work, we would have to search the magerun config also in the current directory (not only in app/etc/)
- Allow specifing the magento path manually

n98-magerun.phar --dir /my/path/to/magento
- Allow for magento-path aliases

In addition, allow configuration of aliases, such as foo-project

n98-magerun.phar --dir foo-project

In addition we could now also add a nice "cd" command

n98-magerun.phar cd foo-project

**Comment by cmuench** [comment]
@goosehub If you change the working directory to your shop installation the root directory should automatically be detected.

Another solution is a Bash alias.

```
alias magerun-myproject="n98-magerun.phar --root-dir <path>"
```

**Comment by ktomk** [comment]
And/Or make use of the [stop file feature (comment)](https://github.com/netz98/n98-magerun/issues/444#issuecomment-72317981).

**Comment by goosehub** [comment]
@cmuench I like the bash alias solution. Much better than changing the location of our Magento installation, our build system, and our modman setup.

@ktomk I read that, and I'm familiar with yaml, but it's not clear what the contents of the yaml should be for me to accomplish no longer needed to specify --root-dir?

Is any of this documented in the README or help or list command? If not, should it be? I imagine others must have non webroot Magento installations as well.

**Comment by ktomk** [comment]
@goosehub: It's not a YAML file (which is configuration) but a file which contains the path to the magento folder (relative to the file itself) named `.n98-magerun`. That is the so called *stop-file* (Magerun stops looking for the path and takes that one in that file).
