### ISSUE TITLE
DB:console unknown variable

### ISSUE THREAD

**Issue by robinero** [netz98/n98-magerun#732]
The command db:console doesn't seem to work with Mysql 5.7.9 (at least this is what we're running), it'll output an error:
mysql: [ERROR] unknown variable 'pass='.

This is caused by ec1000a1832360ed2f92dfe91c766ea8f4324dd2 which changes the -p parameter to --pass in DatabaseHelper.php.

Connecting with Mysql 5.6 doesn't seem to mind the --pass.

Anyone else getting this error?

**Comment by tkn98** [comment]
Thanks for reporting this issue. I have not yet run into this, but you're absolutely correct, the long switch must be named `--password` and not `--pass`.

**Comment by tkn98** [comment]
@robinero: I've created a fix for the issue. The unstable version has been updated. Please try it and see if the problem still exists with it or not. I'd say it should be solved, just let me know.

**Comment by robinero** [comment]
@tkn98 I ran a test with the latest development version of Magerun on server with Mysql 5.7.9 and it works, thanks!

**Comment by ktomk** [comment]
Thanks for the test & update. And thanks again for reporting the issue.
