### ISSUE TITLE
Admin store (0) missing in selection list of `dev:template-hints*` commands

### ISSUE THREAD

**Issue by jthln** [netz98/n98-magerun#736]
1.97.7

Passing the store directly as argument still works, e.g.: `n98-magerun dev:template-hints admin`

**Comment by tkn98** [comment]
Missed in interactive list.

**Comment by tkn98** [comment]
`n98-magerun dev:template-hints` and `n98-magerun dev:template-hints-blocks` is fixed now in the development version.

**Comment by gido** [comment]
Hum, it looks like it doesn't work for me.

```php
$store->getId() == \Mage_Core_Model_App::ADMIN_STORE_ID ? 'default' : 'stores'` 
```
on https://github.com/netz98/n98-magerun/blob/develop/src/N98/Magento/Command/AbstractMagentoStoreConfigCommand.php#L134

The scope need to be 'stores' even for admin. No ?

**Comment by ktomk** [comment]
@gido: Thanks for your feedback, could you add a little what you mean when you write that "it doesn't work for" you? What have you tried? What did happen? What did you expect to happen?

`'default'` looks good to me for store ID 0, admin normally operates within it.

**Comment by gido** [comment]
@ktomk I double checked and found my mistake (I've added manually in the DB the config to hide/show template hints for the backend but used the stores scope to do so). It works as expected on a fresh install or if I revert my changes.

Thanks!

**Comment by tkn98** [comment]
@gido Thanks for taking the time to verify this and report back!

So then this is fixed I'd say.
