### ISSUE TITLE
Fatal error Elgentos\Magento\Command\Extension\DisableCommand not found in phar

### ISSUE THREAD

**Issue by sergeifilippov** [netz98/n98-magerun#737]
## System

- **OSX 10.11.1 (15B42)**
- replaced `full path` with `path` to make the errors shorter

```
$ php -i | grep phar
Phar-based phar archives => enabled
Tar-based phar archives => enabled
ZIP-based phar archives => enabled
phar.cache_list => no value => no value
phar.readonly => On => On
phar.require_hash => On => On
```

## Steps to Replicate

```bash
wget http://files.magerun.net/n98-magerun-latest.phar -O n98-magerun.phar
chmod +x ./n98-magerun.phar
```

### php 5.5

When I run
```
/usr/local/Cellar/php55/5.5.30/bin/php ./n98-magerun.phar --version
```

### Output

```php
PHP Fatal error:  Class 'Elgentos\Magento\Command\Extension\DisableCommand' not found in phar:///path/n98-magerun.phar/src/N98/Magento/Application.php on line 326

Fatal error: Class 'Elgentos\Magento\Command\Extension\DisableCommand' not found in phar:///path/n98-magerun.phar/src/N98/Magento/Application.php on line 326
```
### php 5.6

When I run

```
/usr/local/Cellar/php56/5.6.16/bin/php ./n98-magerun.phar
```

### Output

```php
PHP Fatal error:  Class 'Elgentos\Magento\Command\Extension\DisableCommand' not found in phar:///path/n98-magerun.phar/src/N98/Magento/Application.php on line 326
PHP Stack trace:
PHP   1. {main}() /path/n98-magerun.phar:0
PHP   2. N98\Magento\Application->run() /path/n98-magerun.phar:8
PHP   3. N98\Magento\Application->init() phar:///path/n98-magerun.phar/src/N98/Magento/Application.php:651
PHP   4. N98\Magento\Application->registerCustomCommands() phar:///path/n98-magerun.phar/src/N98/Magento/Application.php:707

Fatal error: Class 'Elgentos\Magento\Command\Extension\DisableCommand' not found in phar:///path/n98-magerun.phar/src/N98/Magento/Application.php on line 326

Call Stack:
    0.0147    1049392   1. {main}() /path/n98-magerun.phar:0
    0.0290    2500496   2. N98\Magento\Application->run() /path/n98-magerun.phar:8
    0.0334    2839376   3. N98\Magento\Application->init() phar:///path/n98-magerun.phar/src/N98/Magento/Application.php:651
    0.1338    4218736   4. N98\Magento\Application->registerCustomCommands() phar:///path/n98-magerun.phar/src/N98/Magento/Application.php:707
```

Any ideas?

**Comment by tkn98** [comment]
Please check if you have APC enabled in CLI and if yes, disable it with the invocation:

    php <php-switches> -f ./n98-magerun.phar -- <magerun-switches>

E.g.:

    /usr/local/Cellar/php56/5.6.16/bin/php -d apc.enable_cli=0 -f ./n98-magerun.phar --

If APC related, the canonical issue for that is: #153

**Comment by sergeifilippov** [comment]
`php -i | grep apc` yielded nothing so assumedly no APC installed.

```
$ /usr/local/Cellar/php56/5.6.16/bin/php -d apc.enable_cli=0 -f ~/bin/n98-magerun.phar --
```

```php
PHP Fatal error:  Class 'Elgentos\Magento\Command\Extension\DisableCommand' not found in phar:///home/bin/n98-magerun.phar/src/N98/Magento/Application.php on line 326
PHP Stack trace:
PHP   1. {main}() /home/bin/n98-magerun.phar:0
PHP   2. N98\Magento\Application->run() /home/bin/n98-magerun.phar:8
PHP   3. N98\Magento\Application->init() phar:///home/bin/n98-magerun.phar/src/N98/Magento/Application.php:651
PHP   4. N98\Magento\Application->registerCustomCommands() phar:///Users/filips01/bin/n98-magerun.phar/src/N98/Magento/Application.php:707

Fatal error: Class 'Elgentos\Magento\Command\Extension\DisableCommand' not found in phar:///home/bin/n98-magerun.phar/src/N98/Magento/Application.php on line 326

Call Stack:
    0.0146    1049392   1. {main}() /home/bin/n98-magerun.phar:0
    0.0346    2496344   2. N98\Magento\Application->run() /home/bin/n98-magerun.phar:8
    0.0377    2833936   3. N98\Magento\Application->init() phar:///home/bin/n98-magerun.phar/src/N98/Magento/Application.php:651
    0.1357    4209696   4. N98\Magento\Application->registerCustomCommands() phar:///home/bin/n98-magerun.phar/src/N98/Magento/Application.php:707
```

## Opcache

I do have opcache installed but it's disabled

```
[opcache]
zend_extension="/usr/local/opt/php55-opcache/opcache.so"

; OPcache On/Off switch. When set to Off, code is not optimized.
; (default "1")
opcache.enable = 0

; Enables the OPcache for the CLI version of PHP.
; It's mostly for testing and debugging.
; (default "0")
opcache.enable_cli = 0
```

**Comment by tkn98** [comment]
The problem would not be with opcache, just with APC, but thanks for the foresight.

When I look in the backtrace in your report, this popped into my eye:

- The phar file is first invoked in `/Users/filips01/bin/n98-magerun.phar`

- However it is used another phar file in `/home/bin/n98-magerun.phar`.

I don't understand *why* this happens however the fact alone I think is problematic. Magerun is designed for a single phar file AFAIK.

**Comment by sergeifilippov** [comment]
Oh right, yeah don't worry about the path. I must have missed that one. I replace the path with a shorter work to make it shorter so it's easier to read. I have my `$PATH` set to check `~/bin` first before heading to `/usr/local/bin`.

**Comment by tkn98** [comment]
Okay, have you obtained the phar file recentely? If you still remember, how?

I wonder because I can't yet reproduce.

It's located in `registerCustomCommands()` methods, probably we don't report well on inconsistencies in the file-system database.

**Comment by hostep** [comment]
@sergeifilippov: can you check these [directories](https://github.com/netz98/n98-magerun/wiki/Modules#where-can-modules-be-placed) to see if you have some extra modules installed? It looks like you might have an older version of the [magerun-addons](https://github.com/peterjaap/magerun-addons) module which causes problems?

**Comment by sergeifilippov** [comment]
Thank you @hostep !

This is exactly it. I had an out of date module `media-sync`. `git pull` on the module fixed it.

:+1:

**Comment by tkn98** [comment]
I think the error message could be better also the error case should be checked for and not bail out with a fatal. Thanks for the detailed report and all the feedback.

**Comment by sergeifilippov** [comment]
No worries. Love this tool. Thank you for making it and looking after it.
