### ISSUE TITLE
[PDOException]                                                                  SQLSTATE[HY000] [2002] No connection could be made because the target machi     ne actively refused it.

### ISSUE THREAD

**Issue by makwanaajay** [netz98/n98-magerun#740]
I have installed the magerun in phpstorm. But it is not working with any command. When I am trying to run command, it generates the error below.

[PDOException] SQLSTATE[HY000] [2002] No connection could be made because the target machi     ne actively refused it.

Please provide me the solution.

**Comment by ktomk** [comment]
Thank you for reporting an issue with magerun. For better feedback, please run the command you've got the error message with the `-vvv` (verbose) switch. This will add more information to the output. 

Then please add the whole command-line you execute as well as the complete verbose output  to this issue. Thank you.

**Comment by makwanaajay** [comment]
Hello
I have got the below message.

php.exe D:\ajay\ajay\Software\n98-magerun-latest.phar customer:list -vvv
Load dist config
Search for Magento in folder Y:\corporate11
Found Magento in folder Y:\corporate11
DEBUG                                                                               
  [Zend_Db_Adapter_Exception]                                                  
  SQLSTATE[HY000] [2002] No connection could be made because the target machi  
  ne actively refused it.   

Exception trace:
 () at Y:\corporate11\lib\Zend\Db\Adapter\Pdo\Abstract.php:144
 Zend_Db_Adapter_Pdo_Abstract->_connect() at Y:\corporate11\lib\Zend\Db\Adapter\Pdo\Mysql.php:111
 Zend_Db_Adapter_Pdo_Mysql->_connect() at Y:\corporate11\lib\Varien\Db\Adapter\Pdo\Mysql.php:320
 Varien_Db_Adapter_Pdo_Mysql->_connect() at Y:\corporate11\lib\Zend\Db\Adapter\Abstract.php:460
 Zend_Db_Adapter_Abstract->query() at Y:\corporate11\lib\Zend\Db\Adapter\Pdo\Abstract.php:238
 Zend_Db_Adapter_Pdo_Abstract->query() at Y:\corporate11\lib\Varien\Db\Adapter\Pdo\Mysql.php:428
 Varien_Db_Adapter_Pdo_Mysql->query() at Y:\corporate11\app\code\core\Mage\Core\Model\Resource.php:179
 Mage_Core_Model_Resource->_newConnection() at Y:\corporate11\app\code\core\Mage\Core\Model\Resource.php:110
 Mage_Core_Model_Resource->getConnection() at Y:\corporate11\app\code\core\Mage\Core\Model\Resource\Db\Abstract.php:320
 Mage_Core_Model_Resource_Db_Abstract->_getConnection() at Y:\corporate11\app\code\core\Mage\Core\Model\Resource\Db\Abstract.php:350
 Mage_Core_Model_Resource_Db_Abstract->_getWriteAdapter() at Y:\corporate11\app\code\core\Mage\Core\Model\Resource\Db\Abstract.php:335
 Mage_Core_Model_Resource_Db_Abstract->_getReadAdapter() at Y:\corporate11\app\code\core\Mage\Core\Model\Resource\Cache.php:53
 Mage_Core_Model_Resource_Cache->getAllOptions() at Y:\corporate11\app\code\core\Mage\Core\Model\Cache.php:478
 Mage_Core_Model_Cache->_initOptions() at Y:\corporate11\app\code\core\Mage\Core\Model\Cache.php:520
 Mage_Core_Model_Cache->canUse() at Y:\corporate11\app\code\core\Mage\Core\Model\App.php:1183
 Mage_Core_Model_App->useCache() at Y:\corporate11\app\code\core\Mage\Core\Model\Config.php:414
 Mage_Core_Model_Config->_canUseCacheForInit() at Y:\corporate11\app\code\core\Mage\Core\Model\Config.php:294
 Mage_Core_Model_Config->loadModulesCache() at Y:\corporate11\app\code\core\Mage\Core\Model\Config.php:255
 Mage_Core_Model_Config->init() at Y:\corporate11\app\code\core\Mage\Core\Model\App.php:270
 Mage_Core_Model_App->init() at Y:\corporate11\app\Mage.php:616
 Mage::app() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/src/N98/Magento/Application.php:793
 N98\Magento\Application->_initMagento1() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/src/N98/Magento/Application.php:474
 N98\Magento\Application->initMagento() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:157
 N98\Magento\Command\AbstractMagentoCommand->initMagento() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/src/N98/Magento/Command/Customer/ListCommand.php:44
 N98\Magento\Command\Customer\ListCommand->execute() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:432
 N98\Magento\Command\AbstractMagentoCommand->run() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/vendor/symfony/console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/src/N98/Magento/Application.php:596
 N98\Magento\Application->doRun() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at phar://D:/ajay/ajay/Software/n98-magerun-latest.phar/src/N98/Magento/Application.php:657
 N98\Magento\Application->run() at D:\ajay\ajay\Software\n98-magerun-latest.phar:8




                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000] [2002] No connection could be made because the target machi  
  ne actively refused it.

**Comment by cmuench** [comment]
@makwanaajay 

This is not a n98-magerun or Magento problem.
Please verify your DB settings.
In the most cases it's a wrong port setting.

If you use localhost you can try to change the host to 127.0.0.1.

To provide a detailed analysis we need more informations about your environment.
Works your shop without n98-magerun? Can you open the homepage of your shop?

**Comment by ktomk** [comment]
@makwanaajay, thanks for providing the details. As @cmuench already commented, this is a problem with your database settings. Check your settings and especially check if you can open Magento in your Webbrowser.

It's not so much a problem with Magerun, albeit the error message could be nicer (which is feature material and not a bug, and has more scope than your error - ref #711).

**Comment by ktomk** [comment]
@makwanaajay: I'll close this ticket now due to lack of feedback. In case this is still an issue or you want to leave other feedback, it's still possible even if closed.

**Comment by tassiocamara** [comment]
Hello. I have a similar problem. How can I resolve this error:

Load dist config phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application/../../../../config.yaml
Search for Magento in folder /Applications/MAMP/htdocs/osc
Found Magento in folder /Applications/MAMP/htdocs/osc
Load dist config cached
Vendor directory phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application/../../../../vendor
Add command  admin:notifications -> N98\Magento\Command\Admin\DisableNotificationsCommand
Add command  admin:user:change-password -> N98\Magento\Command\Admin\User\ChangePasswordCommand
Add command  admin:user:create -> N98\Magento\Command\Admin\User\CreateUserCommand
Add command  admin:user:list -> N98\Magento\Command\Admin\User\ListCommand
Add command  admin:user:delete -> N98\Magento\Command\Admin\User\DeleteUserCommand
Add command  admin:user:change-status -> N98\Magento\Command\Admin\User\ChangeStatusCommand
Add command  admin:user:lock -> N98\Magento\Command\Admin\User\LockCommand
Add command  admin:user:lockdown -> N98\Magento\Command\Admin\User\LockdownCommand
Add command  admin:user:unlock -> N98\Magento\Command\Admin\User\UnlockCommand
Add command  cache:clean -> N98\Magento\Command\Cache\CleanCommand
Add command  cache:dir:flush -> N98\Magento\Command\Cache\Dir\FlushCommand
Add command  cache:disable -> N98\Magento\Command\Cache\DisableCommand
Add command  cache:enable -> N98\Magento\Command\Cache\EnableCommand
Add command  cache:flush -> N98\Magento\Command\Cache\FlushCommand
Add command  cache:list -> N98\Magento\Command\Cache\ListCommand
Add command  cache:report -> N98\Magento\Command\Cache\ReportCommand
Add command  cache:view -> N98\Magento\Command\Cache\ViewCommand
Add command  category:create:dummy -> N98\Magento\Command\Category\Create\DummyCommand
Add command  cms:banner:toggle -> N98\Magento\Command\Cms\Banner\ToggleCommand
Add command  cms:block:list -> N98\Magento\Command\Cms\Block\ListCommand
Add command  cms:block:toggle -> N98\Magento\Command\Cms\Block\ToggleCommand
Add command  cms:page:publish -> N98\Magento\Command\Cms\Page\PublishCommand
Add command  config:delete -> N98\Magento\Command\Config\DeleteCommand
Add command  config:dump -> N98\Magento\Command\Config\DumpCommand
Add command  config:get -> N98\Magento\Command\Config\GetCommand
Add command  config:set -> N98\Magento\Command\Config\SetCommand
Add command  config:search -> N98\Magento\Command\Config\SearchCommand
Add command  customer:change-password -> N98\Magento\Command\Customer\ChangePasswordCommand
Add command  customer:create -> N98\Magento\Command\Customer\CreateCommand
Add command  customer:create:dummy -> N98\Magento\Command\Customer\CreateDummyCommand
Add command  customer:info -> N98\Magento\Command\Customer\InfoCommand
Add command  customer:list -> N98\Magento\Command\Customer\ListCommand
Add command  customer:delete -> N98\Magento\Command\Customer\DeleteCommand
Add command  db:console -> N98\Magento\Command\Database\ConsoleCommand
Add command  db:create -> N98\Magento\Command\Database\CreateCommand
Add command  db:drop -> N98\Magento\Command\Database\DropCommand
Add command  db:dump -> N98\Magento\Command\Database\DumpCommand
Add command  db:import -> N98\Magento\Command\Database\ImportCommand
Add command  db:info -> N98\Magento\Command\Database\InfoCommand
Add command  db:query -> N98\Magento\Command\Database\QueryCommand
Add command  db:variables -> N98\Magento\Command\Database\VariablesCommand
Add command  db:status -> N98\Magento\Command\Database\StatusCommand
Add command  db:maintain:check-tables -> N98\Magento\Command\Database\Maintain\CheckTablesCommand
Add command  design:demo-notice -> N98\Magento\Command\Design\DemoNoticeCommand
Add command  dev:code:model:method -> N98\Magento\Command\Developer\Code\Model\MethodCommand
Add command  dev:email-template:usage -> N98\Magento\Command\Developer\EmailTemplate\UsageCommand
Add command  dev:ide:phpstorm:meta -> N98\Magento\Command\Developer\Ide\PhpStorm\MetaCommand
Add command  dev:setup:script:attribute -> N98\Magento\Command\Developer\Setup\Script\AttributeCommand
Add command  dev:console -> N98\Magento\Command\Developer\ConsoleCommand
Add command  dev:log:db -> N98\Magento\Command\Developer\Log\DbCommand
Add command  dev:log -> N98\Magento\Command\Developer\Log\LogCommand
Add command  dev:log:size -> N98\Magento\Command\Developer\Log\SizeCommand
Add command  dev:module:create -> N98\Magento\Command\Developer\Module\CreateCommand
Add command  dev:module:disable -> N98\Magento\Command\Developer\Module\Disableenable\DisableCommand
Add command  dev:module:enable -> N98\Magento\Command\Developer\Module\Disableenable\EnableCommand
Add command  dev:module:update -> N98\Magento\Command\Developer\Module\UpdateCommand
Add command  dev:module:list -> N98\Magento\Command\Developer\Module\ListCommand
Add command  dev:module:observer:list -> N98\Magento\Command\Developer\Module\Observer\ListCommand
Add command  dev:module:rewrite:conflicts -> N98\Magento\Command\Developer\Module\Rewrite\ConflictsCommand
Add command  dev:module:rewrite:list -> N98\Magento\Command\Developer\Module\Rewrite\ListCommand
Add command  dev:module:dependencies:on -> N98\Magento\Command\Developer\Module\Dependencies\OnCommand
Add command  dev:module:dependencies:from -> N98\Magento\Command\Developer\Module\Dependencies\FromCommand
Add command  dev:profiler -> N98\Magento\Command\Developer\ProfilerCommand
Add command  dev:report:count -> N98\Magento\Command\Developer\Report\CountCommand
Add command  dev:class:lookup -> N98\Magento\Command\Developer\ClassLookupCommand
Add command  dev:symlinks -> N98\Magento\Command\Developer\SymlinksCommand
Add command  dev:merge-css -> N98\Magento\Command\Developer\MergeCssCommand
Add command  dev:merge-js -> N98\Magento\Command\Developer\MergeJsCommand
Add command  dev:template-hints-blocks -> N98\Magento\Command\Developer\TemplateHintsBlocksCommand
Add command  dev:template-hints -> N98\Magento\Command\Developer\TemplateHintsCommand
Add command  dev:theme:duplicates -> N98\Magento\Command\Developer\Theme\DuplicatesCommand
Add command  dev:theme:list -> N98\Magento\Command\Developer\Theme\ListCommand
Add command  dev:theme:info -> N98\Magento\Command\Developer\Theme\InfoCommand
Add command  dev:translate:admin -> N98\Magento\Command\Developer\Translate\InlineAdminCommand
Add command  dev:translate:shop -> N98\Magento\Command\Developer\Translate\InlineShopCommand
Add command  dev:translate:set -> N98\Magento\Command\Developer\Translate\SetCommand
Add command  dev:translate:export -> N98\Magento\Command\Developer\Translate\ExportCommand
Add command  eav:attribute:create-dummy-values -> N98\Magento\Command\Eav\Attribute\Create\DummyCommand
Add command  eav:attribute:list -> N98\Magento\Command\Eav\Attribute\ListCommand
Add command  eav:attribute:remove -> N98\Magento\Command\Eav\Attribute\RemoveCommand
Add command  eav:attribute:view -> N98\Magento\Command\Eav\Attribute\ViewCommand
Add command  giftcard:create -> N98\Magento\Command\GiftCard\CreateCommand
Add command  giftcard:info -> N98\Magento\Command\GiftCard\InfoCommand
Add command  giftcard:remove -> N98\Magento\Command\GiftCard\RemoveCommand
Add command  giftcard:pool:generate -> N98\Magento\Command\GiftCard\Pool\GenerateCommand
Add command  index:list -> N98\Magento\Command\Indexer\ListCommand
Add command  index:list:mview -> N98\Magento\Command\Indexer\ListMviewCommand
Add command  index:reindex:all -> N98\Magento\Command\Indexer\ReindexAllCommand
Add command  index:reindex:mview -> N98\Magento\Command\Indexer\ReindexMviewCommand
Add command  index:reindex -> N98\Magento\Command\Indexer\ReindexCommand
Add command  install -> N98\Magento\Command\Installer\InstallCommand
Add command  uninstall -> N98\Magento\Command\Installer\UninstallCommand
Add command  local-config:generate -> N98\Magento\Command\LocalConfig\GenerateCommand
Add command  extension:download -> N98\Magento\Command\MagentoConnect\DownloadExtensionCommand
Add command  extension:install -> N98\Magento\Command\MagentoConnect\InstallExtensionCommand
Add command  extension:list -> N98\Magento\Command\MagentoConnect\ListExtensionsCommand
Add command  extension:upgrade -> N98\Magento\Command\MagentoConnect\UpgradeExtensionCommand
Add command  extension:validate -> N98\Magento\Command\MagentoConnect\ValidateExtensionCommand
Add command  media:cache:image:clear -> N98\Magento\Command\Media\Cache\Image\ClearCommand
Add command  media:cache:jscss:clear -> N98\Magento\Command\Media\Cache\JsCss\ClearCommand
Add command  media:dump -> N98\Magento\Command\Media\DumpCommand
Add command  open-browser -> N98\Magento\Command\OpenBrowserCommand
Add command  script -> N98\Magento\Command\ScriptCommand
Add command  script:repo:list -> N98\Magento\Command\Script\Repository\ListCommand
Add command  script:repo:run -> N98\Magento\Command\Script\Repository\RunCommand
Add command  self-update -> N98\Magento\Command\SelfUpdateCommand
Add command  shell -> N98\Magento\Command\ShellCommand
Add command  sys:check -> N98\Magento\Command\System\CheckCommand
Add command  sys:cron:history -> N98\Magento\Command\System\Cron\HistoryCommand
Add command  sys:cron:list -> N98\Magento\Command\System\Cron\ListCommand
Add command  sys:cron:run -> N98\Magento\Command\System\Cron\RunCommand
Add command  sys:info -> N98\Magento\Command\System\InfoCommand
Add command  sys:maintenance -> N98\Magento\Command\System\MaintenanceCommand
Add command  sys:setup:compare-versions -> N98\Magento\Command\System\Setup\CompareVersionsCommand
Add command  sys:setup:change-version -> N98\Magento\Command\System\Setup\ChangeVersionCommand
Add command  sys:setup:remove -> N98\Magento\Command\System\Setup\RemoveCommand
Add command  sys:setup:run -> N98\Magento\Command\System\Setup\RunCommand
Add command  sys:setup:incremental -> N98\Magento\Command\System\Setup\IncrementalCommand
Add command  sys:store:config:base-url:list -> N98\Magento\Command\System\Store\Config\BaseUrlListCommand
Add command  sys:store:list -> N98\Magento\Command\System\Store\ListCommand
Add command  sys:url:list -> N98\Magento\Command\System\Url\ListCommand
Add command  sys:website:list -> N98\Magento\Command\System\Website\ListCommand
Add command  composer:init -> Composer\Command\InitCommand
Add command  composer:install -> Composer\Command\InstallCommand
Add command  composer:require -> Composer\Command\RequireCommand
Add command  composer:update -> Composer\Command\UpdateCommand
Add command  composer:validate -> Composer\Command\ValidateCommand
Add command  composer:search -> Composer\Command\SearchCommand
Add command  composer:diagnose -> Composer\Command\DiagnoseCommand

                              
  Magento System Information  
                              


                                                    
  [Zend_Db_Adapter_Exception]                       
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

Exception trace:
 () at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Pdo/Abstract.php:144
 Zend_Db_Adapter_Pdo_Abstract->_connect() at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Pdo/Mysql.php:111
 Zend_Db_Adapter_Pdo_Mysql->_connect() at /Applications/MAMP/htdocs/osc/lib/Varien/Db/Adapter/Pdo/Mysql.php:396
 Varien_Db_Adapter_Pdo_Mysql->_connect() at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Abstract.php:460
 Zend_Db_Adapter_Abstract->query() at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Pdo/Abstract.php:238
 Zend_Db_Adapter_Pdo_Abstract->query() at /Applications/MAMP/htdocs/osc/lib/Varien/Db/Adapter/Pdo/Mysql.php:504
 Varien_Db_Adapter_Pdo_Mysql->query() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource.php:179
 Mage_Core_Model_Resource->_newConnection() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource.php:110
 Mage_Core_Model_Resource->getConnection() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php:320
 Mage_Core_Model_Resource_Db_Abstract->_getConnection() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php:350
 Mage_Core_Model_Resource_Db_Abstract->_getWriteAdapter() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php:335
 Mage_Core_Model_Resource_Db_Abstract->_getReadAdapter() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource/Config.php:55
 Mage_Core_Model_Resource_Config->loadToXml() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Config.php:357
 Mage_Core_Model_Config->loadDb() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Config.php:263
 Mage_Core_Model_Config->init() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/App.php:277
 Mage_Core_Model_App->init() at /Applications/MAMP/htdocs/osc/app/Mage.php:616
 Mage::app() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:791
 N98\Magento\Application->_initMagento1() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:475
 N98\Magento\Application->initMagento() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:155
 N98\Magento\Command\AbstractMagentoCommand->initMagento() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/System/InfoCommand.php:60
 N98\Magento\Command\System\InfoCommand->execute() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:473
 N98\Magento\Command\AbstractMagentoCommand->run() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:868
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:191
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:610
 N98\Magento\Application->doRun() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:642
 N98\Magento\Application->run() at /usr/local/bin/n98-magerun.phar:22

                                                    
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

Exception trace:
 () at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Pdo/Abstract.php:128
 PDO->__construct() at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Pdo/Abstract.php:128
 Zend_Db_Adapter_Pdo_Abstract->_connect() at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Pdo/Mysql.php:111
 Zend_Db_Adapter_Pdo_Mysql->_connect() at /Applications/MAMP/htdocs/osc/lib/Varien/Db/Adapter/Pdo/Mysql.php:396
 Varien_Db_Adapter_Pdo_Mysql->_connect() at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Abstract.php:460
 Zend_Db_Adapter_Abstract->query() at /Applications/MAMP/htdocs/osc/lib/Zend/Db/Adapter/Pdo/Abstract.php:238
 Zend_Db_Adapter_Pdo_Abstract->query() at /Applications/MAMP/htdocs/osc/lib/Varien/Db/Adapter/Pdo/Mysql.php:504
 Varien_Db_Adapter_Pdo_Mysql->query() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource.php:179
 Mage_Core_Model_Resource->_newConnection() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource.php:110
 Mage_Core_Model_Resource->getConnection() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php:320
 Mage_Core_Model_Resource_Db_Abstract->_getConnection() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php:350
 Mage_Core_Model_Resource_Db_Abstract->_getWriteAdapter() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php:335
 Mage_Core_Model_Resource_Db_Abstract->_getReadAdapter() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Resource/Config.php:55
 Mage_Core_Model_Resource_Config->loadToXml() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Config.php:357
 Mage_Core_Model_Config->loadDb() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/Config.php:263
 Mage_Core_Model_Config->init() at /Applications/MAMP/htdocs/osc/app/code/core/Mage/Core/Model/App.php:277
 Mage_Core_Model_App->init() at /Applications/MAMP/htdocs/osc/app/Mage.php:616
 Mage::app() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:791
 N98\Magento\Application->_initMagento1() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:475
 N98\Magento\Application->initMagento() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:155
 N98\Magento\Command\AbstractMagentoCommand->initMagento() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/System/InfoCommand.php:60
 N98\Magento\Command\System\InfoCommand->execute() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:473
 N98\Magento\Command\AbstractMagentoCommand->run() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:868
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:191
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:610
 N98\Magento\Application->doRun() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:642
 N98\Magento\Application->run() at /usr/local/bin/n98-magerun.phar:22

sys:info [--format [FORMAT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--root-dir [ROOT-DIR]] [--skip-config] [--skip-root-check] [--developer-mode] [--] <command> [<key>]

**Comment by cmuench** [comment]
@tassiocamara Please checkout you database credentials in app/etc/local.xml

**Comment by andrespitia** [comment]
hi @cmuench 
I have this error can you help me.
PDOException: Caught PDOException (500): SQLSTATE[HY000] [2002] Connection refused in /var/www/whitelabel/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:128
please

**Comment by cmuench** [comment]
@andrespitia is your shop running with the same 
db credentials?

**Comment by andrespitia** [comment]
@cmuench no, the database is part of the store services

**Comment by cmuench** [comment]
@andrespitia Connection refused is a database error.
Often it's related to the user and host in MySQL.
As one example https://stackoverflow.com/questions/13032270/mysql-connection-refused-when-trying-to-connect-to-localhost-using-remote-ip

I do not see anything here, we can do here in n98-magerun.

**Comment by andrespitia** [comment]
@cmuench I would like to ask you for help with the following error, my database is in Azure, but I don't know exactly what causes this error, could you help me by giving me an idea, what could it be? Thanks a lot.
this happens rarely when i browse my website and it is with magento.


![IMG_20221027_103953 (2)](https://user-images.githubusercontent.com/50963185/198336051-1c81b7da-999c-48be-bad4-206e1db50235.jpg)

**Comment by cmuench** [comment]
@andrespitia IMHO this is not related to n98-magerun. Please check your network/server configuration. I cannot provide support for Microsoft Azure here.
