### ISSUE TITLE
Sys:cron:run all marked with [1]

### ISSUE THREAD

**Issue by cdiacon** [netz98/n98-magerun#745]
When running `sys:cron:run` after v1.97.8 update all the jobs are marked with [1] and none of random values are working 

![screen shot 2016-01-05 at 12 02 54](https://cloud.githubusercontent.com/assets/728734/12114780/8fb65ba6-b3a4-11e5-96a1-802402d70483.png)

**Comment by cmuench** [comment]
Thanks for your bug report. We deployed a bugfix. Please update to v1.97.9.

**Comment by cdiacon** [comment]
amazing support, thanks @cmuench
