### ISSUE TITLE
Dependency on "composer/composer": "1.0.*@dev" fails

### ISSUE THREAD

**Issue by Vinai** [netz98/n98-magerun#746]
Running `composer install` with the following `composer.json` fails:

```json
{
  "require": {
    "n98/magerun":"^1.97"
  }
}
```

The error is:
```
% composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - n98/magerun 1.97.9 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.8 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.7 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.6 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.5 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.4 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.3 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.2 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.1 requires composer/composer 1.0.*@dev -> no matching package found.
    - n98/magerun 1.97.0 requires composer/composer 1.0.*@dev -> no matching package found.
    - Installation request for n98/magerun ^1.97 -> satisfiable by n98/magerun[1.97.0, 1.97.1, 1.97.2, 1.97.3, 1.97.4, 1.97.5, 1.97.6, 1.97.7, 1.97.8, 1.97.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

The latest n98-magerun version with resolvable dependencies is 1.29.0.

Do you have a trick to have the dependency on a later version work?

**Comment by AydinHassan** [comment]
Composer isn't stable so you would need to lower your minimum stability in your composer file. See: https://getcomposer.org/doc/04-schema.md#minimum-stability.

**Comment by Vinai** [comment]
If I set the minimum stability to dev all dependencies get installed in that dependency, but I don't want that.
However, explicitly adding the composer dependency to the root composer.json works:

```json
{
  "require": {
    "n98/magerun":"^1.97",
    "composer/composer":"1.0.*@dev"
  }
}
```

**Comment by AydinHassan** [comment]
Yeah I think you can even omit the version and just have `"composer/composer":"@dev"` so you can leave the version deciding to the actual package which requires it.

**Comment by ktomk** [comment]
Hi @Vinai, I can reproduce the issue and it is new to me. I also check what @AydinHassan wrote and `"composer/composer":"@dev"` works. I'll update the requirements in the package.

**Comment by ktomk** [comment]
Just seeing that we have `1.0.*@dev` for `composer/composer` and that works. So I'm a bit puzzled. I'll just do the version bump with the changes so it can be tried. Can't see a different way to do it for the moment.

**Comment by AydinHassan** [comment]
You probably want `^1.0@alpha`. There are no `1.*` dev releases, only alpha which is why `composer/composer:1.0.0@dev` fails . When you specify `@dev` it just defaults to the master branch.

**Comment by Vinai** [comment]
The answer is here: https://getcomposer.org/doc/04-schema.md#package-links

> `require` and `require-dev` additionally support stability flags (root-only)

So the `@dev` version flag can only be used in a root `composer.json` file, not in a library that is a dependency. If possible, please change that requirement in the n98/magerun package so other packages can depend on it.

**Comment by AydinHassan** [comment]
@Vinai There are no stable releases of Composer so a library cannot depend on it without the root package explicitly allowing it until a stable version of composer is tagged.

**Comment by Vinai** [comment]
The dependency could be on `dev-master`.

**Comment by ktomk** [comment]
Yes, I'm trying with dev-master right now. I'm just seeing that this breaks some version compatibilities, so I'll do this somewhat conservative: `dev-master#9f6fdfd` which is this commit https://github.com/composer/composer/commit/9f6fdfd703f433bd0777fd89fb4684908a6c4f06 - Just one I had at hand here.

**Comment by AydinHassan** [comment]
You would still need to specify `@dev` in your root project as `dev-master` and specific commit hashes are treated as dev stability

**Comment by ktomk** [comment]
Okay, just tried it with a new magerun 1 package 1.97.10 and as @AydinHassan  writes, this still can not be satisfied as it's dev:

	$ composer install
	Loading composer repositories with package information
	Installing dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
		- n98/magerun 1.97.9 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.8 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.7 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.6 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.5 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.4 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.3 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.2 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.10 requires composer/composer dev-master#9f6fdfd703f433bd0777fd89fb4684908a6c4f06 -> no matching package found.
		- n98/magerun 1.97.1 requires composer/composer 1.0.*@dev -> no matching package found.
		- n98/magerun 1.97.0 requires composer/composer 1.0.*@dev -> no matching package found.
		- Installation request for n98/magerun ^1.97 -> satisfiable by n98/magerun[1.97.0, 1.97.1, 1.97.10, 1.97.2, 1.97.3, 1.97.4, 1.97.5, 1.97.6, 1.97.7, 1.97.8, 1.97.9].

	Potential causes:
	 - A typo in the package name
	 - The package is not available in a stable-enough version according to your minimum-stability setting
	   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

	Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

The only way I can get it to work is to change the composer.json given to:

	{
		"require": {
			"n98/magerun": "^1.97"
		},
		"minimum-stability": "dev"
	}

@Vinai: Would that be an option for you?

**Comment by Vinai** [comment]
Yes it is. Thank you

**Comment by ktomk** [comment]
Okay, case closed. Next release will have the requirement again as before.

**Comment by ktomk** [comment]
@Vinai: Looks like that the next stable Magerun will have reqs on stable composer. This should make the workaround unnecessary. Ref: b8241ceaf3b646fe2906d335409cc95915f22581

**Comment by ktomk** [comment]
Works now for require n98/magerun ^1.97
