### ISSUE TITLE
Cannot verify raw.github.com’s certificate

### ISSUE THREAD

**Issue by astorm** [netz98/n98-magerun#75]
When attempting to install the extension using the `wget` method mentioned in the readme, the process fails with the following error

```
$ wget https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar
--2013-01-24 18:04:54--  https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar
Resolving raw.github.com (raw.github.com)... 199.27.73.193
Connecting to raw.github.com (raw.github.com)|199.27.73.193|:443... connected.
ERROR: cannot verify raw.github.com’s certificate, issued by “/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance CA-3”:
  Unable to locally verify the issuer’s authority.
ERROR: certificate common name “*.a.ssl.fastly.net” doesn’t match requested host name “raw.github.com”.
To connect to raw.github.com insecurely, use ‘--no-check-certificate’.
```

While this certificate may be out of the projects control, a readme with incorrect information hurts adoption. 

Steps to Reproduce
1. Open up a Terminal Application
2. Enter the command `wget https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar`
3. Press Enter

Expected Result: `n98-magerun.phar` is downloaded 

Actual Results: `wget` complains about certificate, per above

**Comment by deshkanth** [comment]
wget --no-check-certificate https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar

**Comment by cmuench** [comment]
@deshkanth please use the correct phar file.
https://files.magerun.net/n98-magerun-latest.phar
