### ISSUE TITLE
Documentation of Custom Install Commands

### ISSUE THREAD

**Issue by teknology** [netz98/n98-magerun#750]
I'm unable to run custom commands using the .n98-magerun.yaml. I've placed in ~ and in /etc and neither of them work. I do have Magerun in the usr/local/bin folder. 

My file has this in the contents. 

commands:
  N98\Magento\Command\Installer\InstallCommand:
    installation:
      defaults:
        currency: USD
        locale: en_US
        timezone: America/New_York
        use_secure: no
        use_rewrites: yes
        session_save: files
        admin_username: admin
        admin_firstname: Gee
        admin_lastname: Rox
        admin_password: password
        admin_email: defaultemail@example.com

**Comment by ktomk** [comment]
If you higher the verbosity (`-vvv` switch), magerun will tell you if the personal configuration file (from the homedir) was loaded (incl. it's path). Please check with it.

And the format you use for the *personal config file* is wrong. What you have as format is that of the command definitions of a magerun *module config file*. That is wrong in a *personal config file*. It can become correct if you turn it into a module.

**Comment by teknology** [comment]
I'm going by the tutorial on the wiki, it's short and vague.

**Comment by tkn98** [comment]
@teknology: Can you please link the wiki-page you follow? Any kind of feedback on how to improve it si welcome.

**Comment by teknology** [comment]
I was following the info on the main page. A step by step on modifying a simple command like changing the install locale or currency would be helpful.

**Comment by teknology** [comment]
Or, informing of a way to get magerun compiled to install with US locale, currency, and timezone.

**Comment by ktomk** [comment]
@teknology: If you're willing to write down how you did it in a language that serves your needs, I would be happy to review it and try it on at least two systems to give it a review. We then can improve the documentation this way. What do you think?

**Comment by ktomk** [comment]
No traction.
