### ISSUE TITLE
config:set to nothing

### ISSUE THREAD

**Issue by eriksenonline** [netz98/n98-magerun#757]
I have this line and are testing to use magerun in my script.
/usr/local/bin/n98-magerun.phar config:set -n dev/restrict/allow_ips

It is possible to delete config and set config but can I set the value to nothing? In the above line I have IP's in my live server but when I import to my dev server I want nothing in this config field.

Is this possible?

**Comment by tkn98** [comment]
Yes this is possible.

If you mean by *nothing* an empty string,  just use an empty string for the value parameter:

	$ n98-magerun.phar config:set config/example/value ""
	config/example/value => 

It is then set:

	$ n98-magerun.phar config:get config/example/*
	+----------------------+---------+----------+-------+
	| Path                 | Scope   | Scope-ID | Value |
	+----------------------+---------+----------+-------+
	| config/example/value | default | 0        |       |
	+----------------------+---------+----------+-------+

I assume this is the scenario you're looking for. If not, just let me know.

**Comment by eriksenonline** [comment]
Thanks that worked :)
