### ISSUE TITLE
db:import | Display warning when the dump contains a "use" statement

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#770]
This would overwrite another database.

**Comment by ktomk** [comment]
I don't think we'll pre-parse the SQL before piping it to mysql ... . But perhaps you can share a bit more of your thoughts and how that is practically feasible.

**Comment by amenk** [comment]
I did not think to much about the *how* yet. In --optimize it would be easy. When not using --optimize, adding a pre-processing wouldn't be nice. Maybe the SQL could be piped through magerun again and checked.

**Comment by ktomk** [comment]
@amenk I have problems to figure out how an out come would looks like and behave. Can you create a working example?

**Comment by amenk** [comment]
Maybe we could add `--one-database` to the mysql command - but this would not show a warning.

http://stackoverflow.com/questions/37237310/show-a-warning-during-import-when-mysql-dump-contains-use

**Comment by amenk** [comment]
Actually a more useful feature would be to rewrite the use commands to the current database, right?

http://serverfault.com/a/425988/48782

**Comment by ktomk** [comment]
@amenk: When is it actually the case that there is a use statement within the dump. From what I know that does not come out of nothing and must be placed there purposefully. Not that this requirement is entirely theoretical. What's your context for this feature request? Did you broke a database by using a wrong dump and import command sequence? If so, how did this happen.

**Comment by amenk** [comment]
When this came to my mind, I had a database which was exported with `use` statements and  the import did not seem to work properly (cause it was imported to another database)

**Comment by ktomk** [comment]
Magerun just wraps the mysql call here. It's more or less for convenience, if the dump is bad, well that's bad. I don't see we can easily check this and make this interactive.

**Comment by amenk** [comment]
We could add this `sed` line: http://stackoverflow.com/a/37240258/288568 (the good thing is, that we already depend on `sed`

**Comment by ktomk** [comment]
I'm not so sure it's really portable nor if it works with the current one. But please create a PR then we can better say.

**Comment by cmuench** [comment]
@amenk Can this issue be closed?
