### ISSUE TITLE
Make db:dump --human-readable files smaller

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#776]
I added the option to be able to diff SQL dumps and avoid long lines. Unfortunately it makes the dumps also very big and hard to handle.

We might change the option (or introduce a new one) to just split the short insert statements after each new row - so also no extensive optimizations should be necessary during import.

There seems to be a sed script for this already: http://stackoverflow.com/a/19961480/288568

**Comment by ktomk** [comment]
@amenk: Can you provide reference when the option was added (related issue / PR)?

**Comment by amenk** [comment]
It is already merged ... use git blame :D

**Comment by ktomk** [comment]
Sure, but you probably better know what you've talked about than I do :)

**Comment by amenk** [comment]
74db97457b8070e6cd91217c92db2716715e336d

**Comment by ktomk** [comment]
So if that option isn't used, the problem is non-existent, correct?

Or is the problem immanent regardless?

**Comment by amenk** [comment]
Only if the option is used...

I mean t he basic approach behind that was to create SQL dumps that are somehow easily diff-able .. but in practical use, most dumps are to big, to be diffed

**Comment by ktomk** [comment]
Yeah, that's what I think as well. It's pretty limited, and for smaller dumps (where this could make sense), you normally don't need to care for a "slow" important (as it's fast enough). Ok to close for later?
