### ISSUE TITLE
Hiding underlying error condition in #785

### ISSUE THREAD

**Issue by tkn98** [netz98/n98-magerun#786]
Just a quick note that the change 5670cb0d74cbb03241f98f74d868a788d88fb80a (#785) hides the error condition. Both return points in [`Cron\AbstractCronCommand::getSchedule()`](https://github.com/netz98/n98-magerun/blob/5670cb0d74cbb03241f98f74d868a788d88fb80a/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php#L47) allow to return `FALSE` which is unchecked (cause of original error) however signals a problem with that (yet still unfixed) code.

Casting `FALSE` to array btw creates `[FALSE]` which is not semantically wrong operation in the now "fixed" code.

I'd say this needs proper fixing.

/cc @dmaciej: FYI

**Comment by ktomk** [comment]
@dmaciej: Do you have a cron expression that is broken (or shorter than 5 parts) in your case? With the fix you've provided, is there an entry that looks different in the output?

**Comment by ktomk** [comment]
Fixed.
