### ISSUE TITLE
Magerun plugins not loaded anymore

### ISSUE THREAD

**Issue by therouv** [netz98/n98-magerun#799]
In the new version `1.97.15` all custom magerun plugins are not loaded anymore. 

The bug was introduced with commit https://github.com/netz98/n98-magerun/commit/1f0b0edcdf1e9a2ca3a04230ed83975afca2808e#diff-38c7bfd66e260842fd84690f151b29d8L218 where the plugin folders were changed to **n98-magerun2** which seems to be wrong since this repository is magerun for Magento1.

**Comment by ktomk** [comment]
Yes, this was a mistake while streamlining both repos with each other.

Has been addressed in 1.97.16.

Thanks for the report + patch!
