### ISSUE TITLE
If it is going to support with Rest Api or SOAP/XML-RPC, it would be very appreciated.

### ISSUE THREAD

**Issue by yssource** [netz98/n98-magerun#801]
If it is going to support with Rest Api or SOAP/XML-RPC, it would be very appreciated.
Maybe this can be added as feature to magerun?

**Comment by ktomk** [comment]
@yssource: What do you have in mind?

**Comment by ktomk** [comment]
@yssource: I'll close this issue for now as this lacks an example. It's not clear to me what you're asking for.
