### ISSUE TITLE
Script Repository

### ISSUE THREAD

**Issue by xxxludixxx** [netz98/n98-magerun#802]
Hello. I am trying to create a script which will make a db dump of a one magento project and then import it to another one. I am not able to create a directory path variable to define were to create a dump and where to import this db. Can you please give me a syntax of cd command in such script?

**Comment by tkn98** [comment]
I perhaps do not fully grasp what you're trying to do, perhaps writing some pseudo-code would help.

For the *db:dump* command, it's possible to specify the file where to export the database to.

~~~
$ n98-magerun.phar db:dump --help
Usage:
  db:dump [options] [--] [<filename>]

Arguments:
  filename                       Dump filename

...
~~~

This is the beginning of the command-line help of that command, as you can see, there is a parameter called *filename* at the end you can specify the path to the sql-dump-file to.

Is that what you're looking for?

**Comment by ktomk** [comment]
Syntax for db:dump is juse the filename (after all the options). Can't imagine it does not work as it is under test, but I'm eager to learn if you were able to break it so please share. Please provide a concrete command and outline how it does not working

**Comment by xxxludixxx** [comment]
The goal is to create a script which will reset the Magento instance. It should remove all files, remove existing database, dump database from another directory, create new database, import data into newly created database, change urls and so on. I just cant dump db from one Magento instance and import it to another one with one command, not changing the directory. What is more, in pseudo bash script ! cd ./directory does not work at all.

**Comment by tkn98** [comment]
Most likely the working directory is changed but you won't see the change as the shell in wich that is done is closed. Try to use multiple commands in a row.

**Comment by xxxludixxx** [comment]
I actually tried to use multiple command. I even created script consisting of cd commands only however it doesn't seem to be working. Thank you for your help anyways.

**Comment by ktomk** [comment]
As an alternative you can create a bash script and call magerun from it. this will preserve directory changes if you do them in the bash script. this is what I normally do.

**Comment by xxxludixxx** [comment]
Ok thanks. Have you guys ever tried to create a variable which will specify the path to a directory while creating magerun script? When I type a command with a path manually it works perfectly but when I use e.g ${path} in the script and enter it it can't read the path.

**Comment by tkn98** [comment]
I never tried personally, so I can't say. If that's a feature it should normally work, if not please create a new ticket that is soley about a concrete issue with a short example on how to reproduce.
