### ISSUE TITLE
Refactoring to reuse code between magerun, magerun2, conrun, ..

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#806]
* extract N98\Util to composer module

Create new composer module to comprise the reusable parts of the "xRun" tools
* extract \N98\Magento\Application\ConfigurationLoader, work with a variable config file name 

-- I might add more here --

**Comment by amenk** [comment]
See also #494

**Comment by ktomk** [comment]
We're currently looking to streamline code between Magerun 1 and Magerun 2 to identify parts that can be shared. This is similar to what you suggest. How this is technically done is not yet fully tested, as it's currently in the making.

**Comment by amenk** [comment]
Sounds awesome! Is there a branch for this or ticket?

**Comment by ktomk** [comment]
Right now I'm fixing some bugs on the road to it but it will come into develop.

M1 + M2 will also get local test setup, so it's easier to run the whole testsuite on the local box with a quick clone.

**Comment by amenk** [comment]
What is the time frame for this? Anything I could help without duplicating your work? Do you make multiple composer libs?
We want to make a port for typo3 soon... Especially with the DB functionalities.

**Comment by ktomk** [comment]
We currently do it this way: We duplicated the whole project and then over the time we were looking which parts are actually common. Right now some of these common parts become visible (this might be a little different to your needs, but I think you'll get a good share out of it compared to the current status quo).

For these a common location is to be established which allows to share them in a version controlled manner.

It's not necessarily as part of a composer package, but whatever we do, it must be compatible with composer. We're at the point to actually find this out, so if you know how to share a folder across multiple projects, please share your experiences:

* M1
* M2
* shared

M1+2 both use shared as a directory, it will contain a same namespace root as for example the src folder may contain as namespace in M1+2.

**Comment by amenk** [comment]
I think the way to go would be to make composer libs of the components which are useful for other projects (and are shared between MR1 and MR2). Those Util libs and database functions are the most obvious for now.

**Comment by ktomk** [comment]
I think this evolve from the shared folder. When it proves working, it can be turned in a git submodule and then that into a composer package. Next to these three repositories I plan to have a fourth one that is a kind of development stand to put the processes around the forks under version control. This could also help you with your plans.

So far I've extracted in the MR2 repo, a test against MR1 is pending.

Identifying and extracting the common parts is then one of the next steps. Maybe we can also meet sometime face-to-face soon again and discuss this development related topic and how to progress with it.

**Comment by amenk** [comment]
It's not that hard to make a composer package :) Not sure what you mean by a shared folder ... how can this be done on github? Just make a composer package ...

**Comment by tkn98** [comment]
Not saying it's hard, we can turn that shared repo into a composer package, it's actually pretty trivial.

**Comment by ktomk** [comment]
Tests in Magerun 1 still pending, there were some other PRs to process first.

**Comment by tkn98** [comment]
Considering git repo for the shared folder, looks good so far. https://github.com/ingydotnet/git-subrepo

**Comment by amenk** [comment]
Just make a composer module, pleaaaaaase .....

**Comment by tkn98** [comment]
We can't even say if it makes sense, so no, sorry, you won't please me into non-decisions at this point. As written, it's perfectly possible to do so in the future, but I don't see us at the point right now.

So if you were concerned about composer to this point, I'll close for now, we can re-open this.

Shared folder will touch master sometime soon (tm).

**Comment by amenk** [comment]
is it already in master? How can I use it?

**Comment by amenk** [comment]
@tkn98 
Now the next step would be to move more files from the Util folder to shared, right? Do you see any problems with this? I am specially interested in the Database functions. Can/shall I try it and make a PR? 
But I think the gitrepo for the shared folder is still on your private github account, can you migrate it to netz98 ?

As long as we use it as a shared folder, we also can still run the tests integrated to the Mageruns. But I would try myself also to add a composer.json - will not be obstructive, right?

**Comment by amenk** [comment]
When trying to run `bin/n98-magerun` i does not find N98\Util\ArrayFunctions ...

**Comment by ktomk** [comment]
@amenk: Technically not quite right, the next step is to actually initialize the shared folder for git subrepo. For the error you found with the array util and file not found / class not found, that should be fixed prior that. If I find some time I can take a look.

**Comment by amenk** [comment]
I think I found the problem.  Its due to my composer loading.i think I will
remove the composer require..

**Comment by amenk** [comment]
I should work now

[x] build works
[ ] tests almost pass

	There were 2 failures:

	1) N98\Magento\Command\Database\StatusCommandTest::testRounding
	Failed asserting that '"Variable Name",Value,Description
	Innodb_ibuf_segment_size,728.00B,
	Innodb_ibuf_size,"  1.00B",
	Innodb_page_size," 16.00K",
	Ssl_session_cache_size,"  0.00B",
	Tc_log_page_size,"  0.00B",
	' matches PCRE pattern "~Innodb_page_size,[0-9\.]+K,~".

	n98-magerun/tests/N98/Magento/Command/Database/StatusCommandTest.php:68

	2) N98\Magento\Command\Installer\InstallCommandPackageVersionTest::versionListing
	Check order of versions for package "magento-mirror", highter comes first, but got 1.9.3.2 before 1.9.3.2
	Failed asserting that 0 is greater than 0.

	n98-magerun/tests/N98/Magento/Command/Installer/InstallCommandPackageVersionTest.php:75
	n98-magerun/tests/N98/Magento/Command/Installer/InstallCommandPackageVersionTest.php:32

Will see what travis says ...

 ... how can we proceed? I am very interested on getting this in a separate repository soon

Where do you want to host the shared repo? on netz98?
As I want to include the shared repo via composer (you still can use it as submodule): which composer short-name shall we use? n98/util ? n98/magerun-util ? n98/magerun-extract ?
