### ISSUE TITLE
Drop n98 from the name

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#807]
Did you think about dropping n98- from the name and calling the project only "magerun" ?

**Comment by robbieaverill** [comment]
What would be the benefit? If it's for ease of use, you can symlink or rename to `magerun.phar` if needed

**Comment by amenk** [comment]
Easy of use, without the need for renaming ...
And all the great tools do not have a vendor name in it :)

**Comment by ktomk** [comment]
Well Google had the vendor name in it for a long time - until they became Alphabet. :)

Anyway, I don't see this in the priority queue right now. But please try on your own with the renaming I'm sure we can benefit from the practical experience over time.

From a standpoint of style, the marketed name is ***Magerun***, I'm with you to that point.

**Comment by ktomk** [comment]
I have got more feedback on this one, and I have to take care not to only put in my personal taste. Even "we" normally use "magerun" as the short form for n98-magerun it now came to my attention that other choose to just use "n98" for it. Which makes perfect sense, it was just that this was against my own habit. Just leaving this as a note and a small reminder what can possibly go wrong by only using ones own assumptions ... .

**Comment by kevingimbel** [comment]
Just wanting to let you know we at out office usually also use "magerun" when talking about it and only one developer uses it as `n98-magerun.phar` instead of aliasing it to `magerun`. Since the "brand" is Magerun renaming the script would be a good idea IMO.

**Comment by cmuench** [comment]
We don't like to rename the phar file.
It's possible (since years) to rename the phar file (https://github.com/netz98/n98-magerun#download-and-install-phar-file).

**Comment by amenk** [comment]
Let's drop magerun from the name and call it n98 only. And magerun2 n982 :-)
