### ISSUE TITLE
Feature request: admin:user:lock

### ISSUE THREAD

**Issue by robbieaverill** [netz98/n98-magerun#808]
`admin:user:unlock` exists already to "release lock on admin user for one or all users". It may be handy for Magerun to be able to lock individual accounts as well.

I wouldn't suggest being able to lock *all* accounts at once though.

**Comment by tkn98** [comment]
`admin:user:lockdown` ^^

**Comment by robbieaverill** [comment]
@tkn98 how much power do you give people? It may be a powerful yet useful command to have

**Comment by ktomk** [comment]
@robbieaverill: all power to the people :)

**Comment by robbieaverill** [comment]
Merged into develop.
