### ISSUE TITLE
Error when started debug with Zend Debugger

### ISSUE THREAD

**Issue by kesonno** [netz98/n98-magerun#809]
Hi,
I usually debug shell scripts with Zend Debugger and PHPStorm, and I start it with:

```
export QUERY_STRING="start_debug=1&debug_port=10137&debug_host=127.0.0.1&no_remote=1&debug_session_id=10000"
```

but when I do this and launch n98-magerun, it die with this error:

```
PHP Fatal error:  require_once(): Failed opening required 'phar://n98-magerun.phar/src/bootstrap.php' (include_path='.:') in /Users/kesonno/bin/n98-magerun on line 6
```

My PHP version is 5.5.27 built-in on OSX 10.10.5.

Anyone experienced similar behaviour?

**Comment by tkn98** [comment]
@kesonno, what is the magerun version you have?

And also please check this ticket, as if that file would not have been in there, the whole program (even w/o debugger) wuold not even show the `--version`: 

1. #706 Cannot run n98-magerun

2. #707 Magerun should self-test required PHP settings

**Comment by kesonno** [comment]
@tkn98 magerun version is 1.97.17

I've not mentioned that if the debug isn't active (because I disable from shell with `export QUERY_STRING=''` or because I stop listening connection from PHPStorm) magerun work without problems.

**Comment by ktomk** [comment]
Hmm, something is interesting about your error message:

> PHP Fatal error:  require_once(): Failed opening required 'phar://n98-magerun.phar/src/bootstrap.php' (include_path='.:') in **/Users/kesonno/bin/n98-magerun** on line 6

It looks as-if the bin-stub `bin/98-magerun` is invoked and not `n98-magerun.phar`. You should share the complete example that is causing you the issue.

**Comment by kesonno** [comment]
> or you placed it into your users home "bin" directory.

exactly :) and I've renamed it removing the ".phar" extension

> Have you tried building the phar file locally your own? Or just tried the source version?

ever used the phar downloaded from https://files.magerun.net/n98-magerun.phar. I'll try with the source and let you know.

**Comment by ktomk** [comment]
Please try with the source (just clone the repo, you can clone master), then start `bin/n98-magerun` in it, it's the phar-stub (and exactly the file that requires the bootstrap.

Phar download should be fine normally, also with xdebug. I use xdebug, too.

You could also try to upgrade, as 1.97.18 is out, too (`n98-magerun self-update`).

**Comment by ktomk** [comment]
Please set ini setting `phar.readonly=0` and if that does not help, please try the source version. Zend debugger once could not debug code form phar files (I've read).

**Comment by kesonno** [comment]
@tkn98 `phar.readonly=0` does not solved, I'll try with the source asap.

**Comment by ktomk** [comment]
Yes, please give it a try. I don't have zend debugger here to check this in more detail on my own.

**Comment by kesonno** [comment]
Hi @ktomk I can confirm that using the source version magerun works without problems with Zend Debugger.

I can additionally confirm that the issue is related with an old version of Zend Debugger (like the mine) in conjunction with phar files, as described here: http://stackoverflow.com/questions/17616119/require-file-using-phar-stream-does-not-work-within-zendstudio (to verify I just ran composer phar and it failed with similar message).

So I guess we can happily close this issue. Thanks for your support!

**Comment by ktomk** [comment]
@kesonno: I closed it then. Can you say which version of Zend Debugger was flawed in your scenario?

**Comment by kesonno** [comment]
@tkn98 my local version of Zend Debugger is v6.0.0, I've downloaded from Zend website more or less 2 year ago.
