### ISSUE TITLE
scope id 

### ISSUE THREAD

**Issue by nathan333** [netz98/n98-magerun#811]
Hi there, 

I just found something that might be a small issue with config.  In src/N98/Magento/Command/Config/AbstractConfigCommand.php there was a change. Im guessing it was line 117     if (0 >= (int)$scopeId) . I noticed this because I have be trying to run config:set --scope websites --scope-id 0 blah blah, and it was working fine last week but not today (i saw a commit to this file 5 days ago). I also noticed on your readme that the default scope id is 0, however when that is run you get that error.  

Just a heads up!

**Comment by tkn98** [comment]
Hi Nathan, thanks for the report. It is correct that an error is given since a more recent version.

I belief that we should not use zero (0) within the *websites* scope. This is why you see the error. This was left unchecked in previous versions and is now more strict.

If you think this is an error, it would be great you could show a valid example or some other kind of reference that shows how a scope-id of 0 is used within the *websites* scope.

**Comment by rjocoleman** [comment]
I've got the same issue. I was previously using `config:delete 'web/secure/base_url' --scope-id 0 --scope='stores'`.

I have the `base_url`'s set for admin store, scope 0.

This is not a GUI accessible configuration but it works, I do not remember the context around setting it to work this way as it was many years ago, it may well be an abuse of the core scope handling.

The new `config:delete` validation specifically disables this use case. I saw the `--all` switch as a mitigation for this but it doesn't delete _all_ config per #814.

**Comment by nathan333** [comment]
yeah. I work with a few customers and they all have their admin as scope 0. Its a little frustrating as I cannot really change this for them. I have just reverted back to using the older version.

**Comment by rjocoleman** [comment]
I see a few options:

1. #814 (`all` command using default too), this is potentially imprecise for this specific issue. Arguably `all` should do _all_ but that's a separate topic for #814)
2. Less validation.
3. Another flag to force validation to be disregarded - non-default, for those that need it - `config:delete --force --scope-id 0 --scope default`.
4. Out of core custom command to handle this use case with less validation e.g. `config:delete:force --scope-id 0 --scope default`.

I'm happy to whip up any of these options and send the appropriate PR (or create a gist for a custom command).

**Comment by nathan333** [comment]
I don't mind its up to you. I will just continue to use the older version. I only need it for the next couple of weeks

**Comment by ktomk** [comment]
To not lock anybody out I then suggest the variant with the `--force` switch to allow 0 for scope stores and websites.

For a mitigation of `--all` we could even use the path constraint *only* so to ignore scope and scope-id completely with `--force`. Then it would do "as announced".

@rjocoleman: If you could create a PR would be great.

**Comment by rjocoleman** [comment]
@ktomk I've sent a new PR over at #815, I've got a couple of notes about the implementation there. 

> For a mitigation of --all we could even use the path constraint only so to ignore scope and scope-id completely with --force. Then it would do "as announced".

I don't see a way to do this, please let me know if I'm missing it! I've gone with a different solution.

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/Config.php#L1546-L1560

**Comment by ktomk** [comment]
@rjocoleman: That was just for added benefit, if it's not straight forward, not an option for this patch. What you did is fine!

**Comment by eriksenonline** [comment]
@tkn98 
> If you think this is an error, it would be great you could show a valid example or some other kind of reference that shows how a scope-id of 0 is used within the websites scope.

This is what I have done before to change the admin url when I update the database on my dev servers. So if I am not to use scope ID of 0 how do I update the admin custom URL? You have to make a new command for this?

n98-magerun.phar config:set -n --scope="stores" --scope-id="0" web/unsecure/base_url http://admin.domain.dev/
/n98-magerun.phar config:set -n --scope="stores" --scope-id="0" web/secure/base_url https://admin.domain.dev/
n98-magerun.phar config:set -n --scope="default" --scope-id="0" admin/url/custom http://admin.domain.dev/

**Comment by rjocoleman** [comment]
@eriksenonline 

`scope=default` and `scope-id=0` is un-effected. That's a valid and standard combination.

`scope=stores` (or `websites`) and `scope-id=0` are non-standard and now caught by the validation.

**Comment by eriksenonline** [comment]
This line n98-magerun.phar config:set -n --scope="default" --scope-id="0" admin/url/custom http://admin.domain.dev/ vorks fine.

But Without changing theese lines allso  
n98-magerun.phar config:set -n --scope="stores" --scope-id="0" web/unsecure/base_url http://admin.domain.dev/
/n98-magerun.phar config:set -n --scope="stores" --scope-id="0" web/secure/base_url https://admin.domain.dev/  
The admin interface do not work. If I use the magerun version 1.97.10 it works fine.

**Comment by ktomk** [comment]
@eriksenonline:_Config was chaned recently. The non-standard usage will become working again with the new `--force` flag. I didn't think it's that common. The changes were introduced in 1.97.17. The resolution with `--force` flag is scheduled for 1.97.19.

**Comment by rjocoleman** [comment]
e.g. in 1.97.19 `n98-magerun.phar config:set -n --scope="stores" --scope-id="0" --force web/secure/base_url https://admin.domain.dev/`

**Comment by ktomk** [comment]
@eriksenonline: Just a short question in your case: Wouldn't it be possible to set the (un)secure/base_url entries for default scope to change them for the admin store?

**Comment by ktomk** [comment]
1.97.19 has shipped, please update and try again with the --force flag. It now should work to your needs again.
