### ISSUE TITLE
UnexpectedValueException during sample data installation

### ISSUE THREAD

**Issue by ssachtleben** [netz98/n98-magerun#812]
Hey,

we are currently writing an ansible role to install magento test systems on demand. Problem now is that we are running reguarly into this issue:

```
 Downloading: 100%

  - Installing sample-data-1.9.1.0 (1.9.1.0)
    Downloading: 100%

  [UnexpectedValueException]
  The checksum verification of the file failed (downloaded from http://sourceforge.net/projects/mageloads/files/assets/1.9.1.0/magento-sample-data-1.9.1.0.tar.gz)
```

It happens in 1 out of 5 builds. And since we want to install magento 1.7, 1.8 and 1.9 on one server at the same time it's not really stable. We are using the following command:

```
n98-magerun.phar install --dbHost="localhost" --dbUser="{{ name }}" --dbPass="{{ pass }}" --dbName="{{ name }}" --installSampleData=yes --useDefaultConfigParams=yes --magentoVersionByName="magento-mirror-1.9.2.4" --installationFolder="/var/www/{{ name }}" --baseUrl="http://{{ host }}/"
```

Is it possible to fix it somehow?

Best,
Sebastian

**Comment by ktomk** [comment]
That's because the downloads are not stable from Sourceforge.

I see two options:

- Re-try the download. I do this on Travis from time to time.
- [Provide your own packages](https://github.com/netz98/n98-magerun/wiki/Magento-installer#add-own-magento-repositories). Then you can offer downloads from a server that is in your control.

**Comment by tkn98** [comment]
@ssachtleben: Did the suggestions help? Do you know about a reliable dump where we could host some larger files?

**Comment by ssachtleben** [comment]
@ktomk @tkn98 thanks, well I used the sourceforge cause the main download from magento directly is broken.

How to redownload only sample data? It fails and when I try to install magento again the folder already exists. Having a loop with on fail, delete folder and do again sounds not really nice ;)

Sorry no idea about download host.

**Comment by tkn98** [comment]
@ssachtleben: Good question. On Travis, the whole build system is re-created from scratch. So looks like you need a more stable download option ... :/

So perhaps first downloading packages to local system and repeating it as often as necessary, than having packages via `file://` protocol (we use composer internally and composer supports that). Just some quick idea.

**Comment by ktomk** [comment]
Another Idea I have would be to retry the download if it fails. If this issue is regularly, it should be possible to test.

**Comment by ktomk** [comment]
@ssachtleben: Another option is for your recipe perhaps to integrate with [magedownload-cli](https://github.com/steverobbins/magedownload-cli) it operates with magento.com official downloads (and credentials) and integrates with magerun.

**Comment by tkn98** [comment]
@ssachtleben: Were you able to alleviate the problem? If so, please let me know how.

**Comment by cmuench** [comment]
Closed due to invativity. Feel free to re-open if needed.
