### ISSUE TITLE
Install Magento Database

### ISSUE THREAD

**Issue by brandontamm** [netz98/n98-magerun#819]
I have a script that:

1. installs magerun
2. installs composer and then "github.com/magento-hackathon/magento-composer-installer" and downloads the magento app and copies local xml config
3. then installs sample data

I do not want sample data installed - I just want to start with a blank magento database. Is there a way for magerun to install just a blank database? I tried db:create but it just creates a database without any magento structure - any ideas? I want a blank magento enterprise database with just the structure so I can start without any sample data

Here is a snippet of the script:
echo "Overriding Magento Configuration"
cp -v /etc/local.xml /var/www/html/web/app/etc/local.xml
cp -v /etc/fpc.xml /var/www/html/web/app/etc/fpc.xml

echo "Installing Sample Data: Media"
curl -s -L https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/1.9.1.0/compressed-no-mp3-magento-sample-data-1.9.1.0.tgz | tar xz -C /tmp
cp -av /tmp/magento-sample-data-*/* $MAGENTO_ROOT
rm -rf /tmp/magento-sample-data-*

echo "Installing Sample Data: Database"
magerun --skip-root-check --root-dir="$MAGENTO_ROOT" db:create
databaseFilePath="$MAGENTO_ROOT/*.sql"
magerun --skip-root-check --root-dir="$MAGENTO_ROOT" db:import $databaseFilePath
rm $databaseFilePath

echo "Installing Sample Data: Reindex"
magerun --skip-root-check --root-dir="$MAGENTO_ROOT" cache:clean
magerun --skip-root-check --root-dir="$MAGENTO_ROOT" index:reindex:all

echo "Installing Sample Data: Admin User"
magerun --skip-root-check --root-dir="$MAGENTO_ROOT" \
		admin:user:create \
		"${ADMIN_USERNAME}" \
		"${ADMIN_EMAIL}" \
		"${ADMIN_PASSWORD}" \
		"${ADMIN_FIRSTNAME}" \
		"${ADMIN_LASTNAME}" \
		"Administrators"

**Comment by ktomk** [comment]
@brandontamm: I do not understand how this relates to magerun.

**Comment by ktomk** [comment]
Still not understanding your issue, but are you perhaps looking the `local-config:generate` command, @brandontamm?

**Comment by brandontamm** [comment]
Hi - thank you for following up. I am coping the config XML so i don't need to recreate it, however, I guess my question becomes - Can i use magerun to create a blank database with magento enterprise structure?

**Comment by ktomk** [comment]
Yes, create you own package for the enterprise version (magerun ships with CE packages only, but you can add you own) and run the `install` command. Maybe the `sys:setup:run` command already suffices in your scenario.

**Comment by brandontamm** [comment]
I thought db:create and sys:setup:run would work - I initially tried that. Here is the error I got: 
[Zend_Db_Statement_Exception]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.core_website' doesn't exist, query was: SELECT `core_website`.`website_id`, `core_website`.`code`, `core_website`.`name` FROM `core_website`

I assumed this was because there is no database structure

**Comment by ktomk** [comment]
Yeah, that's the case. You need to run the `install` command then. Please check the available switches, IIRC you should be able to skip downloading.

**Comment by brandontamm** [comment]
We're getting close.. I manually ran the following command:
./magento magerun install --noDownload --dbHost="mysql" --dbUser="root" --dbPass="pw" --dbName="magento" --installSampleData=no --useDefaultConfigParams=yes  --installationFolder="./" --baseUrl="http://magento.dev/"

I got the following [InvalidArgumentException]:
Magento working copy in /var/www/html/web seems already installed. Please remove /var/www/html/web/app/etc/local.xml and retry.

Keep in mind, I can get around this by modifying the install script to only install the composer dependencies (including Magento core) after running the command to setup the database. Is that the suggested route or is there a way around checking the installation folder since the noDownload option was selected? Did we find an enhancement for magerun? :)

**Comment by ktomk** [comment]
I now remember that I personally have experienced ca. 1.5 years ago when starting with Magerun, It's whenever you initialize the shop with an empty database. The exception stands clearly in the way here because Magento should do the first setup on it's own if the installed timestamp is not within the local.xml (if I remember that correclty, I think that's the final decision point).

The exception merely is a pre-caution not to destroy some existing setup, even if not in a perfectly working state.

Not doing the exception when --noDownload is used is perhaps a good solution.

**Comment by brandontamm** [comment]
The workaround that I mentioned above - would the timestamp still be an issue? If so, is there any way around it? I know this is something i should know :-x

**Comment by ktomk** [comment]
I have to correct mysql: Just don't place the local.xml file into the magento directory *before* you run the `install`  command (with the `--noDownload` switch). It then should work. The *install* command will then create the local.xml file with the database credentials so that the initial database-setup should work.

You can then replace it later with your local.xml. The folder then can exist earlier, incl. composer.json etc. It's only the existing local.xml file that is triggering the exception in the *install* command.

**Comment by brandontamm** [comment]
Ok - possibly one more issue - the script actually copies the local.xml. Here is the pertinent part of the script in sequence:

echo "Starting with blank database"
magerun install --noDownload --dbHost="$MYSQL_HOST" --dbUser="$MYSQL_USER" --dbPass="$MYSQL_PASSWORD" --dbName="$MYSQL_DATABASE" --installSampleData="no" --useDefaultConfigParams="yes"  --installationFolder="./" --baseUrl="http://$DOMAIN"

echo "Installing Magento"
updateMagento

echo "Preparing the Magento Configuration"
substitute-env-vars.sh /etc /etc/local.xml.tmpl

**Comment by ktomk** [comment]
In that order it should work. The *install* command only errors if *app/etc/local.xml* already exists, you script suggestion copies it *after* the command so this should be fine.

**Comment by brandontamm** [comment]
Almost there - I got 
installer_1      |   [InvalidArgumentException]
installer_1      |   Folder / is not a Magento working copy.

**Comment by brandontamm** [comment]
I used --installationFolder="./" 

The file path should be correct - is this a file path issue or is the magerun installer looking for files in that directory and not seeing it?

**Comment by ktomk** [comment]
Hmm, on quick look this might be that  --installationFolder="./" has no good support for such a relative path (`./`). I have to take a look in the code, this is fishy.

**Comment by ktomk** [comment]
Internally this looks pretty complicated which could explain the flaw. I could at least spot one place in the code that suggests not to use relative paths, so if you can resolve the path in your script you're most likely suited best (see the `realpath` command, or `cd` into that directory and use `pwd -P`). Should be manageable if you have a shell script there.

I have one idea to get better support of relative paths in there but it's not yet set and I need to test first.

**Comment by ktomk** [comment]
Hmm, for me I can't reproduce your issue. --installationFolder="./" works fine when I execute magerun within that directory, so I can't check into which issue you run with the last exception @brandontamm.

Please double-check the magerun version you use.

**Comment by brandontamm** [comment]
This is the command I use in the script to download magerun - i think it should be the latest version:
RUN curl -o magerun https://raw.githubusercontent.com/netz98/n98-magerun/master/n98-magerun.phar

**Comment by brandontamm** [comment]
Let's assume it's not a path issue....could the "Folder / is not a Magento working copy." be coming because it is checking for a file and not seeing the file in the directory?
Line 484: https://github.com/netz98/n98-magerun/blob/5cd2370b92fc90388bf3880458b528161b271bad/src/N98/Magento/Command/AbstractMagentoCommand.php

Line 163: https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Installer/InstallCommand.php

**Comment by ktomk** [comment]
@brandontamm The command you use to download magerun is outdated and is effectively downloading an outdated version (1.96.1). Switch to the current download URL instead:

    curl -o magerun https://files.magerun.net/n98-magerun.phar

This gives right now version 1.97.19 (!).

**Comment by brandontamm** [comment]
I swapped the download link to use the new version - still getting the same error. Maybe not a path issue? Ideas?

**Comment by ktomk** [comment]
If I could reproduce it here I can debug the issue. Maybe you can share some more context so that I can reproduce?

**Comment by brandontamm** [comment]
Have you used docker before? I can share the repo and you can literally spin up the exact environment if you're comfortable with Docker

**Comment by ktomk** [comment]
I have docker installed, this sounds like a plan.

**Comment by brandontamm** [comment]
Let me know if questions pop up along the way :) 
https://github.com/brandontamm/magento

**Comment by brandontamm** [comment]
Here is a helpful command to rebuild the installer - I've been doing a lot of that!
cd ~/sites/magento && docker-compose stop && rm -r web vendor data/mysql && docker ps -a && docker images -a

**Comment by ktomk** [comment]
Hmm, rebuilding the installer does not seem to work with that chain of commands. Also the install.sh scrip should exit immediately on a non-zero status of one of it's commands. Many things can go wrong but right now it continues as if everything would have worked.

**Comment by brandontamm** [comment]
sorry - that will give you the list of containers and images:
'docker rm XXX' removes the magento_installer_1 container and
'docker rmi XXX' removes the magento_installer_1 image

that will rebuild the installer - substitute the XXX with the image and container id hash

**Comment by ktomk** [comment]
@brandontamm: One gap: You can't call `db:create` while magento is not yet installed. The database credentials are taken from the *local.xml* file for that command. In our own setups (travis, local), the bash scripts are using the mysql command-line client.

- Ref: https://github.com/netz98/n98-magerun/blob/580cc2357d951f9dd8e39e54a9e914ac61980598/build/local/test_setup.sh#L55

**Comment by ktomk** [comment]
@brandontamm: Is there a way to not throw away the whole image to rebuild it? I normally only need to replace install.sh with a new version.

**Comment by ktomk** [comment]
@brandontamm: I find the use of docker frustrating and massively standing in the way to trouble-shoot the issue you experience. I also do not understand which problem with the upstream project https://github.com/andreaskoch/dockerized-magento you're trying to solve. There might be some issues with magerun in that setup however these issues are not easily reproduced and to debug in the container infrastructure you offer with that repo.

**Comment by ktomk** [comment]
Also if I understand docker right, you should create a magento container with it already installed. So the magento/magerun setup should be part of the dockerfile creation, shouldn't it?

**Comment by ktomk** [comment]
My earlier comment about creating the database before running the installer is actually not necessary. The install command will  create the database if it does not yet exists. I also pushed some smaller changes into the development branch of magerun to add some more comfort while debugging. Setup runs fine on my ends.

**Comment by ktomk** [comment]
@brandontamm: You can review the changes I made to get it into a working state here: https://github.com/ktomk/magento/commit/33598d2d93d48593a98c33487aebce3c5afcbd0e#diff-c18fd6a4b0fab8e7cd459aa09081d0bc - It's merely only waiting for the mysql container to be up and running for accepting connections.
