### ISSUE TITLE
PHP7 incompatibility

### ISSUE THREAD

**Issue by IdahoPL** [netz98/n98-magerun#820]
Problem which was fixed here: https://github.com/netz98/n98-magerun/issues/691

still exists:

$ php -v
PHP 7.0.6 (cli) (built: May  6 2016 10:47:03) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

$ git clone https://github.com/netz98/n98-magerun.git
Cloning into 'n98-magerun'...
remote: Counting objects: 15797, done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 15797 (delta 52), reused 0 (delta 0), pack-reused 15670
Receiving objects: 100% (15797/15797), 37.37 MiB | 4.62 MiB/s, done.
Resolving deltas: 100% (7625/7625), done.
Checking connectivity... done.

$ ./n98-magerun/n98-magerun.phar
PHP Fatal error:  Cannot use N98\Util\String as String because 'String' is a special class name in phar:///usr/home/idaho/n98-magerun/n98-magerun.phar/src/N98/Magento/Application.php on line 11

**Comment by tkn98** [comment]
Try ./build.sh first. Afterwards you don't have the outdated n98-magerun.phar any longer ;)

**Comment by ToonSpinISAAC** [comment]
Even after doing this:

    wget https://files.magerun.net/n98-magerun.phar
    chmod +x ./n98-magerun.phar
    ./n98-magerun.phar

I get the error with PHP 7. Am I doing something wrong?

**Comment by tkn98** [comment]
@ToonSpinISAAC: Please try  the `./n98-magerun.phar -vvv --version` command and paste command line and output here.

**Comment by ToonSpinISAAC** [comment]
If I do this:

    ./n98-magerun.phar -vvv --version

I get:

    PHP Fatal error:  Cannot use N98\Util\String as String because 'String' is a special class name in phar:///home/toon/Downloads/n98-magerun.phar/src/N98/Magento/Application.php on line 11

I just downloaded and tried it again to be sure, with the commands I used in my previous comment.

**Comment by tkn98** [comment]
@ToonSpinISAAC: Again? Then the command should be `n98-magerun.phar.1` unless you enable the no-clobber option of wget. Please provide the MD5 sum of the phar file.

**Comment by ToonSpinISAAC** [comment]
When I used PHP 5 to run `./n98-magerun.phar -vvv --version` I noticed that it was running some kind of 1.96 version, so I deleted the PHAR, ran the wget command again and then it worked.

I wasn't aware of wget's behavior in the case that the file existed. PEBKAC in this case, I guess, sorry!

**Comment by tkn98** [comment]
@ToonSpinISAAC: No worries, next time when in doubt just check checksums with the download site, we got some there :)

**Comment by ToonSpinISAAC** [comment]
Will do, @tkn98. And thanks for n98-magerun, it's an important tool for us and many other Magento developers!

**Comment by tkn98** [comment]
And a reminder for me that we should really replace that file with a stub that shows a message how to obtain it. Esp. as PHP 7 now is more and more widely used. Thanks for reporting @ToonSpinISAAC !
