### ISSUE TITLE
Install with --noDownload and --forceUseDb

### ISSUE THREAD

**Issue by adamj88** [netz98/n98-magerun#822]
I'm running the following command on version 1.97.21:

```
n98-magerun.phar install 
  --dbHost="localhost" 
  --dbName="databaseName" 
  --dbUser="user" 
  --dbPass="password" 
  --installSampleData=yes 
  --useDefaultConfigParams=no 
  --installationFolder="." 
  --baseUrl="http://localhost/"
  --noDownload
  --forceUseDb
```

I have an existing, empty database in place with no `app/etc/local.xml` file present. This command fails with the following:

```
Magento Installation  
                        
Database databaseName already exists.

  [InvalidArgumentException]         
  Database configuration is invalid                                 
```

This is contrary to the `forceUseDb` documentation which says:

> If --noDownload passed, force to use given database if it already exists.

If I delete the whole database and run the command it succeeds.

**Comment by ktomk** [comment]
@adamj88: Can you please report your magerun version? We had some recent changes in that area and I want to check if there is still something to fix or we event introduced a new annoyance. If you're not yet running on the latest version, please upgrade to it and try if it already solves your issue.

**Comment by adamj88** [comment]
@ktomk: It's occurring on v1.97.21, I ran `self-update` before reporting the issue to verify it was happening on the latest version.

**Comment by ktomk** [comment]
@adamj88: I could now reporduce your issue and I have done a fix in the development version. Please switch to it with `self-update --unstable` and try your command again. It should then work as expected, but please check on your own and give back feedback.

**Comment by adamj88** [comment]
@ktomk: It's progressing further than before but I'm getting a RuntimeException being thrown:

```
➜  n98-magerun.phar install --dbHost="dbHost" --dbName="dbName" --dbUser="dbUser" --dbPass="dbPass" --installSampleData=yes --installationFolder="." --baseUrl="http://localhost/" --noDownload --forceUseDb --useDefaultConfigParams=yes --verbose

                        
  Magento Installation  
                        

Start installation process.
/bin/php -f 'install.php' -- --license_agreement_accepted 'yes' --locale 'en_GB' --timezone 'Europe/Berlin' --db_host 'dbHost' --db_name 'dbName' --db_user 'dbUser' --db_pass 'dbPass' --db_prefix '' --url 'http://localhost/' --use_rewrites 'yes' --use_secure 'no' --secure_base_url 'https://localhost/' --use_secure_admin 'no' --admin_username 'admin' --admin_lastname 'lastname' --admin_firstname 'firstname' --admin_email 'email@address.com' --admin_password 'password' --session_save 'files' --admin_frontname 'admin' --backend_frontname 'admin' --default_currency 'GBP' --skip_url_validation 'yes' 

                      
  [RuntimeException]  
                      

Exception trace:
 () at phar:///usr/local/bin/n98-magerun.phar/src/N98/Util/Exec.php:41
 N98\Util\Exec::run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/Installer/InstallCommand.php:858
 N98\Magento\Command\Installer\InstallCommand->installMagento() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/Installer/InstallCommand.php:185
 N98\Magento\Command\Installer\InstallCommand->execute() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:440
 N98\Magento\Command\AbstractMagentoCommand->run() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:603
 N98\Magento\Application->doRun() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:669
 N98\Magento\Application->run() at /usr/local/bin/n98-magerun.phar:8
```

PHP v5.5.26

**Comment by ktomk** [comment]
@adamj88: Fine, then the first annoyance is fixed. For the RuntimeException: The command-line command fails with a non-zero status / exit code. What happens if you run that exact command manually? And can you obtain the status code? I also update the development version again to also show the exact status-code and the command itself.

**Comment by adamj88** [comment]
@ktomk: I'm getting:

```
[RuntimeException]                                                                                                                                                                                                                       
  Exit status 255 for command /bin/php -f 'install.php' -- --license_agreement_accepted 'yes' --locale 'en_GB' --timezone 'Europe/Berlin' --db_host 'dbHost' --db_name 'dbName' --db_user 'dbUser' --db_pass 'dbPass' --db_prefix '' --url 'http://localhost/' --use_rewrites 'yes' --use_secure 'no' --secure_base_url 'https://localhost/' --use_secure_admin 'no' --admin_username 'admin' --admin_lastname 'lastname' --admin_firstname 'firstname' --admin_email 'email@address.com' --admin_password 'password' --session_save 'files' --admin_frontname 'admin' --backend_frontname 'admin' --default_currency 'GBP' --skip_url_validation 'yes'   2>&1. Output was:   

Exception trace:
 () at phar:///usr/local/bin/n98-magerun.phar/src/N98/Util/Exec.php:42
 N98\Util\Exec::run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/Installer/InstallCommand.php:858
 N98\Magento\Command\Installer\InstallCommand->installMagento() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/Installer/InstallCommand.php:185
 N98\Magento\Command\Installer\InstallCommand->execute() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php:440
 N98\Magento\Command\AbstractMagentoCommand->run() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:603
 N98\Magento\Application->doRun() at phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:669
 N98\Magento\Application->run() at /usr/local/bin/n98-magerun.phar:8
```

Manually running the command which is output by the cli exits with the sample data installed and creates the `app/etc/local.xml` file.

**Comment by ktomk** [comment]
That's an error when install.php is invoked. Normally 255 is a parse error or some other fatal error. Please check if install.php is in order and try to trouble.shoot this by executing the command by hand. You can add more settings like display_errors via the command line like:

    /bin/php -ddisplay_errors=1 -derror_reporting=-1 -f 'install.php' -- --license_agreement_accepted 'yes' --locale 'en_GB' --timezone 'Europe/Berlin' --db_host 'dbHost' --db_name 'dbName' --db_user 'dbUser' --db_pass 'dbPass' --db_prefix '' --url 'http://localhost/' --use_rewrites 'yes' --use_secure 'no' --secure_base_url 'https://localhost/' --use_secure_admin 'no' --admin_username 'admin' --admin_lastname 'lastname' --admin_firstname 'firstname' --admin_email 'email@address.com' --admin_password 'password' --session_save 'files' --admin_frontname 'admin' --backend_frontname 'admin' --default_currency 'GBP' --skip_url_validation 'yes'
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Using these two PHP settings should some more light, like a concrete error message and the place where it occurs.

**Comment by ktomk** [comment]
@adamj88: Any when you manually run the command, can you tell which exit status the command has (`echo $?`)?

**Comment by ktomk** [comment]
@adamj88: I've once again updated the development version. As it seems it's not easily reproducible by entering the command manually I've added  the PHP error settings to the install command invocation. this now should really shed some more light ;)

**Comment by adamj88** [comment]
@ktomk: It appears to be a problem with a module, it's giving me more detail now. I removed the module temporarily and it's now working fine.

Thanks for troubleshooting this so quickly :)

**Comment by ktomk** [comment]
@adamj88: Did it gave more details to you because of the php-ini-settings I added? Would you consider it useful to keep these flags in?

**Comment by adamj88** [comment]
@ktomk: Yea, it gave more useful output to debug what was going on in this instance, maybe worth keeping those flags in for the development copy at least.

**Comment by ktomk** [comment]
@adamj88: Develop version will become the next stable version, which is why I'm asking. I think I'll add these on debug verbosity (`-vvv`). So in future `-vvv` will shed more light. Also the return code will be visible in all circumstances.

Now if you could share how I could produce a similar error on my end then I could easily test this. Maybe you're willing to share some details so I can break it here on my own box?

**Comment by adamj88** [comment]
@ktomk: I was having a problem with a class not being found in a module, so on the install command it was throwing the following:

```
  [RuntimeException]                                                                                                                 
  Installation failed (Exit code 255).                                                                                               
  Fatal error: Class 'Mage_Namespace_Modulename_Helper_Data' not found in /app/Mage.php on line 547  
```

I think you'll be able to replicate it by deleting a helper from a module.

**Comment by ktomk** [comment]
@adamj88: Ah that's useful to know. So scenario is to use `--noDownload --forceUseDb` to operate on  a shop-project (as usual :)), makes total sense. But running into a fatal error due to an autoloader problem. I see. I think we can keep the setting in, always, as warnings and notices won't stop the installation and are most likely interesting so see anyway for a developer.

Thanks for your detailed feedback and help.
