### ISSUE TITLE
Create Multiple Customers Combining Script with customer:create

### ISSUE THREAD

**Issue by st-bobb** [netz98/n98-magerun#823]
Probably more of a feature request.
Is it possible or should I write something else myself?
Can we pass in responses to the prompt using script?

**Comment by ktomk** [comment]
@st-bobb: Can you provide an example what you're looking for? Pseudo code or similar is fine. Technically most likely everything is possible somehow, would be better if you make this a bit more concrete so that some better directions can be given.

**Comment by ktomk** [comment]
No traction.
