### ISSUE TITLE
Specify target location of setup:backup

### ISSUE THREAD

**Issue by nbennett25** [netz98/n98-magerun#826]
Feature request: allow user to specify target directory for setup:backup to write to instead of var/backup:

`./n98-magerun.phar setup:upgrade --target-location ~/Desktop`

**Comment by ktomk** [comment]
I would prefer to name the option `--backup-folder`. Can you imagine to create a pull-request for this?

**Comment by ktomk** [comment]
Which command do you exactly related to? Is that command from n98-magerun or by a Magerun extension?
