### ISSUE TITLE
Allow putting n98-magerun.yaml in the project root

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun#827]
It is possible to put a project config in app/etc

https://github.com/netz98/n98-magerun/wiki/Config#project-config

Just to have this config easier accessible and have the possibility to have it in the same place in magerun2 I would suggest to additionally allow placing the project config into the root directory of the project (same folder like the .n98-magerun).

What do you think?

Do you see problems?

**Comment by ktomk** [comment]
In Magento 1 that folder is the webroot, would be a bit too easily accessible :)

**Comment by tkn98** [comment]
@amenk: Just getting the info that the feature is already implemented if you make use of the stopfile. Can you please try this and report back if not?

**Comment by ktomk** [comment]
No feedback provided, closing.
