### ISSUE TITLE
db:import failed

### ISSUE THREAD

**Issue by keithbmcd** [netz98/n98-magerun#828]

**Comment by keithbmcd** [comment]
I was trying to import a db, but it does not work

sh-3.2# n98-magerun.phar db:import ../../tmp/magento-staging.sql

It's not recommended to run n98-magerun as root user

"app/etc/local.xml"-file '/app/etc/local.xml' is not readable


                                                     
  [RuntimeException]                                 
  Failed to load database settings from config file  
                                                     




                                                                 
  [InvalidArgumentException]                                     
  "app/etc/local.xml"-file '/app/etc/local.xml' is not readable  
                                                                 


db:import [-c|--compression COMPRESSION] [--only-command] [--only-if-empty] [--optimize] [--drop] [--drop-tables] [--] [<filename>]


any idea?

Thanks

**Comment by ktomk** [comment]
Can you please report back the following information:

* `n98-magerun.phar --version` (magerun version in question)
* `pwd -P` (the working directory)

Additionally please provide the full path of your `app/etc/local.xml` config file.

**Comment by ktomk** [comment]
No traction for quite some time, closing.
