### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by Insect2015** [netz98/n98-magerun#830]
Hello Support,

it's also working on PHP7 Magento version 1.9.2.1 👍

**Comment by ktomk** [comment]
But Magento version 1.9.2.1 does not support PHP7 - or wait, does it?

**Comment by Insect2015** [comment]
Hello Ktomk,

I use Inchoo_PHP7 and it's works perfect 👍

**Comment by ktomk** [comment]
Okay, well, so the standard situation. We do test the code on PHP 7 in the travis build. So you should be covered.
