### ISSUE TITLE
Upgraded to 1.9.2.4 and n98-magerun won't run because it thinks this is Magento2

### ISSUE THREAD

**Issue by danemacmillan** [netz98/n98-magerun#831]
Indexes didn't run last night. Investigation reveals that they did not run because `magerun` thinks the installation is a Magento2 instance. It is Magento `1.9.2.4`. Why is it thinking this? 

n98-magerun version: `1.94.0`

This is the output when trying to run any command:
```
$ ./n98-magerun


  Compatibility Notice


You are running a Magento 2 instance. This version of n98-magerun is not compatible
with Magento 2. Please use n98-magerun2 for this shop.

A current version of the software can be downloaded on github.

Download with curl
------------------

    curl -o n98-magerun2.phar https://raw.githubusercontent.com/netz98/n98-magerun2/master/n98-magerun2.phar

Download with wget
------------------

    curl -o n98-magerun2.phar https://raw.githubusercontent.com/netz98/n98-magerun2/master/n98-magerun2.phar
```

**Comment by ktomk** [comment]
You can try with the `-vvv`switch  for more verbose output which might reveal some details (shown as well in `--help`).

Next to that please also try with the latest Magerun version if it also shows the same behaviour.

**Comment by danemacmillan** [comment]
The output is the same, with the exception that it's preceded by a few directory paths--none of which reveal anything important.

Downloading the `phar` directly and running it does get rid of the compatibility problem. Downloading it directly is not part of the build, though. It'll do for now, or at least until we can upgrade.

**Comment by ktomk** [comment]
Makes sense, 1.94.0 is pretty outdated though. I strongly recommend switching to a newer version. I would close this issue for now unless you still have some questions or objections against it.

**Comment by tkn98** [comment]
Outdated version was used, current stable does not have this issue.
