### ISSUE TITLE
No longer lets you install due to Magento taking down url's

### ISSUE THREAD

**Issue by octoxan** [netz98/n98-magerun#832]
Can no longer use this to install Magento thanks to Magento killing all  the download  URLs.

**Comment by ktomk** [comment]
Please use the mirrors.

**Comment by octoxan** [comment]
How? Am I missing something in the documentation?

**Comment by ktomk** [comment]
They are in the list of packages to install.

**Comment by tkn98** [comment]
@octoxan: If you call the *`install`* command without any other parameters you should be asked which package to install presenting a list of ca. 28 packages, choose one with *`-mirror`* in the name like *`magento-mirror-1.9.2.4`*.

Does this solve your issue?

**Comment by octoxan** [comment]
Yes it does! Thank you very much. Sorry I must have missed that part of the documentation.

**Comment by tkn98** [comment]
Case closed.
