### ISSUE TITLE
n98-magerun.phar not working on mac os x 10.11

### ISSUE THREAD

**Issue by NgocTien01542** [netz98/n98-magerun#840]
Hi Guys,
  I just use to this command on my magento folder: php n98-magerun.phar
  but it only show "?".
  it's magento 1 and n98-magerun.phar latest version 
![n98-magerun](https://cloud.githubusercontent.com/assets/5461972/16800760/13b597b6-4921-11e6-8ab9-4e245e696862.jpg)

**Comment by tkn98** [comment]
I can only guess, I think this is related to unicode settings. Please see report #706 and check your PHP configuration on the multibyte / encoding settings.

Also please verify the checksum of the phar file.

Then please report back.

**Comment by NgocTien01542** [comment]
Thank tkn98

 I found the problem with encoding setting
 must be: detect_unicode=Off
