### ISSUE TITLE
Magerun not throwing Exceptions or triggering errors

### ISSUE THREAD

**Issue by shineability** [netz98/n98-magerun#842]
I am working on a magerun command, but it seems that errors are not triggered. E.g.

```
protected function execute(InputInterface $input, OutputInterface $output)
{
    $this->detetMagento($output);
}
```

If I misspell detectMagento and run the command, it does nothing, I would expect an Exception to be thrown or some other error triggered... There's also nothing in the logs.

What am I missing here?

**Comment by cmuench** [comment]
I cannot reproduce your behavior. Can you please give me some details about your PHP error settings?

**Comment by shineability** [comment]
@cmuench I'm using MAMP Pro and apparently the php.ini is different when using the command line. Setting `display_errors = On` did the trick! Sorry for the noise, should have figured that out myself ;)

**Comment by cmuench** [comment]
@shineability No problem. Someday this issue can help other MAMP Pro users.
