### ISSUE TITLE
db:dump - Cannot exclude non-prefixed tables

### ISSUE THREAD

**Issue by richardklint** [netz98/n98-magerun#847]
When performing a db:dump using magerun, I've noticed it is impossible to strip non-magento-prefixed tables. For example, if the Magento prefix is "mage", then I wouldn't be able to strip a table such as "test_table" since magerun automatically appends the prefix to the stripped tables, it would actually strip "mage_test_table" and that's not right.

Perhaps a better way is to add another option to magerun and have it not auto-prepend the Magento prefix to it such as --exact-strip or something similar.

**Comment by tkn98** [comment]
Hmm, sounds like you even found a bug, as we should not export any of the non-prefixed tables at all. Otherwise the prefix makes no sense, doesn't it?

**Comment by alphab0t** [comment]
Yeah, makes sense Tom. I noticed this the other day with a new client I'm working on where they have all the magento tables prefixed with "mage" and have a few (rather large) tables for their inventory management system outside of Magento so I would like to exclude those but found no way to do so, resulting in larger than usual db dumps.
