### ISSUE TITLE
Don't flush the cache during 'sys:setup:run'

### ISSUE THREAD

**Issue by fbrnc** [netz98/n98-magerun#850]
Before executing `sys:setup:run` n98-magerun flushes the entire cache (see https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/System/Setup/RunCommand.php#L48)

This is critial since it has a major impact on the infrastructure, especially while your rolling out a new deployment. On top of that we typically use customized cache prefixes (configured in local.xml) to 'namespace' the different builds with a build number in the cache prefix. `sys:setup:run`will delete everything affecting the current deployment.

Is there a reason why the cache needs to be flushed?
Could the cache just by cleaned (which would respect the cache prefix)?
Or could we even just selectively clean the config cache? (or what else is stuck in the cache that needs to be updated before running updates?

**Comment by ktomk** [comment]
> Is there a reason why the cache needs to be flushed?

Good question. The change is back from 2012 and I didn't do it so I personally can't say without further study.

> Could the cache just by cleaned (which would respect the cache prefix)?

Yes, changing from flush to clean command.

> Or could we even just selectively clean the config cache? (or what else is stuck in the cache that needs to be updated before running updates?

Maybe also an option. 

---
Perhaps this is a left-over. The addition of the flush command is pretty old. Later on there was a fix on initializing the (Magento) application (`$this->initMagento()`).

I must admit from top of my head I can't say why there is the flush of the cache. It might have been some convenience feature (ref 18836aa629ef2b750c2f2ab364f2a10a8a3c17d7) albeit it summoned some workaround code later (ref f9e960ef22bfa62452760ecd777e26886561eab8) it stayed in.

Technically I do not see the reason behind this. If needed, in cli, one could call cache:flush before if needed and then do the sys:setup:run.

Maybe @cmuench has some more background info about the original reasoning putting cache:flush in? It came in before my ;Magerun time.

**Comment by fbrnc** [comment]
Wow, thanks a lot for this quick respone and for digging into this. If really anything needs to be done before running the scripts switching from `flush` to `clean` would already be a huge gain.

If there are concerns with breaking backwards compability we could introduce an `skipFlushCache`option (defaulting to false), so people could take care of cleaning the cache themeselves before calling `sys:setup:run`

**Comment by cmuench** [comment]
@fbrnc As Tom mentioned is the code very old. We supported Magento 1.3 at this time.
I think it could be an issue with some store initialization. With n98-magerun you also need to flush the cache to start the update process in the web frontend.

I think we should add the `--skip-cache-flush` option to the command and @fbrnc can investigate if this change will produce any issues.

**Comment by tkn98** [comment]
Backwards compat is fine.

Please find the `--no-implicit-cache-flush` option within the development version (source). I have not turned this into clean, so that if you need clean, you should call it beforehand.

Please try how it works for you.

@cmuench: Here as well dev-build runs but hangs on outdated code.

**Comment by arwineap** [comment]
We were also having issues with the caches being cleared during sys:setup:run

Fix works great for us!

**Comment by tkn98** [comment]
This feature is now part of the code-base in the development version and will become part of the next stable version.
