### ISSUE TITLE
404 error after successful upgrade

### ISSUE THREAD

**Issue by barbazul** [netz98/n98-magerun#855]
This is probably a minor thing but I am seeing a 404 error being output after upgrading n98-magerun to 1.97.22

```
$ php n98-magerun.phar selfupdate
Updating to version 1.97.22.
    Downloading: 100%         
Successfully updated n98-magerun
404: Not Found
```

However, upgrade was successful and everything seems to work fine

```
$ php n98-magerun.phar --version
n98-magerun version 1.97.22 by netz98 new media GmbH
```

**Comment by ktomk** [comment]
The 404 is when magerun tries to fetch the changelog file whichs name has changed sometime over the last months. It's no defect in functionality. It's a problem with the original implementation which still exists. We can't fix this retroactively however should have this as a reminder for future changes.

**Comment by ktomk** [comment]
Nothing to fix here atm so closing. But the report is useful to keep in mind for the next time the URL changes.
