### ISSUE TITLE
Doesn't output anything

### ISSUE THREAD

**Issue by writecz** [netz98/n98-magerun#860]
I get no message for any command, ie. index:list, cache:list... sys:info ends up with "Magento System Information", but prints nothing else.

Running with -v flag didn't show any debugging info.

**Comment by tkn98** [comment]
Please provide the full (non) output of the command incl. the command itself. Please add `-vvv` option for more verbose information.

**Comment by writecz** [comment]
Nevermind. It started working today, dunno what it was. Thanks you for your participation and -vvv flag, new for me. Have a nice day.
