### ISSUE TITLE
Autoloading composer classes in commands

### ISSUE THREAD

**Issue by shineability** [netz98/n98-magerun#864]
How can I use composer installed packages in my commands? Where to include the composer autoload.php? When I try to include it at the top of my command before the class definition it gives me this error:

`PHP Fatal error:  Uncaught Error: Call to undefined method N98\Magento\Application\Console\Event::setDispatcher() in phar:///usr/local/bin/magerun/vendor/symfony/event-dispatcher/EventDispatcher.php:46`

When including in the`execute()` method it works, but that seems a bit wrong.

**Comment by ktomk** [comment]
Which composer installed packages? New ones or the existing ones in the package?

For existing ones it should work out of the box, Console Events should be available in Magerun "natively" as we're making use of those already.

**Comment by shineability** [comment]
E.g. I want to use the package [semver/semver](https://github.com/git-pull-request/php-semver) in the command I'm writing. Command should be run globally, not in an existing Magento instance. So my idea was to require it globally and then include ~/.composer/vendor/autoload.php in the command class, resulting in the error mentioned above. What would be the best way to do this? Do you need to include an autoload file or can you tell magerun what composer classes to autoload by config?

**Comment by ktomk** [comment]
Okay, I'm not that fluent with it but what I remember might be what you're looking for. In the config file (yaml file) of your extension you can make use of the following keys:

* `autoloaders` : PSR-2
* `autoloaders_psr4` : PSR-4

These can contain zero or more prefix / path combinations in which you hint the class namespace prefix with the path on disk.

When Magerun loads, your extensions configuration will be loaded as well (and merged in) and then when Magerun initializes the autoloader config-entries are registered for actual autoloading.

Here is a third-party Magerun extension that demonstrates the use of autoloaders: [n98-magerun.yaml](https://github.com/Hypernode/hypernode-magerun/blob/master/n98-magerun.yaml) (excerpt):

~~~
autoloaders:
  Hypernode: %module%/src

commands:
[...]
~~~
Even this is Magerun 1, it should work exactly the same in Magerun 2 as we share the config-loader between both projects (with only difference in the file-name `n98-magerun2.yaml`).

We currently have two place-holders you can make use of:

* `%module%` : path of your Magerun module on disk.
* `%root%` : path of the Magento application.

I think this should suit your needs for a starter, please let me know if you run into problems (or just if it worked out).

References:
* [Hypernode/hypernode-magerun](https://github.com/Hypernode/hypernode-magerun) (Github repository)
* [Find available updates for installed modules](http://magerun.net/find-available-updates-for-installed-modules/) (Feb 2016; by Christian Münch)
* [composer vendor autoloads #340](https://github.com/netz98/n98-magerun/issues/340) (N98-Magerun Github Issue)

**Comment by tkn98** [comment]
@shineability: Please let us know if this worked for you or if you have any further questions.

**Comment by ktomk** [comment]
No traction.
