### ISSUE TITLE
Exiting shell?

### ISSUE THREAD

**Issue by ADDISON74** [netz98/n98-magerun#866]
n98-magerun shell command allows prompt interface. Do we have a command for exiting the shell like quit, exit? in this moment I am exiting with Ctrl + C.

**Comment by cmuench** [comment]
You can type "exit" and hit return.

**Comment by ADDISON74** [comment]
It is not working, see the image bellow:

![n98_exit](https://cloud.githubusercontent.com/assets/8360474/19553741/24dd3bc6-96be-11e6-87c8-0635c7e17e69.jpg)

**Comment by ktomk** [comment]
Please report the exact version of Magerun you're using and the original command-line you executed to enter the console so that we can see if the scenario you report is reproducible or not. Thanks.

**Comment by ADDISON74** [comment]
OS: Debian 8.5  64bits
n98-magerun version: 1.97.22 downloaded according to your instructions in Magento root directory
command executed: ./n98-magerun.phar shell

After executing that command you have the screenshot from above. Entering exit command and pressing Enter key you see the result. Error says "Command exit is not defined". You are still in n98-magerun prompt shell.

**Comment by cmuench** [comment]
@ADDISON74  My mistake...   dev:console != shell
The shell can only be exited by typing "Ctrl + C".
The dev:console can do much more and has a "exit" command.

**Comment by ADDISON74** [comment]
I can exit with Ctrl + D as mentioned when you start shell too. I thought it might be an exit/quit command.

**Comment by ktomk** [comment]
Ctrl + D signals EOF IIRC. See as well some more reference material like [Why does Ctrl-D (EOF) exit the shell? (Unix & Linux Stackexchange; Jan 2014)](http://unix.stackexchange.com/questions/110240/why-does-ctrl-d-eof-exit-the-shell).

The Shell itself is from Symfony Console, from a quick look it's nothing we can easily change. Please use ctrl+D to exist the shell.
