### ISSUE TITLE
Incorrect URL generated via cron

### ISSUE THREAD

**Issue by ashsmith** [netz98/n98-magerun#871]
If you are generating URL's via cron such as product urls for a product feed, magerun will add the script name (`n98-magerun.phar`) into the URL rather adding `index.php`.

**Expected result:** http://dev.www.mymagentostore.com/index.php/awesome-product.html

**Actual result:** http://dev.www.mymagentostore.com/n98-magerun.phar/awesome-product.html

I did a little digging into this and `cron.php` does the following:

    // Only for urls
    // Don't remove this
    $_SERVER['SCRIPT_NAME'] = str_replace(basename(__FILE__), 'index.php', $_SERVER['SCRIPT_NAME']);
    $_SERVER['SCRIPT_FILENAME'] = str_replace(basename(__FILE__), 'index.php', $_SERVER['SCRIPT_FILENAME']);

Which as you can see replaces the script name/filename with `index.php`.

Happy to submit a PR for this, I would add the above lines in here: https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/System/Cron/RunCommand.php#L79

**Comment by tkn98** [comment]
Interesting report :) I wonder what the magento core cron.php script does here to not run into the same problem. I think we should mimic that.

**Comment by ktomk** [comment]
@ashsmith: If you like, please provide a PR. The line has changed since your initial report but the solution looks like a good mimic. It's perhaps worth to backup the original values in that `$_SERVER` superglobal and restore it back after cron callback invocation.

**Comment by ktomk** [comment]
@ashsmith: An if you can, please share the command you were executing running into this to the original report. That would better illustrate the issue (if there is private data, just use placeholders or similar).

**Comment by ktomk** [comment]
I added a fix to the development version. It would be great if you could upgrade to it (using the `self-update` command with the `--unstable` switch) and check if you still experience the issue. There is small chance that the fix is incomplete but I can not test the command fully integrated on my environment as I don't know the specifics of your scenario.

Your feedback will help to get this flaw fixed fast.

**Comment by ashsmith** [comment]
Sorry for the delay. I'll be testing this today for you!

**Comment by ashsmith** [comment]
Works perfectly 👍 

Thank you!

**Comment by tkn98** [comment]
:)
