### ISSUE TITLE
Add Magento 1.9.3

### ISSUE THREAD

**Issue by rafaelstz** [netz98/n98-magerun#872]
Add the install script to Magento 1.9.3

**Comment by Aquive** [comment]
Any details for roadmap?

**Comment by rafaelstz** [comment]
When we use `php -f n98-magerun.phar install` the last version is missing.

![image](https://cloud.githubusercontent.com/assets/610598/20846926/016c4508-b8b3-11e6-99c3-af216e95424a.png)

**Comment by ktomk** [comment]
I'm currently remote so I can't take care of this in a quick manner. For example, I can't download the packages and create the SHA1 checksums for them:

- https://github.com/OpenMage/magento-mirror/archive/1.9.3.1.zip
- https://github.com/OpenMage/magento-mirror/archive/1.9.3.0.zip

Same for those packages from Magento download section. 

Additionally when reviewing the issue it came to my attention that there is a new sample data package beginning with 1.9.2.4 already. This needs to be taken care of as well.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by tkn98** [comment]
@rafaelstz: Magento Mirro 1.9.3.0 and 1.9.3.1 incl. the correct sample-data should work now.

1.9.3.0 (w/o correct sample-data) was already available earlier, however only in the development ("unstable") version.

Today we released 1.97.24 which contains all available current versions incl. the correct demo-data properly now in a stable revision.

**Comment by tkn98** [comment]
@Aquive: Versions are now available in stable  1.97.24.
