### ISSUE TITLE
admin:user:change-password shows password

### ISSUE THREAD

**Issue by faisalmirza** [netz98/n98-magerun#873]
When asked for password, it shows the input. This should be hidden.

![image](https://cloud.githubusercontent.com/assets/1070807/20432997/09cb8d38-ada2-11e6-9ff9-de9cc2394dbb.png)

**Comment by tkn98** [comment]
Feel free to make this possible. AFAIK this is not possible with PHP built-ins. Composer uses some binary for it AFAIK. Patches welcome :)

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
