### ISSUE TITLE
cannot access DB, wrong field?

### ISSUE THREAD

**Issue by seansan** [netz98/n98-magerun#880]
Cannot access DB, wrong field?

Hi, I run this command but I cannot access DB. Don't understand why. server host is this not localhost? Or is it possible to see the complete command it uses to login?

On last version 

[user@server public_html]$  magerun db:console
Warning: Using a password on the command line interface can be insecure.
ERROR 2005 (HY000): Unknown MySQL server host '-umydbname (0)

		<default_setup>
			<connection>
				<server><![CDATA[localhost]]></server>
				<username><![CDATA[mydbname]]></username>
				<password><![CDATA[xxxxxxxxxxx]]></password>
				<dbname><![CDATA[mydbname]]></dbname>
				<initStatements><![CDATA[SET NAMES utf8]]></initStatements>
				<model><![CDATA[mysql4]]></model>
				<type><![CDATA[pdo_mysql]]></type>
				<pdoType><![CDATA[]]></pdoType>
				<active>1</active>
			</connection>
		</default_setup>

**Comment by seansan** [comment]
[mydbname@server public_html]$ magerun db:info
+------------------------+--------------------------------------------------------------------+
| Name                   | Value                                                              |
+------------------------+--------------------------------------------------------------------+
| server                 | localhost                                                          |
| username               | mydbname                                                           |
| password               | i6xxxxxxxxxxxxxL                                                    |
| dbname                 | mydbname                                                           |
| initStatements         | SET NAMES utf8                                                     |
| model                  | mysql4                                                             |
| type                   | pdo_mysql                                                          |
| pdoType                |                                                                    |
| active                 | 1                                                                  |
| host                   |                                                                    |
| port                   |                                                                    |
| unix_socket            |                                                                    |
| prefix                 |                                                                    |
| PDO-Connection-String  | mysql:host=;port=3306;dbname=mydbname                                |
| JDBC-Connection-String | jdbc:mysql://:3306/mydbname?username=mydbname&password=i6xxxxxxxxxxxxxL |
| MySQL-Cli-String       | mysql -h'' -u'mydbname' -p'i6cv5lOMJTKbRyL' 'mydbname'                 |
+------------------------+--------------------------------------------------------------------+

Can it be the mysql -h'' is empty?

**Comment by ktomk** [comment]
@seansan: could be a parsing issue. can you provide the `local.xml` file? And can you provide the magerun version?

**Comment by ktomk** [comment]
Can confirm, it's a problem when using *sever* (`/config/global/resources/default_setup/connection/server`) instead of *host* (`/config/global/resources/default_setup/connection/host`).

Looks fishy that the username then is used then. Perhaps must error on empty hostname or not put it into the Mysql-CLI-string.

**Comment by seansan** [comment]
n98-magerun version 1.97.27 by netz98 GmbH

**Comment by seansan** [comment]
that was the problem yes

no idea how <server> got there ...

**Comment by ktomk** [comment]
@seansan: I wonder as well but can't say. Can you confirm this was initially a configuration error on your end? For me it sounds a bit like that but I don't want to jump to conclusions too fast.

And in any case I see and error for the Mysql CLI command building.

**Comment by ktomk** [comment]
@seansan: Could it be that Magento worked flawlessly?

**Comment by seansan** [comment]
you almost wonder why?

I think this was our error

​thx for help

​

**Comment by ktomk** [comment]
Yes I wonder why, thanks for the feedback. I also wonder if Magento itself had an issue with that or not. I think it will fallback to `localhost` for the *host*, I think we can do the same for the Mysql CLI string. Your feedback is very welcome!

**Comment by seansan** [comment]
I think the error was correct. Because now it resulted in me fixing this.
Maybe magerun could error "host value not found"?

**Comment by ktomk** [comment]
That would be an option, on the other hand I dunno if the host entry is not just optional in Magento 1. Taking a look into the code ... according to docs, it defaults to *localhost*. Compiling a fix. I won't give an error message as there is a default encoded for it in Magento. But I'll fix the output for `db:info` so it should become more obvious.

**Comment by ktomk** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.
