### ISSUE TITLE
db:import sprintf too few arguments

### ISSUE THREAD

**Issue by peterjaap** [netz98/n98-magerun#884]
`Importing SQL dump 2016-12-dump.sql to database test`
`PHP Warning:  sprintf(): Too few arguments in phar:///usr/local/bin/n98-magerun.phar/src/N98/Util/Exec.php on line 44`

See that line [here](https://github.com/netz98/n98-magerun/blob/master/src/N98/Util/Exec.php#L43).

When I run the command with `--only-command`, and run that, I get a MySQL warning; `ERROR 1118 (42000) at line 3202: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.`

So passing on the error message from MySQL to the user through magerun seems to fail.

Obviously, raising the innodb_log_file_size fixed it for me but that was the underlying issue.

**Comment by tkn98** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by tkn98** [comment]
Thanks for the report!
