### ISSUE TITLE
product image not showing in the frontend

### ISSUE THREAD

**Issue by michel1986** [netz98/n98-magerun#886]
hello Guys,

After I use a cleanup command for the product image's the product image from som products ar not showing in the frontend ?

I use commands
> Images: remove duplicate image files
> Images: remove orphaned files
> Images: clean tables

Frontend > https://gyazo.com/3cf4241d687de289bc58427faac089dd
backend product > https://gyazo.com/0dfcfae55cc43298e89c7d2a288d6bcc

I how you no what I need to do

best regards,
Michel

**Comment by tkn98** [comment]
Hard to say from the outside. Could be a caching issue. Follow the trail of the image URL, probably you can spot something in it or on the file-system.

**Comment by tkn98** [comment]
Also please share the exact command that you were running (incl. parameters) and the n98-magerun you were using to complete your report.

**Comment by hostep** [comment]
I think @michel1986 is using this magerun addons package: https://github.com/peterjaap/magerun-addons
@michel1986: best to open an issue over there if you experience problems with those commands :)

**Comment by tkn98** [comment]
That sounds ledigt, I'll close here for now, @michel1986  even redundant, please open the issue in the correct location: https://github.com/peterjaap/magerun-addons/issues - you can leave a link to the new issue then here, too so it is cross-linked. Thank you for taking the time to make Magerun and it's Add-Ons better!
