### ISSUE TITLE
[Insight] Interfaces names should end with &quot;Interface&quot; - in src/N98/Magento/Command/CommandAware.php, line 7

### ISSUE THREAD

**Issue by thomas-spigel** [netz98/n98-magerun#887]
**[in src/N98/Magento/Command/CommandAware.php, line 7](https://github.com/netz98/n98-magerun/blob/880b7a675028ca6d12c0b41854e3951c5d73eacd/src/N98/Magento/Command/CommandAware.php#L7)**

> Interface `CommandAware` should be named `CommandAwareInterface` for better clarity.

```php

namespace N98\Magento\Command;

use Symfony\Component\Console\Command\Command;

interface CommandAware
{
    /**
     * @param Command $command
     * @return void
     */
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/9a5128f6-127c-4e6a-be4b-eade7b72b915/analyses/28)_

**Comment by ktomk** [comment]
Clarity via word-form, not cruft.
