### ISSUE TITLE
Slider Revolution(WordPress) plugin

### ISSUE THREAD

**Issue by kokosuave** [netz98/n98-magerun#889]
Fatal error: Uncaught Error: [] operator not supported for strings in /customers/3/a/c/rettaskitchen.com/httpd.www/wp-content/plugins/revslider/includes/framework/base-admin.class.php:71 Stack trace: #0 /customers/3/a/c/rettaskitchen.com/httpd.www/wp-content/plugins/revslider/admin/revslider-admin.class.php(465): RevSliderBaseAdmin::addMetaBox('Revolution Slid...', '', Array, NULL) #1 /customers/3/a/c/rettaskitchen.com/httpd.www/wp-content/plugins/revslider/admin/revslider-admin.class.php(72): RevSliderAdmin->addSliderMetaBox() #2 /customers/3/a/c/rettaskitchen.com/httpd.www/wp-content/plugins/revslider/admin/revslider-admin.class.php(44): RevSliderAdmin->init() #3 /customers/3/a/c/rettaskitchen.com/httpd.www/wp-content/plugins/revslider/revslider.php(165): RevSliderAdmin->__construct('/customers/3/a/...') #4 /customers/3/a/c/rettaskitchen.com/httpd.www/wp-admin/includes/plugin.php(1882): include('/customers/3/a/...') #5 /customers/3/a/c/rettaskitchen.com/httpd.www/wp-admin/plugins.php(164): plugin_sandbox_scrape('revslid in /customers/3/a/c/rettaskitchen.com/httpd.www/wp-content/plugins/revslider/includes/framework/base-admin.class.php on line 71

**Comment by cmuench** [comment]
Wrong repo.
