### ISSUE TITLE
How can I help make new locale for create customer

### ISSUE THREAD

**Issue by eriksenonline** [netz98/n98-magerun#893]
I would like to help add nb_NO for the https://github.com/netz98/n98-magerun#generate-dummy-customers command. How can I do that?

**Comment by tkn98** [comment]
Magerun uses *Faker* under the hood, please just try with the iso code.

The support of locales is within faker: https://github.com/fzaninotto/Faker#localization

If it does not work with nb_NO, please check if Faker already supports it and report back.

**Comment by tkn98** [comment]
Faker has support for it: https://github.com/fzaninotto/Faker/tree/master/src/Faker/Provider/nb_NO

**Comment by ktomk** [comment]
Also please provide a simple command example how you want to use it, e.g.

~~~
$ bin/n98-magerun customer:create:dummy --with-addresses 1 nb_NO 
Customer skjalg.185282@example.com with password -YpNtmD@ successfully created
~~~

I just tried this one and at least from the output this looks good to me. So could be that the locale already works it's just not documented.

From a first glance on the commands code I'd say there are two preconditions:

1. The Faker library must support the locale `nb_NO`
2. Magento must support the two-letter ISO code `nb`

So please try yourself and let us know. This is normally the first step for a contribution. Then we can decide which steps need to be taken, e..g documentation updates etc. If it already works you can consider blogging about it and spread the word :) There are many things you can do to contribute to magerun. :+1:

**Comment by cmuench** [comment]
Closed due to inactivity. Re-open if needed.
