### ISSUE TITLE
aliases do not work in n98 shell

### ISSUE THREAD

**Issue by codexp** [netz98/n98-magerun#905]
I've used the ´ccc´ alias from examples to try it out and noticed that it does not work inside n98-magerun shell but does work outside (from bash).

aliases cause an exception in n98 shell:
                                                          
    [Symfony\Component\Console\Exception\RuntimeException]  
    Too many arguments, expected arguments "command".       
    
    The command terminated with an error status (1)

**Comment by cmuench** [comment]
@codexp Is this a n98-magerun alias (defined in a yaml config)? Or is it a bash alias?

**Comment by codexp** [comment]
this is pure n98-magerun alias from yaml config.

**Comment by cmuench** [comment]
@codexp Strange. I was able to run my defined aliases within the shell. Can you provide some details of your config?

**Comment by codexp** [comment]
my config is in home folder (ubuntu: /home/{user}/.n98-magerun.yaml)
content:
```
commands:
   aliases:
     - "ccc": "cache:clean config"
     - "fs:fix:ownership": "fs:fix:permissions ownership -u ew:www-data"
```

**Comment by cmuench** [comment]
@codexp Thanks. I can reproduce the problem now. It's only if the alias calls a command with arguments.

**Comment by cmuench** [comment]
We will not fix this issue. Symfony removed support for the shell. With the update to Symfony 5.4 we will also remove this command.
