### ISSUE TITLE
install command fails

### ISSUE THREAD

**Issue by codexp** [netz98/n98-magerun#906]
I tried to install recent magento-ce version, but it has failed downloading it:

```
$ php n98-magerun.phar install --dbHost="localhost" --dbUser="root" --dbPass="****" --installationFolder="magento" --baseUrl="https://magento.local"

                        
  Magento Installation  
                        

[1]  magento-ce-1.9.2.4
[2]  magento-ce-1.9.2.3
...
[13] magento-mirror-1.9.3.1
[14] magento-mirror-1.9.3.0
...
[30] mageplus-master
Choose a magento version: 1
  - Installing magento-ce-1.9.2.4 (1.9.2.4)Warning: Accessing www.magentocommerce.com over http which is an insecure protocol.
 Downloading: FailedThe "http://www.magentocommerce.com/downloads/assets/1.9.2.4/magento-1.9.2.4.zip" file could not be downloaded (HTTP/1.1 301 Moved Permanently)
```

**Comment by cmuench** [comment]
It seems that Magento moved all assets away. We are investigating.

**Comment by vdloo** [comment]
Using the magento-mirror version still works in the mean time, for 1.9.2.4 that's option 15:

![15](https://cloud.githubusercontent.com/assets/1437341/25070926/c088c0a4-22aa-11e7-9316-35bd51083da4.png)

**Comment by cmuench** [comment]
Yes, that's a GitHub mirror. It seems that Magento removed the unauthorized accessable tarballs.

**Comment by hostep** [comment]
They have been removed a long long time ago: https://github.com/netz98/n98-magerun/issues/722
Maybe it's best if the "normal" downloads are removed from the list and only the mirrors are kept?

**Comment by cmuench** [comment]
A new n98-magerun version (1.97.30) is deployed.

**Comment by ktomk** [comment]
Please use "magneto-mirror" packages as "magento-ce" packages are offline since 2015.

**Comment by ktomk** [comment]
The packages under "magento-mirror" are transparently codified by Openmage here on Github: https://github.com/OpenMage/magento-mirror
