### ISSUE TITLE
magerun install can't parse IPv6 addresses

### ISSUE THREAD

**Issue by vdloo** [netz98/n98-magerun#907]
The `magerun install` command can't parse IPv6 dbHosts, it fails with `SQLSTATE[HY000] [2002] Failed to parse address` without brackets and with `SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known` with brackets. 

![ipv6](https://cloud.githubusercontent.com/assets/1437341/25070714/c2e4e4c6-22a6-11e7-8f71-96990b23fcca.png)

Tested on PHP 7.1.4 with mysqlnd 5.0.12-dev

**Comment by cmuench** [comment]
I'm not sure if this is a n98-magerun problem. Magento 1 has some issues with IPV6. Additonally the PHP version must be compiled with IPv6 support.

@vdloo Can you check if a normal PDO connection works with your PHP version and IPv6?

**Comment by vdloo** [comment]
Hi @cmuench, you are probably right that this breaks somewhere deeper than magerun (maybe the PHP framework?) but I figured I'd report it here anyway for people googling this error in the future. 

A connection with PDO works fine on this system, PHP is compiled with IPv6 support:

```
[android@1d173e4df7b14acb public]$ php -i | grep ipv6 -i
IPv6 Support => enabled
IPv6 => Yes

# forward the remote MySQL port to the localhost
[android@1d173e4df7b14acb public]$ ssh -L 3306:[fc08:433b:7b37:91c8:6fcc:3a9d:b24c:ab05]:3306 android@fc08:433b:7b37:91c8:6fcc:3a9d:b24c:ab05 -g 

[android@1d173e4df7b14acb public]$ cat pdo.php 
<?php
echo "ipv4:".PHP_EOL;
$db = new PDO('mysql:dbname=magentodb;host=127.0.0.1', 'root', 'password');
$result = $db->query("show tables");
$row = $result->fetch();
var_dump($row);

echo "ipv6:".PHP_EOL;
$db = new PDO('mysql:dbname=magentodb;host=[fc08:433b:7b37:91c8:6fcc:3a9d:b24c:ab05]', 'root', 'password');
$result = $db->query("show tables");
$row = $result->fetch();
var_dump($row);

[android@1d173e4df7b14acb public]$ php -d display_errors pdo.php 
ipv4:
array(2) {
  ["Tables_in_magentodb"]=>
  string(12) "admin_assert"
  [0]=>
  string(12) "admin_assert"
}
ipv6:
array(2) {
  ["Tables_in_magentodb"]=>
  string(12) "admin_assert"
  [0]=>
  string(12) "admin_assert"
}
```

If I leave out the brackets it throws the same error as magerun does without brackets:
```
[android@1d173e4df7b14acb public]$ php -d display_errors pdo.php 
ipv6:
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] Failed to parse address "fc08:433b:7b37:91c8:6fcc:3a9d:b24c:ab05:3306" in /home/android/public/pdo.php:4
Stack trace:
#0 /home/android/public/pdo.php(4): PDO->__construct('mysql:dbname=ma...', 'root', 'password')
#1 {main}
  thrown in /home/android/public/pdo.php on line 4

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Failed to parse address "fc08:433b:7b37:91c8:6fcc:3a9d:b24c:ab05:3306" in /home/android/public/pdo.php:4
Stack trace:
#0 /home/android/public/pdo.php(4): PDO->__construct('mysql:dbname=ma...', 'root', 'password')
#1 {main}
  thrown in /home/android/public/pdo.php on line 4
```

**Comment by cmuench** [comment]
ok. Thanks for investigation.

**Comment by cmuench** [comment]
I close this. Looks not like n98-magerun problem.
