### ISSUE TITLE
n98-magerun script does not throw exit code 1

### ISSUE THREAD

**Issue by chrispotter** [netz98/n98-magerun#908]
On `.magerun` scripts `n98-magerun script --stop-on-error <script>` does not throw status a non-zero exit code when it fails.

**Comment by chrispotter** [comment]
@cmuench i'm having some trouble deciphering the travis-ci output on my PR.  I forgot to assign reviewers to my PR and it won't let me assign post-creation :/ 

Can you provide some direction? 
N98\Magento\Command\Installer\InstallCommandPackageVersionTest::versionListing seems to be failing....

Thanks!

**Comment by cmuench** [comment]
@chrispotter The failed test was a problem in our develop branch. We fixed it. Your PR is now merged in the develop branch. Thanks for contributing.

**Comment by ktomk** [comment]
Fixed in next release 1.98.0.
