### ISSUE TITLE
Failed reindex does not respond with correct error status code

### ISSUE THREAD

**Issue by danemacmillan** [netz98/n98-magerun#911]
When a reindex throws errors, n98 does not respond with a non-zero error status code. For example, in a Bash environment, assume the first command in the chain fails:

```
./n98-magerun.phar -vvv index:reindex catalog_category_flat && date
```

The first command failing should mean that the `date` command will not run. Nevertheless, `date` still runs. It shouldn't. This makes it problematic to set up alerts in a crontab, for example. It also makes it impossible to handle errors properly in simple Bash scripts.

n98 should be throwing the correct non-zero error status code when an error occurs.

Related tickets I found:

- https://github.com/netz98/n98-magerun/issues/701
- https://github.com/netz98/n98-magerun/issues/709

**Comment by danemacmillan** [comment]
I should add this is also an issue when a MySQL dump fails.

```
./n98-magerun db:dump -vvv --skip-root-check --no-interaction --force --compression="gzip" --strip="@customdev" "/root/db/site/development/$(date +\%Y\%m\%d\%H\%M\%S-\%b-\%d-\%a-\%H\%M).dev.fortnine.sql.gz" && date
```

`date` will run regardless the success or failure of the dump command preceding it. This issue might be true across other commands as well, but these are the two I use most often.

**Comment by cmuench** [comment]
@danemacmillan I could reproduce the behavior in a local Enterprise Edition project. I added support to detect bubbled Exceptions. An updated version of n98-magerun will be available in the next minutes. Please update with `n98-magerun.phar self-update --unstable` to test the new version in your environment.

**Comment by danemacmillan** [comment]
I'm not willing to test this out in production, as currently I'm still trying to figure out how to reproduce the issue locally, so I don't want to add more unknowns to the environment. I recently upgraded to `1.97.30` and noticed another issue, #915, which is related.

**Comment by ktomk** [comment]
To progress further on this issue we need at least some test-run. Best is from the original reporter, but I don't want to force this on any of your production system, just saying why this issue might look stale.
