### ISSUE TITLE
add a command to encrypt/decrypt values

### ISSUE THREAD

**Issue by yoosefi** [netz98/n98-magerun#916]
Something like `dev:encrypt` and `dev:decrypt` would be helpful for operating on things like encrypted config settings.

It could just take a string and dump out the encrypted/decrypted string.

**Comment by ktomk** [comment]
I think `config:encrypt` and `config:decrypt`  is fine for the commands as encryption / decryption is for config values then. Routines for en- and de-crypting should be available in the base class of the config command.

**Comment by yoosefi** [comment]
Initially this was my thinking (see original title) but Magento can encrypt/decrypt any data, not just config.

Something that just calls `Mage::helper('core')->encrypt()` and `Mage::helper('core')->decrypt()` would be useful.

**Comment by yoosefi** [comment]
Hm ok not sure how I missed it but `--encrypt` and `--decrypt` already exist for `config:set` and `config:get`

Will keep this open for a generalized encrypt/decrypt, but feel free to close.

**Comment by ktomk** [comment]
Okay I thought you had found out earlier and therefore changed the request. Can you tell me which other data is encrypted? I only know it from config.

**Comment by yoosefi** [comment]
For example you can encrypt arbitrary strings via `Mage::helper('core')->encrypt(...)`, it's not just configuration values.

Having a command that encrypts/decrypts what you give it would be helpful.
