### ISSUE TITLE
Get frontName

### ISSUE THREAD

**Issue by szepeviktor** [netz98/n98-magerun#917]
How is it possible to get admin `frontName`?

`n98-magerun config:get admin/routers/adminhtml/args/frontName` is not the solution.

**Comment by ktomk** [comment]
If that is not the solution, then the default value might be.

**Comment by szepeviktor** [comment]
I think this is not the way to read that variable.
I can find it in local.xml.

**Comment by ktomk** [comment]
Default is not in local.xml, at least not that default I meant. Anyway, the `frontName` you ask is the part of the URL-path that signals it's the adminhtml area, doesn't it? I think that must be within some config.xml file IIRC.

**Comment by cmuench** [comment]
@szepeviktor you should use the config:dump command.

**Comment by ktomk** [comment]
I think it's about getting the value programmatically... but if it's in local.xml not sure if config:dump covers it - @cmuench perhaps knows it better from memory.

**Comment by szepeviktor** [comment]
Thank you. The dump does not contain the frontname, not the admin URL.

**Comment by ktomk** [comment]
the dump contains the default I mentioned in my first comment. so this is local.xml related. If you can share why you're looking for it we might have some pointers.

**Comment by szepeviktor** [comment]
I'd like to log in without opening app/etc/local.xml which contains frontname.
I thought n98-magerun is able to display it.

**Comment by cmuench** [comment]
n98-magerun.phar open-browser admin

**Comment by szepeviktor** [comment]
@cmuench Thank you very much

**Comment by szepeviktor** [comment]
@ktomk Thank you too.
