### ISSUE TITLE
Admin password expire doesnt get reset when you change password 

### ISSUE THREAD

**Issue by robbertstevens** [netz98/n98-magerun#919]
When I update the password with the command the password expire message doesn;t get reset. So even if I change it everyday in EE I still get notification I need to change my password.

**Comment by ktomk** [comment]
Am I correct this is an EE feature? Can you share which model manages the exipred message in EE? So far, the command only updates the admin user model maybe some events are not properly dispatched / watched or the feature is put into a controller action in EE only?

**Comment by robbertstevens** [comment]
This is indeed an EE feature. I have not looked into it, it's just something I noticed because I got the screen pop up just now while I just changed my password with the command

**Comment by ktomk** [comment]
EE has a admin-user property / column `lock_expires`. I assume it should be cleared if set before save. Can you please check if the field could be set NULL? I don't have a EE install at hand right now.

**Comment by ktomk** [comment]
Also this would require the config setting as otherwise if the expire feature is enabled, it would be disabled on each user that gets the password changed.

**Comment by robbertstevens** [comment]
OOh my bad, I was talking about n98-magerun2. Can this ticket be transfered to that project? But I can imagine this is also the case here.

BTW... It's not possible to set the column `lock_expires` to `null`

**Comment by ktomk** [comment]
@robbertstevens: It's not possible to move issues, you can report it over there. In Magento2 I think this is standard functioniality, so not an EE feature. Just FYI. You can leave a link here after you created a new ticket. I'll close the ticket now until someone confirms an issue for Magento 1.

**Comment by robbertstevens** [comment]
https://github.com/netz98/n98-magerun2/issues/293
