### ISSUE TITLE
db:dump doesn't drop+create database => pre-esisting tables persists on import

### ISSUE THREAD

**Issue by ZaneCEO** [netz98/n98-magerun#923]
Hi,
big n98-magerun fan here!

I noticed that db:dump+db:import uses a multiple "droptable+dropcreatetable" approach. This is a problem because the pre-existing tables that aren't on the dump won't get deleted on db:import.

Case in point: I was doing deploing tests with SUPEE-6788, a patch that creates an upgradescript like this:

````
...
->newTable($installer->getTable('admin/permission_variable'))
....
->newTable($installer->getTable('admin/permission_block'))
````

This actually creates new table.

My db was already upgraded (so these tables where created). I db:import a previous dump and re-run upgrades script: boom, 1050 Table 'permission_variable' already exists, because such table is not in the dump.

[My solution when working on non-magento projects is to mysqldump with](https://github.com/TurboLabIt/zzmysqldump) `--add-drop-database`. Maybe n98 can do the same?

**Comment by ktomk** [comment]
The `db:import`  command has the `--drop` option, if you use it for the import it should result in a solution for the problem you report.

The `db:export` command does not have such an option.

So please check if `db:import --drop` works for you.

**Comment by ZaneCEO** [comment]
Excellent, thanks. I will test your solution on monday, but I expect it to work for me.

**Comment by ktomk** [comment]
@ZaneCEO: Thanks for taking care!
