### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by decorate** [netz98/n98-magerun#926]
Not producing any output on the shared server my Magento is installed on. I have emailed support and they added phar to whitelist. Any ideas? Thank you.

Command

```
~/www/shell$ ./n98-magerun.phar --version
~/www/shell$ 
```

Server information

> PHP 5.5.32 (cli) (built: Feb 23 2016 02:48:49) 
> Copyright (c) 1997-2015 The PHP Group
> Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
> with the ionCube PHP Loader v4.7.5, Copyright (c) 2002-2014, by ionCube Ltd., and
> with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
> with Suhosin v0.9.38, Copyright (c) 2007-2015, by SektionEins GmbH

> Kernel Version 2.6.32-673.8.1.lve1.4.3.1.el6.x86_64

**Comment by ktomk** [comment]
Please call with the `-vvv` switch and provide the exit code:

    $ ./n98-magerun.phar -vvv --version; echo $?

It should provide more information.

**Comment by decorate** [comment]
Thanks for getting back to me.

Here is the output of the command:

```
~/www/shell$ ./n98-magerun.phar -vvv --version; echo $?
0
~/www/shell$ 
```

**Comment by ktomk** [comment]
Oh, no output at all.  Please verify the checksum of the phar file and share the expected magerun version and tell how you downloaded it.

Also Let's make the php configuration more explicit:

    $ php -ddisplay_startup_errors=1 -ddisplay_errors=1 -derror_reporting=-1 -f ./n98-magerun.phar -- -vvv --version; echo $?

This *hopefully* shows more, albeit the zero exit status already shows that there is no fatal error.

**Comment by decorate** [comment]
I used the recommended wget command to download latest version.

```
~/www/shell$ sha256sum n98-magerun.phar
694f13561125889c07ca7fdbfd9f6a7b281a4f24f2313940f7d797563c03a662  n98-magerun.phar
```

Expected version is the one dated 2017-04-17 12:40.

```
~/www/shell$ php -ddisplay_startup_errors=1 -ddisplay_errors=1 -derror_reporting=-1 -f ./n98-magerun.phar -- -vvv --version; echo $?
0
```

:( Still nothing.

**Comment by ktomk** [comment]
This is quite esoteric. I double checked the infos, maybe I get another idea later, but this smells like it could benefit from some debugging on your end. Can you share the hoster of that system? Can you disable specific PHP modules? Can you debug this ? Do you run other command-line PHP scripts on that host, likewise as well with phar files?

**Comment by decorate** [comment]
Thank you for your patience regarding this issue. I was assured by my host that `phar` had been added to the whitelist. In search of another phar to run from the command line I just attempted to install `composer`. That gave me the following error:

```
Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The suhosin.executor.include.whitelist setting is incorrect.
Add the following to the end of your `php.ini` or suhosin.ini (Example path [for Debian]: /etc/php5/cli/conf.d/suhosin.ini):
    suhosin.executor.include.whitelist = phar 

The php.ini used by your command-line PHP is: /usr/local/lib/php.ini
If you can not modify the ini file, you can also run `php -d option=value` to modify ini values on the fly. You can use -d multiple times.
```

My apologies I will chase with host (shared hosting) now and see if they can update the whitelist.

**Comment by decorate** [comment]
That was definitely it, running as follows and it works!

`php -d suhosin.executor.include.whitelist=phar n98-magerun.phar`

**Comment by ktomk** [comment]
I've applied a fix so that this circumstance is visible upfront, check is the same as with the Composer installer.

The change is directly available with the development version so please try it on your host.

**Comment by decorate** [comment]
Can confirm the check is in place and works on my host.

```
~/www/shell$ ./n98-magerun-dev.phar 
The suhosin.executor.include.whitelist setting is incorrect.
Add the following to the end of your `php.ini` or suhosin.ini (Example path [for Debian]: /etc/php5/cli/conf.d/suhosin.ini):
    suhosin.executor.include.whitelist = phar 
```

**Comment by ktomk** [comment]
Fine. This issue also documents the workaround via explicit invocation:

    $ php -d suhosin.executor.include.whitelist=phar -f n98-magerun.phar -- --version
