### ISSUE TITLE
Make config:get list out section values

### ISSUE THREAD

**Issue by yoosefi** [netz98/n98-magerun#933]
It would be nice to be able to view an entire section at once by just supplying the path to it.

With `Mage::getStoreConfig()`, if you omit the final node from the path, you get an array back of all of the section's values. Could use that.

Examples:

```
n98-magerun.phar config:get web
n98-magerun.phar config:get web/secure
```

**Comment by ktomk** [comment]
What you're looking for is possible by using a wildcard:

Show all values:

      $ bin/n98-magerun config:get '*'

Show web values:

    $ bin/n98-magerun config:get 'web/*'

etc.

Is that the feature you're looking for?

**Comment by yoosefi** [comment]
Ah wonderful, thank you.
