### ISSUE TITLE
Where to check the checksum?

### ISSUE THREAD

**Issue by goosehub** [netz98/n98-magerun#935]
"If it shows the same checksum as on the website, you downloaded the file successfully."

I think it's great you're encouraging developers to check checksums. That said, where on the website can I check my checksum?

This is the website right?

http://magerun.net/

What page do I need to be on?

Can you update the README to be more clear on this?

**Comment by ktomk** [comment]
The website is https://files.magerun.net/ it has the downloads and the checksums.

**Comment by ktomk** [comment]
Sure, you may file a pull request. We're always open for contributions :) Thanks for taking care.
