### ISSUE TITLE
Fatal error: Call to undefined method Symfony\Component\Console\Event\ConsoleCommandEvent::commandShouldRun

### ISSUE THREAD

**Issue by convenient** [netz98/n98-magerun#939]
I'm getting a PHP fatal error when trying to instantiate magerun for a client which has magento installed into a sub directory using https://github.com/AydinHassan/magento-core-composer-installer.

#### Setup prep for version 1.98.0
```bash
[14:54:33] lukerodgers [~/src/n98-magerun]$ git fetch
[14:54:35] lukerodgers [~/src/n98-magerun]$ git checkout tags/1.98.0
Note: checking out 'tags/1.98.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at dc6729e... Add release branch to travis
[14:54:41] lukerodgers [~/src/n98-magerun]$ composer install -o
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 50 installs, 0 updates, 0 removals
  - Installing symfony/process (v2.8.16): Loading from cache
  - ... snipped for brevity ...
Generating optimized autoload files
```

#### Showing the PHP fatal error

```bash
[14:54:52] lukerodgers [~/src/n98-magerun]$ ./bin/n98-magerun --root-dir=/Users/lukerodgers/src/client/htdocs/ cache:list

Fatal error: Call to undefined method Symfony\Component\Console\Event\ConsoleCommandEvent::commandShouldRun() in /Users/lukerodgers/src/n98-magerun/vendor/symfony/console/Application.php on line 865
```

#### Probable cause is 3f015d2b3426c9087eeeba0cfb42f92f5b6a417b

```bash
[14:55:09] lukerodgers [~/src/n98-magerun]$ git revert     3f015d2
[detached HEAD e13bc83] Revert "Fix Magento Enterprise detection, fixes #902"
 3 files changed, 29 insertions(+), 100 deletions(-)
 delete mode 100644 src/N98/Magento/Initialiser.php
[14:55:18] lukerodgers [~/src/n98-magerun]$ ./bin/n98-magerun --root-dir=/Users/lukerodgers/src/client/htdocs/ cache:list
+-------------------+---------+
| code              | status  |
+-------------------+---------+
| config            | enabled |
| layout            | enabled |
| block_html        | enabled |
| translate         | enabled |
| collections       | enabled |
| eav               | enabled |
| config_api        | enabled |
| config_api2       | enabled |
+-------------------+---------+
```

I'll be looking into this when I have time, but it won't be today and I thought you'd like to know.

**Comment by convenient** [comment]
A quick round of experimentation suggests this is only breaking in community edition, my EE instances all work without issue.

The client is running 1.9.2.4

**Comment by convenient** [comment]
Commenting out the following line seems to make the issue disappear

https://github.com/netz98/n98-magerun/commit/3f015d2b3426c9087eeeba0cfb42f92f5b6a417b#diff-733082d0f223a21b50061401f988bf02R320

**Comment by ktomk** [comment]
Never seen that error, what makes me wonder is why the method shouldn't be there in in CE edition, Magerun itself should ship with it (via it's requirements as operating on Symfony Console).

**Comment by ktomk** [comment]
#938 might be related....

**Comment by tylerssn** [comment]
@convenient - I am running EE and am having a [similar issue](https://github.com/netz98/n98-magerun/issues/938).

**Comment by convenient** [comment]
See my update on #938, I think both these issues may have the same (or similar) cause.

Furthermore, I do not think it is CE vs EE anymore, but rather whether you are using the https://github.com/Cotya/magento-composer-installer module.

@tylerssn are you using that module?

**Comment by convenient** [comment]
I am closing this issue as i am now 100% confident it is the same as #938 , just a different error message based on project specific configuration.

https://github.com/netz98/n98-magerun/issues/938#issuecomment-327143700
