### ISSUE TITLE
Can't install via Homebrew

### ISSUE THREAD

**Issue by dfridrich** [netz98/n98-magerun#943]
I am trying to install n98-magerun via **brew** but still can't do that because of SHA256 mismatch. I tried `brew update` and `brew upgrade`.

```➜  ~ brew install n98-magerun                                   
==> Installing n98-magerun from homebrew/php
==> Downloading https://files.magerun.net/n98-magerun-1.98.0.phar
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: 4e48652f347a48e9b323a0b042d0a97ce1f9ffb7ff48104a9143be217cb8fe63
Actual: 059a2a0212d998d6f1e93e7ca7c22b2c58a84d7c6ea6594622ed3c783be38749
Archive: /Users/dennis/Library/Caches/Homebrew/n98-magerun-1.98.0.phar
To retry an incomplete download, remove the file above.
➜  ~ 
```

**Comment by Filyox3** [comment]
Same here. I tried `brew cleanup` as well.

**Comment by ktomk** [comment]
The build-server looks broken, I can confirm that the sha256 hash for tag 1.98.0 of

    4e48652f347a48e9b323a0b042d0a97ce1f9ffb7ff48104a9143be217cb8fe63

is correct. But for the downloaded file, there seems to be the different checksum. So the error is correct, but we have a problem on the build-server.

**Comment by cmuench** [comment]
@dfridrich @Filyox3 I restored V1.98.0. Can you please check again if the brew installation is working again?

**Comment by cmuench** [comment]
@ktomk Found the problem in the build process, but I have no fix at the moment.

**Comment by Filyox3** [comment]
@cmuench, I've tried again and everything seems to be ok 👍 
Thank you! 🎉

**Comment by cmuench** [comment]
Great
