### ISSUE TITLE
Error on db:dump

### ISSUE THREAD

**Issue by cr15p** [netz98/n98-magerun#944]
When calling
` php n98-magerun.phar  db:dump --strip="@stripped"`
I got following error message:
`PHP Fatal error:  Call to undefined function N98\Magento\simplexml_load_file() in phar:///.../n98-magerun.phar/src/N98/Magento/DbSettings.php on line 63`
I'm running php version 5.6 at Ubuntu 16.04.3 LTS, although that shouldn't matter.

Did i do something wrong or is it a known issue?

P.S. Just downloaded magerun today. so should be latest version

**Comment by ktomk** [comment]
Looks like you don't have the SimpleXML Module activated on PHP 5.6 in CLI (command-line-interface). Can't say which packages you're using, with *Sury* that is:

    $ sudo apt-get install php5.6-xml

Can't say for vanilla Ubutnu packages, perhaps similar. *Sury* is https://deb.sury.org/ .
