### ISSUE TITLE
Try to access table before creating it 

### ISSUE THREAD

**Issue by berliozd** [netz98/n98-magerun#947]
Hi,
I have just tried to install Magento 2 using the following command : 
magerun install --noDownload

I follow the instructions and answer the questions but then the following error occurs : 
[RuntimeException]                                                                                                                                                                                       
  Installation failed (Exit code 42). Starting Magento installation:                                                                                                                                       
  File permissions check...                                                                                                                                                                                
  [Progress: 1 / 481]                                                                                                                                                                                      
  Required extensions check...                                                                                                                                                                             
  [Progress: 2 / 481]                                                                                                                                                                                      
  Enabling Maintenance Mode...                                                                                                                                                                             
  [Progress: 3 / 481]                                                                                                                                                                                      
  Installing deployment configuration...                                                                                                                                                                   
  [Progress: 4 / 481]                                                                                                                                                                                      
  Installing database schema:                                                                                                                                                                              
    [Zend_Db_Statement_Exception]                                                                                                                                                                          
    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.store_website' doesn't exist, query was: SELECT `main_table`.* FROM `store_website` AS `main_table` ORDER BY main_table.sort_order ASC, main_table.name ASC  

It looks like it is trying to read table store_website before having created it.

Thanks for your help.
Didier

**Comment by cmuench** [comment]
@berliozd If this is a customized Magento installation, please check if there is a `SchemaInstall` or `SchemaUpgrade` class which tries to get the data. Some common mistake is that data operations are done during in schema installation process.
Magerun only starts the installation process. The content of the setup classes will not be modified by magerun.
