### ISSUE TITLE
Selfupdate Updates Over and Over Again

### ISSUE THREAD

**Issue by sprankhub** [netz98/n98-magerun#952]
The `self-update` command seems broken with the latest version:

    simon@simonpad-t470s ~> n98-magerun.phar -V
    n98-magerun version 1.99.1 by netz98 GmbH
    simon@simonpad-t470s ~> sudo n98-magerun.phar self-update 

    It's not recommended to run n98-magerun as root user

    Updating to version 1.99.0.
     Downloading: 100%Successfully updated n98-magerun
    RECENT CHANGES
    ==============

    1.99.0
    ------

Even though I seem to already have a version >= `1.99.0`, it updates to `1.99.0` over and over again.

**Comment by sprankhub** [comment]
This falsy version number has already been fixed in 065ca48d80bb3b7c8bd0fc1fd45d33015a5bd6e1. The issue should be automatically fixed with the next version. But maybe it would be a good idea to skip version 1.99.1 then...

**Comment by cmuench** [comment]
Next version will be "1.100.0".
