### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Command\HelpCommand::isHidden() in vendor/symfony/console/Descriptor/ApplicationDescription.php:115

### ISSUE THREAD

**Issue by lfluvisotto** [netz98/n98-magerun#953]
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Command\HelpCommand::isHidden() in vendor/symfony/console/Descriptor/ApplicationDescription.php:115
Stack trace:
#0 vendor/symfony/console/Descriptor/ApplicationDescription.php(82): Symfony\Component\Console\Descriptor\ApplicationDescription->inspectApplication()
#1 vendor/symfony/console/Descriptor/TextDescriptor.php(194): Symfony\Component\Console\Descriptor\ApplicationDescription->getCommands()
#2 vendor/symfony/console/Descriptor/Descriptor.php(55): Symfony\Component\Console\Descriptor\TextDescriptor->describeApplication(Object(N98\Magento\Application), Array)
#3 vendor/symfony/console/Helper/DescriptorHelper.php(72): Symfony\Component\Console\Descriptor\Descriptor->describe(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(N98\Magento\Application), Array)
#4 phar:///us in vendor/symfony/console/Descriptor/ApplicationDescription.php on line 115

Using:

PHP 7.0.15-0ubuntu0.16.04.4

Composer:

"name": "symfony/console",
"version": "v3.2.8"

**Comment by cmuench** [comment]
Duplication of #938
