### ISSUE TITLE
Flushing only config cache after disabling a module

### ISSUE THREAD

**Issue by szepeviktor** [netz98/n98-magerun#962]
This is how I disable a module.
```
n98-magerun dev:module:disable Module_Name
n98-magerun cache:flush
```
We use Redis and PHP OPcache, so var/cache is empty.

Is there a way to disable a module without flushing everything thus **logging out** admins?

**Comment by cmuench** [comment]
@szepeviktor You should run a separate redis instance for your session data. Another way is that you use the cache:clean command. This will not clear the complete cache at once.

**Comment by szepeviktor** [comment]
> You should run a separate redis instance for your session data.

Thank you!
