### ISSUE TITLE
N98-magerun not working on Debian 9 and PHP 7

### ISSUE THREAD

**Issue by gbarranco** [netz98/n98-magerun#963]
Hello !
I have a development environment on Debian 9 with PHP 7. I installed n98-magerun like this :
`wget https://files.magerun.net/n98-magerun.phar`
I gave the right to execute it to all (like advised on the homepage of the project).
I copied it in /usr/local/bin.
This is what I get when I run it : 
`dev@dev:~/public_html$ n98-magerun.phar --version`
` `
I can wait as long as I want, it doesn't change anything, the server never returns.
I copied the line `suhosin.executor.include.whitelist="phar"` in /etc/php/7.0/cli/php.ini (I put it just under the line [PHP], to be sure it will be executed.

I can't find someone with the same problem on the net. Can you help me, please ? 

Thank you by advance

**Comment by cmuench** [comment]
@gbarranco There could be a lot of possibilities.
Can you install composer (they have the same requirements) to run a phar file.
The installer tests the platform requirements.

```
php -r "readfile('https://getcomposer.org/installer');" | php
```

**Comment by gbarranco** [comment]
@cmuench > I have the same problem with the command you gave me (it's been close to twenty minutes I launched it and still no response).
I have to precise I have a pretty cool connection here at work.

**Comment by cmuench** [comment]
So we can exclude a n98-magerun problem.
This looks like a network issue.
Can you download the installer with curl or wget?

**Comment by gbarranco** [comment]
Yes I have downloaded the package with wget, like I said in my first post.
Also I can ping the Google's DNS 8.8.8.8 and all from this machine.

**Comment by gbarranco** [comment]
I deleted the package and could reinstall it using Curl, this time. Still the same problem

**Comment by cmuench** [comment]
@gbarranco For me something is corrupt in your system. I watched a video of a guy who installed composer without any problems on Debian 9.

https://www.youtube.com/watch?v=tzNNrEO2wFM

**Comment by gbarranco** [comment]
@cmuench I installed composer without problem with apt-get maybe there is some conflict or something ?

**Comment by cmuench** [comment]
Yes, with apt-get, but the PHP based installation is not working. So it looks like a problem with the PHP installation.

**Comment by gbarranco** [comment]
@cmuench : I found the problem !!! \o/

But it was a really stupid problem : I had to debug some cli script so I configured my environment and my IDE to use Xdebug but I didn't cut it. I stopped PHPStorm to listen Xdebug connections and it work !

Thank you very much for your help
