### ISSUE TITLE
direct link to sha256 checksum

### ISSUE THREAD

**Issue by dhpowrhost** [netz98/n98-magerun#971]
Is there a direct link to a file that only contains the sha256 checksum? For use for my configuration-management system (saltstack)

**Comment by cmuench** [comment]
@dhpowrhost Yes!
Example:

https://files.magerun.net/sha256.php?filename=n98-magerun-latest.phar

Replace the filename query parameter with your downloaded version.

**Comment by cmuench** [comment]
@dhpowrhost Sorry, the correct query parameter name is "file".

https://files.magerun.net/sha256.php?file=n98-magerun-latest.phar

**Comment by dhpowrhost** [comment]
perfect
