### ISSUE TITLE
Database dumps with @development stripped group has no admin roles or rules

### ISSUE THREAD

**Issue by maderlock** [netz98/n98-magerun#972]
Using n98 1.100.0

Previously @development strips have included admin rules and roles. These tables are no longer, which is slowing down our testing as we work out how to recreate the specific rules that we have on production.

It seems odd that this data is stripped as it is needed for development and testing and has nothing to do with customers. Perhaps there could be a group for admin data so that it was easy to add this to the list to strip?

**Comment by maderlock** [comment]
Hmm - looking at the updated readme file (doesn't match the documentation pages which confused me), I could use --strip="@trade @stripped" and this would give the old meaning of @development?

**Comment by RoussKS** [comment]
@maderlock yep, that's changed a while back. Had the same issue myself

Checking the config.yaml file, these are the tables that the development tag removes

> "@admin @trade @stripped @search @newsletter @emails"

So do all but @admin :)

**Comment by cmuench** [comment]
#353

**Comment by cmuench** [comment]
Sadly we forgot to describe the "@table" group in the readme.
This was fixed with #976.
