### ISSUE TITLE
db:dump --add-time does not add timestamp to filename

### ISSUE THREAD

**Issue by Quazz** [netz98/n98-magerun#974]
This used to work, but no longer. 

I use the command

`php /var/www/vhosts/example.com/public_html/n98-magerun.phar db:dump --add-time --compression="gzip" --force`

to generate a database dump. The dump itself works as expected, but the filename remains databasename.gz, as opposed to databasename-timestamp.gz

**Comment by ktomk** [comment]
Can you share in which version this worked for you and for which version you report the flaw?

**Comment by Quazz** [comment]
I don't entirely remember what version it worked in. I only noticed it not working as expected earlier when I was checking backups. 

Can't have been more than 10 versions ago that it worked though, if I remember correctly. 

It runs automatically in a script, which is why I'm not sure when it went wrong.

**Comment by AScaredSquirrel** [comment]
It's working in my local environment which has version 1.97.28 installed.
It's **not** working on a dev server which has version 1.100.0 installed.

Can't say anything about versions between them.

**Comment by gety9** [comment]
+1, i use 
`
docker exec -ti mag_cron_1 magerun db:dump --add-time --strip="@development"`

and stamp is not added.

Output is identical to 
`
docker exec -ti mag_cron_1 magerun db:dump --strip="@development"`

**Comment by kkrieger85** [comment]
@gety9 @AScaredSquirrel @Quazz did you try to use `--add-time` in this way: `--add-time="prefix"`

For me prefix did not work with simple `--add-time` but worked with `--add-time="prefix"`

**Comment by Quazz** [comment]
Can confirm that `--add-time="prefix"` works as expected. Thanks for the find!

**Comment by kkrieger85** [comment]
As n98-magerun uses `"symfony/console": "~2.3",` [1](https://github.com/netz98/n98-magerun/blob/1.102.0/composer.json) there is no default value for option `add-time` [2](https://symfony.com/doc/2.8/console/input.html#options-with-optional-arguments)
