### ISSUE TITLE
Running commands from code (Magento 1.9.x)

### ISSUE THREAD

**Issue by shineability** [netz98/n98-magerun#975]
Is it possible to run Magerun commands from your code (Models, Observers, ...) without using `exec()` as you would in Laravel and Symfony?

**Comment by ktomk** [comment]
Technically yes, however you need to add Magerun as a dependency. And that is somewhat theoretical, I never did it that way round.

If you share a bit more about your concrete use-case, it's perhaps possible to give better hints.

**Comment by shineability** [comment]
In a custom Magerun command we can run another command like this, e.g.:

```
$this->getApplication()->run(new StringInput('index:reindex:all'), $output);
$this->getApplication()->run(new StringInput('fullservice:magmi:generate --staging'), $output);
...
``` 

If we need to run the same code triggered by a cron job, not in a CLI context, how could we reuse this command. Since we're not executing from a Command class we don't have access to `$this->getApplication()`, right?

For example, in Laravel you can do:
``` 
Artisan::call('migrate:refresh', [ '--force' => true]);
```

**Comment by cmuench** [comment]
Running n98-magerun command inside of Magento modules is not a best practice. The main idea of n98-magerun is to provide functionality without changing the source code of a installed Magento instance.
