### ISSUE TITLE
Dry-run for selfupdate

### ISSUE THREAD

**Issue by szepeviktor** [netz98/n98-magerun#981]
Could we have `n98-magerun selfupdate --dry-run` to only check for new version.
Thanks!

**Comment by cmuench** [comment]
Yes, nice idea. Thanks.

**Comment by tobiasdalhof** [comment]
I think it makes more sense to check for new versions in `$ n98-magerun --version`

**Comment by cmuench** [comment]
The "--version" option is a build-in option of the Symfony Console component. I am not sure if I like that.

**Comment by cmuench** [comment]
We already implemented that in n98-magerun2 in the self-update command.

**Comment by szepeviktor** [comment]
@cmuench I see :)

https://github.com/netz98/n98-magerun2#update

**Comment by cmuench** [comment]
@szepeviktor The --dry-run option was provided with V1.102.0 release.

**Comment by szepeviktor** [comment]
Thanks.
