### ISSUE TITLE
db:dump and anonymized user data

### ISSUE THREAD

**Issue by ThomasNegeli** [netz98/n98-magerun#982]
Are there any plans to implement a userdata anonymization when dumping the db?
On some installations we need the real customer account in developer environments, with complete account history, but we do not need real user data.

**Comment by cmuench** [comment]
We do not have plan to add this feature to n98-magerun.
There is a 3rd party module available to anonymize customer data.
https://github.com/kalenjordan/magerun-addons#anonymize-customer-data

**Comment by cmuench** [comment]
Currently there are no plans to port that 3rd party command to the n98-magerun core.
