### ISSUE TITLE
Enable symlinks without clearing sessions cache or redis flushdb

### ISSUE THREAD

**Issue by AdrianBalcan** [netz98/n98-magerun#983]
In a scenario where I run Magento in Kubernetes Pods, I have to enable symlinks every time when a Magento pod is starting/restarting. But I am loosing Magento sessions because n98-magerun is running "flushdb". How can I enable symlink without loosing Magento sessions?

**Comment by cmuench** [comment]
@AdrianBalcan Die you try to set the config value with "config:store:set" command?

**Comment by cmuench** [comment]
Closed. No due to no reaction. Feel free to re-open if you have any new information.
