### ISSUE TITLE
Fallback folder /tmp/magento/var is used in n98-magerun when running through SSH

### ISSUE THREAD

**Issue by gety9** [netz98/n98-magerun#985]
Guys hi,

I am using n98-magerun in docker container. And when i run commands directly in docker console everything works great. For example
`
docker exec -ti mag1_cron_1 magerun config:set web/unsecure/base_url http://mag1.net/`
changes base url.

However when i connect to server through SSH using putty, it says 

"Fallback folder /tmp/magento/var is used in n98-magerun.
n98-magerun is using the fallback folder. If there is another folder configured for Magento, this can cause serious problems."
https://puu.sh/A7mZt/66f9373524.png
and none of the commands work.

The permission of var/cache folder is set correctly. How can i solve this?

**Comment by ktomk** [comment]
Use the correct user when executing the command inside the docker container. `docker exec` offers the `-u` switch for that. HTH.
