### ISSUE TITLE
magerun customer:create, not a valid email address

### ISSUE THREAD

**Issue by seansan** [netz98/n98-magerun#989]
I am issuing 

magerun customer:create john johndoe@gmail.com password John Doe
This value is not a valid email address.
Email: ^C

Based on the example in the readme
error is This value is not a valid email address.

**Comment by ktomk** [comment]
but the address is valid, correct? can you please also add the help output of that command, just the report is more clear?

**Comment by seansan** [comment]
my bad. mixing up admin create magerun admin:user:create
