### ISSUE TITLE
admin:user:unlock throws error messages 

### ISSUE THREAD

**Issue by samihsoylu** [netz98/n98-magerun#995]
The command line interfaces is throwing a fatal error when I try to unlock an admin account. I did not see a issue about this on here, and I thought I should mention it. 

Error was encountered on: Magento 1.9.3.3

```
PHP Fatal error:  Uncaught Error: Call to a member function unlock() on boolean in phar:///usr/local/bin/n98-magerun/src/N98/Magento/Command/Admin/User/UnlockCommand.php:87
Stack trace:
#0 phar:///usr/local/bin/n98-magerun/vendor/symfony/console/Command/Command.php(264): N98\Magento\Command\Admin\User\UnlockCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/local/bin/n98-magerun/src/N98/Magento/Command/AbstractMagentoCommand.php(473): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/n98-magerun/vendor/symfony/console/Application.php(868): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/n98-magerun/vendor/symfony/console/Application.php(191): Symfony\Component\Console\Application->doR in phar:///usr/local/bin/n98-magerun/src/N98/Magento/Command/Admin/User/UnlockCommand.php on line 87
```

**Comment by emulgeator** [comment]
Are you guys still investigating? :P

**Comment by cmuench** [comment]
@emulgeator yes 😁

**Comment by cmuench** [comment]
@emulgeator This command works only in Magento Enterprise Edition.
You are using 1.9.3.3 which looks for me like a Community Edition version.
The command should be hidden if you are using a Community Edition.
Can you really see the command in your command list?

**Comment by emulgeator** [comment]
@cmuench I think you wanted to address your question to @SamihSoylu who opened the issue.
But ours is 1.7.0.2

**Comment by cmuench** [comment]
@SamihSoylu This command works only in Magento Enterprise Edition.
You are using 1.9.3.3 which looks for me like a Community Edition version.
The command should be hidden if you are using a Community Edition.
Can you really see the command in your command list?

**Comment by samihsoylu** [comment]
Incredible, I was not notified that there was a response to this issue. Since the new GitHub app I could see that I have not replied. 

@cmuench I can no longer reproduce this issue. It appears to be hidden indeed.
